### ISSUE TITLE
azcopy make doesn't work when executed from Azure DevOps

### ISSUE THREAD

**Issue by SupriyaGangineni** [Azure/azure-storage-azcopy#1006]
I am using the azcopy_10.4.3 version. I am trying to create a new container on a Target Storage account. The following command works when I execute locally in PowerShell.

./azcopy.exe make 'https://{storageaccount}.blob.core.windows.net/{containername}?{SASToken}'

The SASToken has rcwdl permissions.

The same command with the same SAS token consistently fails when executed from Azure DevOps pipelines from both PowerShell and Azure Powershell Tasks with the error "**no SAS token or OAuth token is present and the resource is not public"** .

**Comment by JohnRusk** [comment]
Sounds like something may be going wrong with the command line parsing in the devops pipeline.  Can you set up a little pipeline task that just echoes its parameters to a log file, and pass it the same parameters as you are passing to AzCopy (maybe use a SAS that's already expired, if you don't want to log a live SAS into your debug logs).  Then see if there's an evidence of something going wrong there.

**Comment by SupriyaGangineni** [comment]
Hi John. Yes I tried all the above option of printing the entire syntax of the AzCopy command along with SAS token. The generated command works perfectly from local machine, but consistently fails from Azure DevOps  release pipelines.

**Comment by JohnRusk** [comment]
And you are using the same command processor in both places? E.g. PowerShell in both places, or CMD in both places?

**Comment by SupriyaGangineni** [comment]
Yes. PowerShell in both the places. Tested with Azure PowerShell as well.

**Comment by JohnRusk** [comment]
Are you using the same SAS token in both places?  To create a container that definitely does not exist beforehand?

**Comment by JohnRusk** [comment]
(Just trying to eliminate any easy causes, before puzzling over hard ones!)

**Comment by SupriyaGangineni** [comment]
Yes. The same SAS Token is used at both the places . In fact this token is being generated from the Pipeline and used both locally and from pipeline.

**Comment by JohnRusk** [comment]
Is it possible that, when used from the DevOps pipeline, some, or all, of the SAS token is being removed by the pipline?  I ask because SAS tokens are usually considered to be authentication secrets.  Some tooling removes or redacts part of the SAS token for exactly that reason. (E.g. AzCopy's own logging code does that, when logging URLs to the azcopy log file).

If something in your tooling or pipeline was looking at the SAS and saying, "oh, that looks like a SAS token, I should redact it", that could explain what you are seeing.  In particular, I have just done some tests and verified the following:

1. If I remove the "sig=...." portion of the SAS I see the error that you see. 
2. If I remove just the value after sig=,I also see the error that you see.
3. I currently cannot find any other way to reproduce the error that you are seeing, other than removing the whole SAS token (which has the same effect).

**Comment by JohnRusk** [comment]
I can't think of anything more that we, on the AzCopy team, can do to help with is issue at this time.  Let us know if you think of something.

**Comment by SupriyaGangineni** [comment]
Hi John, changing the single quotes to double quotes in the below command resolved the issue. Appreciate all you help on this issue. Thank you.

Failed Command: ./azcopy.exe make 'https://{storageaccount}.blob.core.windows.net/{containername}?{SASToken}'

Working Command: ./azcopy.exe make "https://{storageaccount}.blob.core.windows.net/{containername}?{SASToken}"

**Comment by JohnRusk** [comment]
Thanks for the update. Glad to hear its working for you now.
