### ISSUE TITLE
Preserve Source File Timestamps on Upload to Blobs

### ISSUE THREAD

**Issue by leswaters** [Azure/azure-storage-azcopy#1039]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync

### What problem was encountered?
azcopy loses the original file metadata for Creation, LastWrite, and LastAccess.

### Have you found a mitigation/solution?
This is certainly known that **azcopy** does not preserve file timestamps when uploading to blob storage. This can be remedied by optionally pushing the file timestamps up to Azure storage as metadata properties.

Recommendation is to add new switch **--put-timestamps** which will create three metadata attributes for each uploaded file:  *CreationTimeUTC*, *LastWriteTimeUTC*, *LastAccessTimeUTC* which have the UTC times of the original file. Using UTC time ensures no time zone issues.

The following illustrates how to do this using PowerShell :
```
$file = "SampleFile.txt"
$FileInfo = Get-ChildItem -Path $file
$FileMetadata = @{ "CreationTimeUTC"= $FileInfo.CreationTimeUtc; "LastWriteTimeUTC"=$FileInfo.LastWriteTimeutc; "LastAccessTimeUTC"=$FileInfo.LastAccessTimeUtc; "Origin"=$FileInfo.FullName }

$x = Set-AzStorageBlobContent -Metadata $FileMetaData -Container "contosoupload" -File ".\$file" -Blob $file -Context $c
```

As an further enhancement, **AzCopy sync** could be enhanced with a **--use-timestamps** which would preserve the file timestamps found in the metadata when downloading to a PC. It could also be used for the synchronization itself. This would allow AzCopy sync to work with multiple computers sharing the same container (i.e., shared synchronized data).

Another minor enhancement would be to have **--Put-Origin** switch which would add an *Origin* metadata attribute showing the file origin:

![MetadataExample](https://user-images.githubusercontent.com/30345058/83946137-cc5ae300-a806-11ea-9763-83fafdaf9409.PNG)

**Comment by lesterw1** [comment]
The use case I have is to move files from one PC to another and preserve all of the timestamps in the process.  One solution is to zip up the files before moving them. Works for a small number of files; not so great for a large number.

A crude work-around is to generate a file which contains all of the timestamps for the relevant files and upload that along with the files. The PowerShell below will generate such a file:

```
Get-ChildItem -File -Recurse `
    | Select-Object -Property FullName, Length, CreationTimeUtc, LastAccessTimeUtc, LastWriteTimeUtc, Attributes `
    | ConvertTo-json | out-file "FileTimestamps.json"
```

And then when you do a restore, you use the timestamps file to restore the original timestamps for all of the files after downloading completes. 

This would be a whole lot easier if **AzCopy** could preserve the original file timestamps as blob metadata tags.

**Comment by JohnRusk** [comment]
Versions 10.4 and later support preserving timestamps when uploading to Azure Files. I'll change the title to make it clear that this request is about blobs.

**Comment by lesterw1** [comment]
Any progress on adding this feature?  Even just preserving the source file's **LastModified** timestamp in ISO-8601 format with a **--put-timestamps** switch would be great.

**Comment by JohnRusk** [comment]
@lesterw1 I've moved on to a different project, so can't answer your question sorry.  @rishabpoh or @zezha-msft might be able to respond.

**Comment by Satyajeet331** [comment]
Hi,
I have a scenario where I have to upload and download the huge file (TB) in Linux  and preserve date and time, Is this is feasible with new Azcopy 10.8 version ' --preserve-last-modified-date'

**Comment by phrak** [comment]
Is there any solution to maintain the last modified dates yet please?

**Comment by jacobwilde** [comment]
+1 for this feature.

**Comment by lesterw1** [comment]
@rishabpoh or @zezha-msft Is there any update on this?  It's an easy feature to implement as it only requires adding a couple extra metadata fields and a switch such as **--put-timestamps** as shown in the comments above.

**Comment by zezha-msft** [comment]
Sorry for the delay and we appreciate your patience.

To create an adequate solution, I'll be submitting a formal request to the service to add a user-settable lmt field. The reason is that the easier solution of simply using metadata is problematic: if only AzCopy was setting it, then how can AzCopy operate on existing files or the files uploaded by other tools? A user-settable lmt would solve this concern and let all tools leverage the same field.

**Comment by lesterw1** [comment]
Thanks @zezha-msft.  As for your point about simply using metadata, I don't see it as a problem. If the 'lmt' field is the blob last-modified-time, that would be great to be able to set. I asked for that feature years ago and there wa s alittle push-back from the dev teams due to some issue with billing (if my memory serves). If there is push back, then having the metadata would be the next best option.  Keep us posted on progress. Thank you.

**Comment by zezha-msft** [comment]
@lesterw1 Thanks for the context!

I'll definitely be advocating for this change to happen since it improves the sync behavior immensely.

Service changes may take a while to ship unfortunately, but I think it ultimately is the best solution.

**Comment by peter-bertok** [comment]
> Service changes may take a while to ship unfortunately

Is there an approximate ETA?

The lack of this feature means many common operations are impossible. For example, copying a blob container to another container will reset timestamps, wiping out the info needed for tiering.

Similarly, legal hold and similar features (or end-user code doing the same thing) can't rely on the timestamps either, because they're not the "content timestamps", but "maintenance operation timestamps" instead. These have no business meaning.

**Comment by vansree** [comment]
Is there any update on this?

I have Raw blob container and curated blob containers and when ever I upload, they are getting the latest datetime and hard to sync

What is the ETA if planned on this ? TIA

**Comment by leswaters** [comment]
@zezha-msft If **LastWriteTimeUTC** and **CreateTimeUTC** are used as the metadata property names (by convention), then any application (including AZCopy) could read / modify these attribute fields. This would not require and service level change to accomodate (i.e., to add an lmt field) since this would use the existing metadata fields.  These property names would simply be by convention, which AZCopy could write by default (or at least if a **--put-timestamps** switch was specified). 

![image](https://user-images.githubusercontent.com/30345058/169989784-fa42a41a-ee79-4f7c-b75f-736c0d84681d.png)

Of course, having two dedicated properties for this would be a great service extension. :)

**Comment by zezha-msft** [comment]
Hi @leswaters @vansree, thanks for following up on this feature. We are actively working on it: https://github.com/Azure/azure-storage-azcopy/pull/1780

The new feature will allow the user to preserve POSIX attributes, including the timestamps, on blobs as metadata.

**Comment by zezha-msft** [comment]
Released in 10.16.

**Comment by thierrylach** [comment]
This is not very useful for microsoft operating systems.

failed to parse user input due to error: in order to use --preserve-posix-properties, both the source and destination must be POSIX-aware (Linux->Blob, Blob->Linux, Blob->Blob)

**Comment by anonymouse-jj** [comment]
Like @thierrylach said this doesn't work for windows os.

@zezha-msft are there any plans to implement it for windows?

**Comment by mrboojum** [comment]
Upvote for implementation on Windows

**Comment by Nehmiabm** [comment]
Looks like there's no hope in supporting this on windows as they have closed the issue that was created to track the effort. Oh, well :(

**Comment by baggs1981b** [comment]
Closing this and leaving Windows without a solution is very unhelpful.

We need to be able to retain file timestamps and as far as I can see with the Metadata workaround it means uploading each individual file to Azure because you can't dynamically apply metadata for each file within a bulk upload, using recursive upload with azcopy of a folder of say 1000 local items would put the same metadata on all 1000. I'm not sure if this massively increases the overhead or if it inflates the actions count.

There must be a wider need for retaining the true timestamps of files from windows origin surely?

**Comment by awsles** [comment]
Re-opened as https://github.com/Azure/azure-storage-azcopy/issues/3194.
If you are interested in this as an AZCOPY feature, please comment on the above request.

**Comment by vansree** [comment]
yes, please
