### ISSUE TITLE
Add include-before filter

### ISSUE THREAD

**Issue by JohnRusk** [Azure/azure-storage-azcopy#1075]
Include-after is in 10.5.  The comments here outline a feature request for include-before: https://github.com/Azure/azure-storage-azcopy/issues/716#issuecomment-651444644

**Comment by basty0722** [comment]
Does this option work with "--overwrite IfSourceNewer" ?

**Comment by landro** [comment]
Hi @JohnRusk , any chance you'll be able to add this in near future? We're about to migrate some TBs to azure, and it would be really helpful to have this feature in order to handle files added while azcopy is traversing the source tree (hours) to be handled separately by some other process/mechanism.
I haven't looked at the code, but shouldn't this be fairly easy to add?

**Comment by JohnRusk** [comment]
Yes, it could be easy to add (I think).  FYI I moved to a different team a few months ago, so I no longer work on AzCopy.  @rpohane and @amishra-dev are the folks to talk to about prioritization of work.

**Comment by landro** [comment]
Hi @rpohane and @amishra-dev! Any chance you'll be able to add this feature in near future?

**Comment by evenh** [comment]
I'm working on this feature

**Comment by amishra-dev** [comment]
@evenh tag me when you have the review out, i would be happy to get it reviewed. Thanks
