### ISSUE TITLE
Versioning of deleted/overwritten files

### ISSUE THREAD

**Issue by martinweihrauch** [Azure/azure-storage-azcopy#1083]
Hi!
Is there any way to set in the sync or backup mode that deleted/overwritten files get versioned to e. g. a hidden subfolder and it is possible to e. g. keep 5 versions?
That would be great, because I am synching from Azure to a local machine as backups. If someone would delete files accidentally on azure, then also the synched files would disappear. The same would be if I set it to "copy" and a new version of a file overwrites.

**Comment by mohsha-msft** [comment]
Hey @martinweihrauch ,

If you're using blob storage, I think [versioning feature](https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services) might be what you are looking for. which when enabled on your Azure storage account, can help restore an earlier version of a blob to recover your data if it is erroneously modified or deleted. After you enable blob versioning for a storage account, Azure Storage automatically maintains versions for every blob in the storage account. 

In AzCopy, we support downloading/deleting given blob versions currently. If you overwrite an already existing blob, instead of deleting the previous version, a new version will be created.

**Comment by mohsha-msft** [comment]
This feature is still not supported in `sync` but we look forward to adding that in the future releases.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality. We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
