### ISSUE TITLE
Piping doesn't work with AD login

### ISSUE THREAD

**Issue by msmouse** [Azure/azure-storage-azcopy#1140]
### Which version of the AzCopy was used? 
AzCopy 10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac & Linux

### What command did you run?
after `azcopy login` successfully,

`azcopy cp "/local/path/to/file" "https://blah.blob.core.windows.net"/blah/1.txt"` works
`azcopy cp "https://blah.blob.core.windows.net"/blah/1.txt" | cat` works

but

**`cat | azcopy cp "https://blah.blob.core.windows.net"/blah/1.txt"` doesn't work - the command quits with 1 and there’s no output on stdout or stderr**

although

`cat | azcopy cp "https://blah.blob.core.windows.net"/blah/1.txt?[SAS]"` does work.

### What problem was encountered?

_`cat | azcopy cp "https://blah.blob.core.windows.net"/blah/1.txt"` doesn't work._

### How can we reproduce the problem in the simplest way?

repeat the above commands.

### Have you found a mitigation/solution?

generate unnecessary SAS.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/425

**Comment by mohsha-msft** [comment]
Hey @msmouse 

Thanks for reaching out and I apologize for the late reply.
We've fixed the issue in [AzCopy v10.6.1](https://github.com/Azure/azure-storage-azcopy/blob/master/ChangeLog.md#version-1061). Check out https://github.com/Azure/azure-storage-azcopy/pull/1220 to know more.  😄 

Please try to use AzCopy version >= 10.6.1 and reach out to us if the issue is still persisting
