### ISSUE TITLE
where are all of the environment variables defined in the documentation?

### ISSUE THREAD

**Issue by jpsebasti** [Azure/azure-storage-azcopy#1147]
I'm having a variety of problems with Azure Storage Explorer 1.14.2 in trying to copy hundreds of thousands of small files from a blob container in one storage account to another storage account in my same subscription.   Microsoft engineers have suggested using azcopy command line which I've tried (10.6.0) but I get thousands upon thousands of COPYFAILED errors with the error text cannot simultaneously send two files to the same destination name.   I'm running on Windows 2016 DataCenter OS in my Azure v-net.  

The MS Engineers suggested making changes to the azcopy environment.  So I look up in the Reference azcopy env and there is one friggin page of info on this command with no documentation or examples of how to call it.
When in the CMD screen, I can issue azcopy env and I get a list of many current values for my environment variables but many of those values don't show anything with a description text that say the default is based on something or other (machine size, #CPUs, etc).  If you don't actually show in the azcopy env command output what the current values are, how am I supposed to know what values to use in tweeking the environment?  Also, if there are no examples of how to use the azcopy env command to set environment variables in the documentation, how am I supposed to know how to use it?   azcopy env --help   shows practically useless information.  No examples of how to set environments, no information on what environment variables I can set.  As far as I can tell there is no info in the documentation on what environment variables I can set.

**Comment by jpsebasti** [comment]
I've gathered from other posts on the internet that you need to set these environment variables at the OS command prompt with set AZ....=value
Where are the environment variables documented?

**Comment by mohsha-msft** [comment]
Hey @jpsebasti ,

I appreciate you reaching out and I apologize for late response. 
You can find about all the environment variables by simply executing `azcopy env` command. Just to make things simple for you, here is the list of environment variables which you can set.

------------------------------------------------------------------------------------------------------------------------------
`AZCOPY_CONCURRENCY_VALUE` Overrides how many HTTP connections work on transfers. By default, this number is determined based on the number of logical cores on the machine.

`AZCOPY_CONCURRENT_FILES` Overrides the (approximate) number of files that are in progress at any one time, by controlling how many files we concurrently initiate transfers for.

`AZCOPY_CONCURRENT_SCAN` Controls the (max) degree of parallelism used during scanning. Only affects parallelized enumerators, which include Azure Files and Local File Systems.

`AZCOPY_PARALLEL_STAT_FILES` Causes AzCopy to look up file properties on parallel 'threads' when scanning the local file system.  The threads are drawn from the pool defined by AZCOPY_CONCURRENT_SCAN.  Setting this to true may improve scanning performance on Linux.  Not needed or recommended on Windows.

`AZCOPY_LOG_LOCATION` Overrides where the log files are stored, to avoid filling up a disk.

`AZCOPY_JOB_PLAN_LOCATION` Overrides where the job plan files (used for progress tracking and resuming) are stored, to avoid filling up a disk.

`AZCOPY_BUFFER_GB` Max number of GB that AzCopy should use for buffering data between network and disk. May include decimal point, e.g. 0.5. The default is based on machine size.

`AWS_ACCESS_KEY_ID` The AWS access key ID for S3 source used in service to service copy.

`AWS_SECRET_ACCESS_KEY` The AWS secret access key for S3 source used in service to service copy.

 `AZCOPY_SHOW_PERF_STATES` If set, to anything, on-screen output will include counts of chunks by state

 `AZCOPY_PACE_PAGE_BLOBS` Should throughput for page blobs automatically be adjusted to match Service limits? Default is true. Set to 'false' to disable

`AZCOPY_DEFAULT_SERVICE_API_VERSION` Overrides the service API version so that AzCopy could accommodate custom environments such as Azure Stack.

`AZCOPY_SPA_CLIENT_SECRET` The Azure Active Directory client secret used for Service Principal authentication

`AZCOPY_SPA_CERT_PASSWORD` The password used to decrypt the certificate used for Service Principal authentication.

`AZCOPY_TUNE_TO_CPU` Set to false to prevent AzCopy from taking CPU usage into account when auto-tuning its concurrency level (e.g. in the benchmark command).

`AZCOPY_CACHE_PROXY_LOOKUP` By default AzCopy on Windows will cache proxy server lookups at hostname level (not taking URL path into account). Set to any other value than 'true' to disable the cache.

`AZCOPY_USER_AGENT_PREFIX` Add a prefix to the default AzCopy User Agent, which is used for telemetry purposes. A space is automatically inserted.

--------------------------------------------------------------------------------------------------------------------------------------

Now apart from that, you need to setup few other Environment variables.:- `ACCOUNT_NAME, ACCOUNT_KEY, APPLICATION_ID, CLIENT_SECRET, and TENANT_ID`. These variables are hidden so won't be visible by executing `azcopy env` command.
`ACCOUNT_NAME and ACCOUNT_KEY` refers to the name and key of Azure Storage Account.

As for `APPLICATION_ID, CLIENT_SECRET, and TENANT_ID`, those are setup in `azcopy login` command by specifying flags. It wouldn't be necessary for Account Key Auth.

If the given explanation doesn't answer your question, please don't hesitate to reply on this thread and I'll be more than happy to help you out 😄
