### ISSUE TITLE
Detailed information when downloading from Azure blob

### ISSUE THREAD

**Issue by AlexBlain** [Azure/azure-storage-azcopy#115]
Currently, we only see the throughput displayed when we download a file from a blob.
If we add the option --output=json, it adds a bit more information but that is not readable from an end user perspective.
We would need to have the size of the file being downloaded, the time remaining, the size remaining, etc.

**Comment by zezha-msft** [comment]
Hi @AlexBlain, thanks for reaching out!

To clarify, the JSON output is not meant to be read by the end user; it's for applications that spawn AzCopy to easily parse the output.

Could you please clarify what the expected behavior is? Did you mean you wanted to see the throughput in the JSON?

The real time throughput can be easily computed with the fields `Timestamp` and `TotalBytesTransferred`. In fact, that's how the throughput was calculated when `--output=text`: throughput = (current `TotalBytesTransferred` - previous `TotalBytesTransferred`)/(current `Timestamp` - previous `Timestamp`).

Remaining bytes is equal to `TotalBytesEnumerated` - `TotalBytesTransferred`.
