### ISSUE TITLE
azcopy sync removing files

### ISSUE THREAD

**Issue by Disordely** [Azure/azure-storage-azcopy#1203]
### Which version of the AzCopy was used? 
10.4.3
### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows

### What command did you run?
Job-Command sync https://REDACTED.blob.core.windows.net/kf-mpo-files/?se=REDACTED-REDACTED-&sp=rlpx&REDACTED C:\Windows\System32\REDACTED\MPO --recursive --delete-destination true 
### What problem was encountered?
When two syncs happened at the same time (separate triggers), one of the syncs deleted the destination files. The log shows "Deleting incomplete destination file"
[ee473184-c8a6-3c4f-75f0-55fcf5936304.log](https://github.com/Azure/azure-storage-azcopy/files/5346310/ee473184-c8a6-3c4f-75f0-55fcf5936304.log)

### How can we reproduce the problem in the simplest way?
we are struggling to reproduce it, it is very random but it looks like it only happens (sometimes) when two azcopy jobs run at the same time - on the one that deletes the destination files the log says "File Creation Error destination file has no known flags that could cause issue (current set: 20) and azcopy was unable to clear the flag(s), so access will be denied: The process cannot access the file because it is being used by another process." and then later on "Deleting incomplete destination file"

### Have you found a mitigation/solution?
no

**Comment by zezha-msft** [comment]
Hi @Disordely, thanks for reaching out!

It sounds like you are running into a race condition. You are running two syncs:

1. source1 -> C:\Windows\System32\REDACTED\MPO
2. source2 -> C:\Windows\System32\REDACTED\MPO

Right?

Since --delete-destination is set to true, each AzCopy instance will try to delete extra files at the destination that don't exist at the sources, and since the source1 and source2 are different, this may create a case where a specific file is being deleted, but the other instance is trying to write it.

My suggestion is to use the copy command with `--overwrite=ifSourceNewer` instead, which does not detect extra files at the destination. It is more efficient and suits your scenario better. 

More info about sync is available [here](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide).

Please let us know if you have any other question.
