### ISSUE TITLE
--list-of-files, how to upload files without creating subdirectories in azure container

### ISSUE THREAD

**Issue by weiwei-liu** [Azure/azure-storage-azcopy#1233]
### Which version of the AzCopy was used? 
V10

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`.\azcopy copy "\\?\UNC\" "https://my_storage_account.blob.core.windows.net/container_name/target_folder/" --list-of-files copyfile.txt`

contents of `copyfile.txt` are the paths of files on the network drives.

> servername1\path\to\file\foo.txt
> servername2\path\to\file\bar.jpg
> 

### What problem did you have?
The command can be run successfully, but the results is not ideal. I would like to upload just the file like _foo.txt_ into azure container without creating all the folders/subdirectories like _servername1\path\to\file_ in azure storage.

**Comment by mohsha-msft** [comment]
@weiwei-liu 

Thanks for reaching out to us!
``--list-of-files`` flag defines the location of text file which has the list of only files to be copied from the source. So, it acts as a filter and we upload only the files specified in ``copyfile.txt``. But since you specified the relative path ``servername1\path\to\file\foo.txt`` instead of ``foo.txt``, it will create directories specified in the path as well as blob.

What you ask for is not exactly supported by AzCopy in one Job. For your ask to work, you need to go ahead and specify local file path as source and run AzCopy multiple times.

Please feel free to reach out for more clarification if this does not answer your question.

**Comment by meganshand** [comment]
Under the assumption that it would be faster to move a large number of files with one AzCopy job rather than running it multiple times, then this still seems like a very useful feature. Is there any other way to achieve this?
