### ISSUE TITLE
`sync` file<->file fails on blob containers

### ISSUE THREAD

**Issue by munael** [Azure/azure-storage-azcopy#1250]
### Which version of the AzCopy was used? 
10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019

### What command did you run?
```
azcopy sync "local-dir/file.txt" "remote-dir/file.txt"
```

### What problem was encountered?
Error:
```
Cannot perform sync due to error: sync must happen between source and destination of the same type, e.g. either file <-> file, or directory/container <-> directory/container
```

### How can we reproduce the problem in the simplest way?
1. Make file `local-dir/file.txt`
2. Run command with `remote-dir` pointing to an Azure blob container.

### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment]
Hi @munael thanks for reaching out!

The file <-> file scenario only works if the destination file already exists, since there is no concept of folders in the Blob Storage, and it'd be hard to tell whether the remote path is meant to be a folder (it requires a more expensive listing operation to check).
