### ISSUE TITLE
Wildcard patterns applied to full paths

### ISSUE THREAD

**Issue by gar1t** [Azure/azure-storage-azcopy#1281]
Version: 10.8.0
Platform: Linux
Command: sync

Wildcard patterns specified with `--include-pattern` appear to only apply to file base names. If I have this right, this is remarkably limited functionality. I would expect a sync or recursive copy command to support pattern matching that can control directories as well as files. E.g. `--include-pattern */subdir/*.txt` should IMO match any txt file in a subdirectory `subdir`. Perhaps this is possible though and I just need the right syntax?

**Comment by zezha-msft** [comment]
Hi @gar1t, thanks for reaching out!

We designed the flags this way with the intention to simplify the experience. The flag used to function the way you described it, but the implementation was flaky and it was hard to explain the behavior in documentation. For example, does `*/subdir/*.txt` include the following:

1.  bla/subdir/bla.txt
    1. This one is a pretty obvious yes. 
2. bla/bla/subdir/bla.txt
    1. My guess is no, since `*` is not supposed to pattern match to path separators like `/`. 
3. bla/subdir/bla/bla/bla/bla.txt
    1. Also no? Same logic as above?

In addition, we need to support the scenario where the cx wants to include a specific list of sub directories, e.g. `subdir1;subdir2`. So having a single pattern flag cannot accomplish that, since they need everything under subdir1 and subdir2, i.e. subdir1**;subdir2**, where the double * indicates that it can match to path separators. We ended up adding a separate set of include/exclude path flags to avoid the complexity. 

We are all ears if you have any proposal to improve the functionality, and yet keep the complexity in check so that it's easy to document/implement. Thanks!

**Comment by gar1t** [comment]
The change you outline does not help my case, nor many common cases. In particular, you need to match over multiple directories, not just one.

I recommend studying the schemes provided by these sync commands as they are accommodate a much wider range of cases:

- [AWS CLI sync](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#use-of-exclude-and-include-filters)
- [rsync](https://linux.die.net/man/1/rsync) (see Filter Rules just below the options list.

You might consider `--include-regex`, which supports a [regular expression](https://pubs.opengroup.org/onlinepubs/009696699/basedefs/xbd_chap09.html) that is applied to the full path, rather than path segments. This would preserve existing basic functionality and give users an outlet to handle more complex cases.

**Comment by zezha-msft** [comment]
Thanks a lot for the feedbacks @gar1t! We will look into your suggestion. Much appreciated.

**Comment by lmeyerov** [comment]
We were surprised, disappointed, & blocked as well. We'd love to see standard regex on full paths, as is common with most CLI tools.

**Comment by pablospe** [comment]
I guess this issue has already been solved using V10.12+ (with the `--exclude-regex` option), right?

https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.12.0
`Added support for include and exclude regex flags, which allow pattern matching on the entire paths.`
