### ISSUE TITLE
azcopy copy deletes files in the destination directory!

### ISSUE THREAD

**Issue by oneear** [Azure/azure-storage-azcopy#1417]
##### Note: The version is visible when running AzCopy without any argument
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2008 R2

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
c:\azure\azcopy copy "e:\copytest" "https://mystorage.file.core.windows.net/myfileshare?sv=2019-12-12&ss=b
fqt&srt=sco&sp=rwdlacupx&se=2025-12-09T06:15:43Z&st=2020-12-08T22:15:43Z&spr=https&sig=REDACTED" --recursive

### What problem was encountered?
The copy caused files in the destination azure file share to be deleted!

### How can we reproduce the problem in the simplest way?
1. put a few files in a directory (e:\copytest)
2. run the copy command above to copy the files to azure storage
3. verify the files copied in azure storage
4. run the copy command above, hitting Ctrl-C to cancel it after at least one file has copied and before it's finished
>> Look at azure storage and you'll see some of the files are now missing! It's consistently reproducible.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Thanks for reaching out, I see that there seems to be a misunderstanding.
 
When we write to the file service, we must call “create file” first, which zeros out the file; then we perform range updates to upload all the data. This is how the file service works and we don't have a choice here.
 
Canceling a job means that the in-flight files are in an incomplete state on the service side, thus they are removed if canceled.

Please turn on soft delete and keep backups until you’ve verified that the transfers succeeded. 

And in addition, if you are only interested in copying files that don't already exist on the destination side, you could set `overwrite=false` so that those existing files are skipped over and not copied again (more efficient and less risk).

Please let us know if you have any additional question.

**Comment by zezha-msft** [comment]
On a side note, block blobs do not have this problem, since we don't have to zero them out first; the blocks are first staged; then a "commit block list" call is issued to atomically overwrite the entire file in one shot. It's another option. 😃

**Comment by oneear** [comment]
I have never, ever heard of copy deleting files. There should be a huge warning, requiring confirmation and recommending turning on soft delete, before proceeding to delete files on the destination. It's unexpected and wrong for a copy to delete files without warning.

**Comment by oneear** [comment]
Under no circumstances should copy delete files in the destination. (And this destructive behavior is not documented and no warning is provided. https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy)

This is a bug and should not be blosed.

**Comment by zezha-msft** [comment]
Hi @oneear, I understand your frustration, but I think there is still a misunderstanding. Please allow me to clarify again.

When uploading to the file service, the destination file is first resized and zero'd out, then individual ranges are uploaded; if you stop the transfer in the middle, it means that the destination file is in a corrupt state, as it contains only part of the new data. In other words, as soon as transferring starts, the original data is gone, so in the case of a canceled transfer, the half-transferred corrupt file is removed. 

Imagine if you triggered a transfer but did not notice that the job failed (let's say network had a problem). Would you want corrupt files to be kept on the service side? They'll not be usable, and may give the impression that they were uploaded successfully. The safer option is to simply remove the corrupt file. Keeping backups (until transfers are verified to be successful) and turning on soft-delete are both great steps to keep your data safe.

As I mentioned already, this is how the file service works. If this is not what you are expecting, I suggest to take a look at the blob service instead, which behaves much more like what you expected. For example, a failed block blob transfer would not delete the original blob, because the write ("commit block list") is atomic, and we don't have to zero out the blob first. 

Please let us know if you have any other question.

**Comment by oneear** [comment]
Hi zesha, thank you for your explanation; however, it is a bug for copy to delete files -- even those that haven't been attempted to be copied yet. Have you ever seen a copy command delete *all* of the files in the destination, whether it succeeded or not? I have never seen this behavior. At a minimum there should be a huge warning, requiring confirmation, before deleting destination files.

Can you imagine my surprise when I canceled the copy, only later to realize *all* my files were deleted? Not expecting it, I didn't realize it until my soft delete files were gone also. I relied on Azure. Azure failed me terribly. There was no warning and nothing in the documentation. This is a terrible bug and should be addressed. 

You indicate there is no other way; there is always a better way. (This no-fix, deal-with-it attitude is why there is so little confidence in MS software, and why computers blue-screen during Gates' presentation.) Of course we don't want corrupted files either. Why not copy the files to a staging area before deleting them; then if the copy is canceled they can be restored?

If this behavior is not changed, I suggest "copy" be renamed to "delete-all-then-copy" or the like. At a minimum, a warning should be displayed that all destination files will first be deleted, and this destructive behavior should be in the documentation.

**Comment by zezha-msft** [comment]
> however, it is a bug for copy to delete files -- even those that haven't been attempted to be copied yet. 

This is not correct. As I've clarified already, only in-flight half-copied files are removed. The successful or not-yet-started files are left alone. If the job consists of only a couple of files, they are all started simultaneously. 

> Can you imagine my surprise when I canceled the copy, only later to realize all my files were deleted? Not expecting it, I didn't realize it until my soft delete files were gone also. I relied on Azure. Azure failed me terribly. There was no warning and nothing in the documentation. This is a terrible bug and should be addressed.

I empathize with how you are feel. I'll look into improving our documentation for new users of Azure Files. Please turn on soft delete and verify that transfers have succeeded before deleting the backups. 

> You indicate there is no other way; there is always a better way. Of course we don't want corrupted files either. Why not copy the files to a staging area before deleting them; then if the copy is canceled they can be restored?

Sorry, could you please clarify? Do you mean copying the files that are about to be overwritten to another location on the Azure Files side first?
