### ISSUE TITLE
Local-To-ADLS with SAS fails, works with StorageExplorer OAuth

### ISSUE THREAD

**Issue by kfallstrom** [Azure/azure-storage-azcopy#143]
##### Note: The version is visible when running AzCopy without any argument
10.0.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
C:\Users\Administrator\Downloads\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4>azcopy.exe cp "https://%destinationdfs%.dfs.core.windows.net/%containername%?%SAS%" --recursive=true --follow-symlinks --fromTo=LocalBlobFS --list-of-files=files.json

--files.json contents:
{"files":["%ADLS FOLDER NAME%"]}
### What problem was encountered?
failed to perform copy command due to error: OAuth token or shared key should be provided for Blob FS
### How can we reproduce the problem in the simplest way?
attempt Local to ADLS copy using SAS
### Have you found a mitigation/solution?
No

**Comment by kfallstrom** [comment]
attempted to re-run StorageExplorer exported task with SAS instead of OAuth (via StorageExplorer)

copy "C:\Users\Administrator\Shared Folders\*" "https://%destinationdfs%.dfs.core.windows.net/sharefile/" --overwrite=false --follow-symlinks --recursive --fromTo=LocalBlobFS --list-of-files "C:\Users\ADMINI~1\AppData\Local\Temp\2\stg-exp-azcopy-5f56aa5d-150a-4db2-9d0b-0a2cf55a8ed7.json"

**Comment by zezha-msft** [comment]
Hi @kfallstrom, thanks for reaching out. 

The ADLS Gen2 service currently does NOT support SAS. If you need to leverage AzCopy for scripting purposes, please consider using Shared Key instead by specifying two environment variables (hidden from documentation)`ACCOUNT_NAME` and `ACCOUNT_KEY`.

Would this solve your issue?

On a side note, we are still debating whether Shared Key should be supported, so that's why these environment variables are undocumented.

**Comment by kfallstrom** [comment]
Yes, thanks @zezha-msft
