### ISSUE TITLE
Sync command is a misnomer?

### ISSUE THREAD

**Issue by CheeseBreadIsGood** [Azure/azure-storage-azcopy#1434]
Should the "Sync" command be renamed to "Mirror" command? This more reflects (no pun intended) how it only goes one way.

I had to create two separate "Sync" commands to make sure they truly sync both ways. One going to the blob (local->blob and one coming from the blob -> local.

 azcopy.exe sync "L:\DATA\SharedData" "***https://SAS URL BLOB****"  --delete-destination=FALSE
 azcopy.exe sync "***https://SAS URL BLOB***" "L:\DATA\SharedData"  --delete-destination=FALSE

I had to do it this way because I had another system that was modifying the blob files directly. I just think it should be called "Mirror" command. A true "sync" command would only take one line and would sync both sides at the same time. I should not have to create a two-way "Mirror".

**Comment by TomAdams9** [comment]
Unfortunately it's not a sync or a mirror, because it can't handle files changed made at the target.
AZCopy behaviour is very limited - The most recent file always wins and there is no way to over-rule it.

A "mirror" would always over-write of the target, regardless of anything.

**Comment by zezha-msft** [comment]
Hi @CheeseBreadIsGood @TomAdams9, thanks for the feedbacks!

We've added a mirror mode to the sync command in 10.11, change log is [here](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.11.0). Basically it allows the user to perform a brute sync and complete overwrite the destination.

@CheeseBreadIsGood sorry for the inconvenience, but the sync command was designed as a one-way sync, because the blob service does not allow users to set the last modified time of the blobs. Thus, the most we can do is a one-way sync, since as soon as you transfer anything to the blob side, it'll look newer than the file that you had at the source. 

I'm not sure that your two commands are actually doing what you intended. The second sync would bring back the files that you just uploaded with the first sync.
