### ISSUE TITLE
--put-md5 option - Any plans to accept additional checksum types such as sha512

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [Azure/azure-storage-azcopy#1581]
Hi,

We are wondering if there are any plans to implement `--put-md5` equivalent options for other checksum types such as `sha512`.

### Which version of the AzCopy was used? 
10.12.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
--put-md5

**Comment by zezha-msft** [comment]
Hi @tyamaguchi-ucla thanks for reaching out!

Could you please clarify your scenario a bit? Is --put-md5 not satisfying your needs? If not, what are you expecting from other checksum types?

**Comment by zezha-msft** [comment]
@tyamaguchi-ucla to clarify, --put-md5 only takes effect when you are uploading from local drive, and AzCopy is reading the source data and computing an overall MD5 for the file. This value is stored on the service (and not validated) for the downloader to eventually verify on their own. 

--put-md5 is setting the `x-ms-blob-content-md5` header. Refer to REST API doc here: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

I'm not sure that this is actually relevant for your scenario, since you are transferring files from service to service.

**Comment by tyamaguchi-ucla** [comment]
@zezha-msft We've done some testing and transfers from Avere Cache (hot tier) to a blob container (archive tier) worked fine.

>--put-md5 is setting the x-ms-blob-content-md5 header. Refer to REST API doc here: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

Yes, so we are wondering if it would be possible to have the same functionality for sha512.

**Comment by zezha-msft** [comment]
@tyamaguchi-ucla thanks for the update.

To clarify, MD5 is a dedicated field that the service can store (but does not verify) for you, and --put-md5 is simply computing and putting the value there. 

> x-ms-blob-content-md5 | Optional. An MD5 hash of the blob content. This hash is not validated, as the hashes for the individual blocks were validated when each was uploaded.The Get Blob operation returns the value of this header in the Content-MD5 response header.If this property is not specified with the request, then it is cleared for the blob if the request is successful.

Then at download time, AzCopy can verify with --check-md5.

If you'd like to store the SHA512, I'd suggest doing it using a metadata field and compute it outside of AzCopy. Since there is no standard header to store SHA512 on the service side, I don't believe AzCopy should compute/store SHA512 unless it's officially supported by the service in some fashion.

We are exploring the possibility of supporting CRC64 (which the service supports already) that is using a custom polynomial. Please let us know if you have any thoughts or feedbacks on that front. Thanks!
