### ISSUE TITLE
AZCopy with error message

### ISSUE THREAD

**Issue by apolloxm** [Azure/azure-storage-azcopy#1626]
### Which version of the AzCopy was used? 
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
./azcopy sync "https://XXXX.blob.core.windows.net/testingupload?   --recursive    --delete-destination=true  --exclude-path '#snapshot'  --include-pattern="*.vbk"

### What problem was encountered?
We  run the AZCopy completed with errors
In the AZCopy logs, we can see there are lot of error messages said that  http request error or TLS handshake timeout. In the Firewall, We also can found the “ tcp-rst-from-server” or “tcp-rst-from-client”  

Error Message:

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=1/13.6480238s[SLOW >3s], OpTime=13.6480238s) -- REQUEST ERROR
   PUT https://xxxxxx.blob.core.windows.net/xxxxxxx.vbk?blockid=owmxmzfkmtytmtc4os1mntqwltcyowitm2mymgvlotuznzcx&comp=block&se=2022-09-29t11%3A27%3A26z&sig=-REDACTED-&sp=racwdli&spr=https&sr=c&st=2021-09-29t03%3A27%3A26z&sv=2020-08-04&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.13 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [685899a8-879d-4b2e-7dac-ac23117897d5]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put "https://xxxxxx.blob.core.windows.net/xxxxxxxxxx.vbk?blockid=OWMxMzFkMTYtMTc4OS1mNTQwLTcyOWItM2MyMGVlOTUzNzcx&comp=block&se=2022-09-29T11%3A27%3A26Z&sig=-REDACTED-&sp=racwdli&spr=https&sr=c&st=2021-09-29T03%3A27%3A26Z&sv=2020-08-04&timeout=901": net/http: TLS handshake timeout

We don't know why this happen, We didn't do any change and it was run with successfully for a long time, only this time got error. We need to do the RCA for this. Can you help on this? We have checked the resource healthy from Azure Portal, there is no error

**Comment by mohsha-msft** [comment]
HI @apolloxm ,

Thanks for reaching out!
This is most likely due to slow network bandwidth/flaky network. The amount of packets Azure Storage was expecting couldn't be delivered in the allotted time. Hence, the timeout. 

However, we retry every failed request 20 times and have exponential back-off policy enabled. So, a failed request  will be retried multiple times before finally can be marked as failed.

I can investigate more if you can provide us with AzCopy log file but this most likely is a network issue.
Please reopen the issue if you have more comments on the same or the above explanation doesn't answer your question.

**Comment by apolloxm** [comment]
Hi @mohsha-msft，
Thanks for your reply! Can you tell me how can I upload the log file to you?I didn't see any upload option in the git hub. Thanks!
