### ISSUE TITLE
Azcopy sync File Creation Error cannot simultaneously send two files

### ISSUE THREAD

**Issue by prohand** [Azure/azure-storage-azcopy#1647]
### Which version of the AzCopy was used? 
V10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?

```
$BackupShareNas =  "Y:\BKPAZURE\BLOBS\"
$copysource = "https://xxxxx.blob.core.windows.net"
$clessassource = "xxxxx"

$containerToBackup = @('test','test2')
foreach($container in $containerToBackup)
{
    $source = -join($copysource,'/',$container,$clessassource)
    $destination = -join($BackupShareNas,'\',$container)
    .\AzCopy.exe sync  $source $destination --delete-destination=true --log-level ERROR
}
```

### What problem was encountered?

Error : File Creation Error cannot simultaneously send two files to same destination name

### Have you found a mitigation/solution?

No

Thank you for you're help

**Comment by adreed-msft** [comment]
Do you have any files with names that can't be encoded on a NTFS filesystem? (e.g. with characters like <, >, \\, /, :, ", |, ?, or *)? Names that are duplicates in all but capitalization (e.g. `Foo.txt` and `foo.txt`)? I'm trying to probe for potential overlaps in filenames.

**Comment by prohand** [comment]
Hello,

Here is an example of a failed file

`CommandeFournisseur_v2.0.2.mrt`

Thank you

**Comment by prohand** [comment]
Hello,

Do you have a solution ?

Thank you

**Comment by prohand** [comment]
Hello,

any news ?

Thank you

**Comment by nakulkar-msft** [comment]
Hi @prohand , can you mail the log file? I secrets in the file are redacted and it is safe to do so. Email ID on my profile.
Thanks.

**Comment by prohand** [comment]
Hello,

I have send the log via email.

Thank you

**Comment by nakulkar-msft** [comment]
Hi @prohand, I inspected the log file and like @adreed-msft you've files with similar names but differing in capitalization. Windows is case-insensitive, and such files will be downloaded to same destination file. If you've such blobs copy them back to same container with a different name, and retry the sync operation.

**Comment by prohand** [comment]
Hello the problem is not solved.
The solution of use azcopy copy <source> <destination> --overwrite=false is not ok but my azcopy use sync and the flag --overwrite not exist with sync option.

In addition, the sync has the --mirror-mode value set to false which should not be a problem because the file is not redownloaded

Thank you

**Comment by zezha-msft** [comment]
Hi @prohand, to illustrate the explanation that @nakulkar-msft provided, consider the following example:

Lets say that you have these 2 blobs:
    container/foo.txt
    container/Foo.txt

As you can see, these two blobs, foo.txt and Foo.txt differ in casing only. While they happily exist side by side on the blob service, they cannot possibly co-exist on Windows, which provide file access APIs in a case insensitive way.

In other words, both foo.txt and Foo.txt would map to the same file on Windows while they are being downloaded. Therefore, AzCopy must fail the copy as there is no sane behavior, do you want:

1. The contents of foo.txt and Foo.txt to be mixed together?
2. The contents of foo.txt alone is downloaded?
3. The contents of Foo.txt alone is downloaded?

Hopefully this explanation makes sense.

To work around this problem, please rename your blobs so that their names differ in more than the casing. In this case, consider renaming foo.txt to bar.txt.

**Comment by prohand** [comment]
Hello,

Thanks for your feedback.
I understood the problem and I will see with our teams why there are 2 files that do not have the same name but the same content;).

Thank you
