### ISSUE TITLE
AzCopy move feature instead of copy and remove 

### ISSUE THREAD

**Issue by Ravi-Kashyap** [Azure/azure-storage-azcopy#1650]
We are looking for move flag for AzCopy so it's easier to move files rather than copying and removing in 2 different steps. 

I found a reference but that issue was closed (https://github.com/MicrosoftDocs/azure-docs/issues/29554) and I don't see any option to re-open it. 

I know there is a remove flag (doc link below) but we are looking for delete after copy or move as a single step rather than 2 step process. 

https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy?toc=/azure/storage/blobs/toc.json

**Comment by adreed-msft** [comment]
This has been discussed in the past at length and historically we'd decided not to support these asks, as we didn't want to be in the business of deleting user data (outside of the `rm` function).

That said, I'll pass this request around again and see what folks think.

**Comment by zezha-msft** [comment]
Hi @Ravi-Kashyap, thanks for reaching out. Sorry to disappoint you but our decision remained the same after the discussion. The main reason is still what @adreed-msft  mentioned earlier: `we didn't want to be in the business of deleting user data (outside of the rm function)`.

**Comment by SlkRck** [comment]
"not being in the business of deleting user data..."  that is B.S.  EVERY operation that is a move does that -- all you need to do is CONFIRM the copy and then your're in business.

I wrote a script that does it.  Why not integrate it into a MOVE operation?
https://stackoverflow.com/a/72419241/13120207

**Comment by zezha-msft** [comment]
Sorry @SlkRck, the decision is firm unfortunately.

**Comment by LeeBear35** [comment]
This is really a poor reason, while I like SlkRck's solution, it does not work in our business case because we drop files into a container for processing, and the processing step removes those files from the container. So **sync** is not an option because the files are removed. 
The rest of the business case is the fact that we are talking about moving millions of files, and as invariably happens a copy might fail somewhere along the way, but restarting means that the same file previously dropped gets dropped a second time. 

Considering that azcopy has a remove option is really a short sided design failure, and a reason to seek out a better solution elsewhere. Maybe is it just an upsell to get people to use Data Factory, which is sad to me, but expected anymore.

**Comment by adreed-msft** [comment]
> Maybe is it just an upsell to get people to use Data Factory, which is sad to me, but expected anymore.

I assure you that's not the case. I agree that it's something we should support, but you know how that is. I'll try to push the issue again during the next sync up.

**Comment by LeeBear35** [comment]
> > Maybe is it just an upsell to get people to use Data Factory, which is sad to me, but expected anymore.
> 
> I assure you that's not the case. I agree that it's something we should support, but you know how that is. I'll try to push the issue again during the next sync up.

Thank you for the consideration, I did find that the rclone application provides the needed feature and works well with Azure and non-Azure storage, in case anyone else needs the same solution.

**Comment by mcobzarenco** [comment]
This discussion focuses on failure modes. An additional reason to support moving a blob is that it does not require any actual copying of data, only updating the metadata of the blob with the new path. This is a **_much cheaper and faster operation_** -- should be instant and pretty much free. 

Our use case is to refactor how a large amount of data is organized

**Comment by PolItKy** [comment]
> This discussion focuses on failure modes. An additional reason to support moving a blob is that it does not require any actual copying of data, only updating the metadata of the blob with the new path. This is a **_much cheaper and faster operation_** -- should be instant and pretty much free.
> 
> Our use case is to refactor how a large amount of data is organized

I think you just made MSFT's reasoning for NOT supporting this: it's cheaper.  They need those moves to cost more so they can make more money., which in some cases is fair  It's a sound business practice, but an unsound technical practice. 

But your argument actually completely counters the idea of "we don't want to be in the business of deleting user data." First, of course they're in that business, or they wouldn't be able to support data at all, so that's nonsense. But second, you are actually making the correct argument that this isn't even a "delete" but an update to the metadata, especially in regards to ADLS Gen 2 Storage Accounts, as that's the whole point... operations only update the metadata.  That's the entire benefit of ADLS Gen 2.  But unfortunately due to poor support, we are forced to interact with it using this archaic Az Copy, which is not at all user friendly, especially in environments where Storage Explorer is not an option.
