### ISSUE TITLE
Feature | Server side copy support ADLS and ADLSv2

### ISSUE THREAD

**Issue by msdz** [Azure/azure-storage-azcopy#169]
### What problem was encountered?

There will be some data trends. For example, importing from ADLS to ADLSv2, ADLS importing Storage, ADLSv2 importing to Storage, and ADLSv2 importing to ADLSv2. 

Is there a server-side replication to do this now? 
Can I only use the ADF pipeline at this time? The average will have terabytes of data, which will cause a Throttling error in the sink storage.

### How can we reproduce the problem in the simplest way?
Copy a large file such as 1TB from ADLSv2 to ADLSv2 on ADF.

### Have you found a mitigation/solution?
Server side copy will ease, but there is no public way to do it.

**Comment by zezha-msft** [comment]
Hi @mscss, thanks for reaching out!

We are aware of these data transferring scenarios, but we are still waiting on the necessary service-end changes to implement them in AzCopy.

My colleague @jiacfan will get back to you with more info once they are available.

**Comment by JasonYeMSFT** [comment]
Is there any update on this feature?

**Comment by zezha-msft** [comment]
Hi @JasonYeMSFT, sorry we haven't heard anything yet. We'll update this thread if we get any news.

**Comment by JohnRusk** [comment]
For ADLS Gen 2, this is covered by the recent GA of [Multi Protocol Access.](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access)  Just use the account's blob url endpoint (instead of its ADLS Gen 2 one) and its should work.

For ADLS Gen 1, that's outside the current scope of AzCopy.

So I propose to close this issue now.  Please let us know if it may need to be reopened.
