### ISSUE TITLE
Issue copying a directory from one storage account to another 

### ISSUE THREAD

**Issue by walshphilip86** [Azure/azure-storage-azcopy#1738]
### Which version of the AzCopy was used? 
`azcopy version 10.14.1`

### Which platform are you using? (ex: Windows, Mac, Linux)
`Linux (ubuntu 20.04)`

### What command did you run?
```
az storage container generate-sas -n mycontainer --account-name myaccount --auth-mode login --as-user --expiry <DATE>
azcopy copy 'https://myaccount.blob.core.windows.net/mycontainer/db?<SAS TOKEN from above>' 'https://mydestaccount.blob.core.windows.net/mycontainer' --recursive
INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210914164749-2d6cd3e07548/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)
   HEAD https://myaccount.blob.core.windows.net/mycontainer/db?<SAS TOKEN>
   User-Agent: [AzCopy/10.14.1 Azure-Storage/0.14 (go1.16.14; linux)]
   X-Ms-Client-Request-Id: [37afd4cb-c3da-4ddf-5274-76dc37a199bd]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Tue, 05 Apr 2022 10:56:29 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [16ee79a3-901e-0029-47db-480326000000]
```

### What problem was encountered?
I am trying to copy a directory of the form `https://myaccount.blob.core.windows.net/mycontainer/dir1/dir2/dir3/files` to a destination storage account which is currently empty. 

Also, can it be confirmed if Azure (azcopy) supports the copying/moving/syncing of files between different containers in the same storage account? 
Thanks

**Comment by walshphilip86** [comment]
I was missing the permissions parameter `--permissions lrwac` - working for me now. 

Is it possible to copy/move between different containers in the same storage account?

**Comment by nakulkar-msft** [comment]
Hi @walshphilip86, you can move between different containers in the same storage account. Closing this issue. Let us know if you need more information.

**Comment by walshphilip86** [comment]
Hi @nakulkar-msft, 

Can you provide an example of how you would move between different containers in the same storage account please?
From the docs here it doesnt suggest this is possible - https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy#copy-a-directory

`azcopy copy 'https://<source-storage-account-name>.blob.core.windows.net/<container-name>/<blob-path><SAS-token>' 'https://<destination-storage-account-name>.blob.core.windows.net/<container-name>/<blob-path>'`

Src storage account to dest storage account. 

Is the below possible? It has not worked for me. 

`azcopy copy 'https://<storage-account-1>.blob.core.windows.net/<container-name>/<blob-path><SAS-token>' 'https://<storage-account-1>.blob.core.windows.net/<container-name>/<blob-path>'`

Thanks

**Comment by nakulkar-msft** [comment]
@walshphilip86 You can copy between different containers in the same storage account. i.e.
`azcopy copy 'https://<sa1>.blob.core.windows.net/container1/<blob path><SAS>` 'https://sa1.blob.core.windows.net/container2/<blob Path>`

You can also copy blob to the same container, but different path. i.e.
`azcopy copy 'https://<sa1>.blob.core.windows.net/container1/<blob path><SAS>` 'https://sa1.blob.core.windows.net/container1/<blob Path2>`

The command you've posted essentially tries copying a blob to itself and is not allowed.

**Comment by mohiabu** [comment]
@nakulkar-msft I'm hitting similar error in one of our storage account which enabled with hierarchical namespace. 
Here I'm using SAS token generated using storage account key for azcopy both source and target.

Appreciated your input to mitigate this error.

100.0 %, 10000 Done, 0 Failed, 0 Pending, 0 Skipped, 10000 Total (scanning...), 
100.0 %, 10000 Done, 0 Failed, 0 Pending, 0 Skipped, 10000 Total (scanning...), 
failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go
/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210914164749-2d6cd3e07548/azblob/zc_storage_error.
go:42
===== RESPONSE ERROR (ServiceCode=InternalError) =====
Description=Server encountered an internal error. Please try again after some time.
RequestId:12f5114d-301e-0089-2f84-59a497000000
Time:2022-04-26T15:45:14.8364291Z, Details: 
   Code: InternalError
   GET https://sourceblob.blob.core.windows.net/mycontainer?comp=list&delimiter=%2F&include=metadata&prefix=fact%2Fft_online_stores_sales_consol%2Fsrc_i
d%3Dreceipt_row%2F&restype=container&se=2022-04-27t18%3A57%3A36z&sig=-REDACTED-&sp=rl&spr=https&srt=sco&ss=b&st=2022-04-25t10%3A57%3A36z&sv=2020-08-0
4&timeout=901
   User-Agent: [AzCopy/10.14.1 Azure-Storage/0.14 (go1.16.14; Windows_NT)]
   X-Ms-Client-Request-Id: [03f3fd16-e0b2-4c69-7b24-cd834a167967]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 500 Server encountered an internal error. Please try again after some time.
   Content-Length: [253]
   Content-Type: [application/xml]
   Date: [Tue, 26 Apr 2022 15:45:14 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [03f3fd16-e0b2-4c69-7b24-cd834a167967]
   X-Ms-Error-Code: [InternalError]
   X-Ms-Request-Id: [12f5114d-301e-0089-2f84-59a497000000]
   X-Ms-Version: [2020-04-08]
