### ISSUE TITLE
Cannot list objects error

### ISSUE THREAD

**Issue by odis43** [Azure/azure-storage-azcopy#1841]
##### Note: The version is visible when running AzCopy without any argument
10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
.\azcopy  copy 'https://s3-ca-central-1.amazonaws.com/devo-log-storage' 'https://ulsnapreprod.blob.core.windows.net/azcopy-test' --recursive=true

### What problem was encountered?
Cannot list objects, Access Denied (this was the error)
### How can we reproduce the problem in the simplest way?
Reproducing the problem may not be possible as the copy is done for a company that I do not own.  I'm hoping the solution is due to semantics or something I may not have done correctly.
### Have you found a mitigation/solution?
No I have not.

**Comment by games** [comment]
I am facing same problem, any update on this?

**Comment by romilynxt** [comment]
Facing the same issue. any update on this?

**Comment by nakulkar-msft** [comment]
Closing due to age. Please open a new  issue if you're seeing this.

**Comment by NRL-LEastham** [comment]
Wow, so nobody from MS responded other that to close it due to age.

The problem appears to be due to AzCopy trying to enumerate the S3 bucket, however the permissions aren't sufficient.  Unfotunately this also happens when you only want a specific object. Our supplier can't grant enumerate permissions due to data sensitivity so we can't use AzCopy until the code is updated to not force --recursive=true on S3 sources.
