### ISSUE TITLE
azcopy copy command to allow passing --account-name and --account-key options for source storage account.

### ISSUE THREAD

**Issue by mgiannakopoulos** [Azure/azure-storage-azcopy#1867]
##### Note: The version is visible when running AzCopy without any argument

AzCopy 10.16.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Debian GNU/Linux 11 (bullseye)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
azcopy copy 'https://s2mscompanybucket.blob.core.windows.net/s2mscompanybucket' 'https://s2mspersonalbucket.blob.core.windows.net/s2mspersonalbucket?[SAS TOKEN]' --recursive --account-name <source storage account name> --account-key <source storage account key>
```
### What problem was encountered?
Passing the `account-name` and the `account-key` for source destination is not supported. However, with `az storage blob copy` the equivalent parameters are available.
### Have you found a mitigation/solution?
No, I don't want to produce a SAS token for the source container.

**Comment by zezha-msft** [comment]
Hi @mgiannakopoulos, thanks for reaching out and providing this feedback.

Unfortunately, this was a conscious decision by our security team, as account keys are way too powerful and they give super user permission to the entire account. SAS are safer since they are scoped in terms of permission and short-lived.

If you don't like SAS, please consider using AAD. More info here: https://docs.microsoft.com/en-us/azure/storage/blobs/authorize-access-azure-active-directory
