### ISSUE TITLE
preserve-last-modified-time is not supported while uploading

### ISSUE THREAD

**Issue by karthikeyanr** [Azure/azure-storage-azcopy#1982]
##### Note: The version is visible when running AzCopy without any argument
10.16.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy linux_server_folder Azure_storage_file_share?SAStoken --recursive --follow-symlinks --preserve-last-modified-time

### What problem was encountered?
failed to parse user input due to error: preserve-last-modified-time is not supported while uploading

### How can we reproduce the problem in the simplest way?
copy folders or files from Linux to Azure Storage

### Have you found a mitigation/solution?
No. Based on issue #1750 , This was targeted for 10.16.0 but still not working on 10.16.2. Need to know when this will be available.

**Comment by gapra-msft** [comment]
Hi @karthikeyanr I believe the earlier response to #1750 only specified that we would be supporting ACL preservation. 

The last modified time is not settable in any of the Azure Storage Services, so we are unable to implement this feature. 

Closing this issue since it is a limitation by the service.
