### ISSUE TITLE
Reuse AD-login from az cli or Az.Accounts PowerShell module

### ISSUE THREAD

**Issue by elygre** [Azure/azure-storage-azcopy#2039]
To the best of my knowledge, azcopy always requries a separate login (for example using `az login --tenant-id xxx`).

It would be super useful if the tool could hook into a current session under the Azure CLI or PowerShell modules. An example of this is found in the Azure Functions Core Tools (https://github.com/Azure/azure-functions-core-tools/), which does this. Here is what it looks like when you are not logged in:

```
> func azure functionapp publish FUNCNAME --build remote --python
Unable to connect to Azure. Make sure you have the `az` CLI or `Az.Accounts` PowerShell module installed and logged in and try again
```

The mechanism could be surfaced in many different ways:

* It could be added to `azcopy login`, as in `azcopy login --reuse-cli-connection` or similar
* It could be an option to each invocation: `azcopy --login-cli sync ...`
* It could be automatic, if there is no azcopy login, reuse what's in the environment (though this would perhaps be a breaking change)

Apart from the magnificent convenience for interactive use, it would also help in for example Azure DevOps pipelines. Azure DevOps automatically configures authentication for the `az`  cli, without exposing any secrets to the pipeline environment. In order to run `azcopy`, we have found that we needed to enable the `addSpnToEnvironment`, which puts the required settings into environment variables that we then use with `azcopy login --service-principal`. All of that would be superfluent if azcopy had a simple way of reusing the existing cli login.

**Comment by aolszowka** [comment]
Coming in here to ask for the same thing; but rather than just giving a simple +1 if you are trying to do this in an Azure DevOps Pipeline, here's what you'd have to do today to get this to work:

Your DevOps Pipeline YAML:
```yml
- task: AzureCLI@2
  displayName: 'Copy Storage Account Data'
  inputs:
    azureSubscription: 'YOUR-SPN-HERE'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'AzCopyScript.ps1'
    addSpnToEnvironment: true
```

As per the documentation of AzureCLI@2 (https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines) using `addSpnToEnvironment` will populate several environment variables: `servicePrincipalId`, `servicePrincipalKey` and `tenantId` we're going to use these in the underlying PowerShell Script next.

AzCopyScript.ps1 (cutting out all the logic to grab AzCopy assumes $AzCopy points to the binary):
```powershell
$env:AZCOPY_SPA_CLIENT_SECRET = $env:servicePrincipalKey
& $AzCopy login --service-principal --application-id $env:servicePrincipalId --tenant-id $env:tenantId
& $AzCopy login status
```

Will work, but as mentioned in the initial report isn't super clean, especially as you are passing secrets. Azure DevOps Pipelines does a pretty good job with censoring it from the logs but be careful.

Perhaps a shorter term ask is to have `azcopy` be smart enough to understand that `servicePrincipalId`, `servicePrincipalKey` and `tenantId` are also valid aliases for the `AZ_COPY_` versions?

**Comment by gapra-msft** [comment]
Hi @elygre 

We recently added support for az cli and powershell based login, which should satisfy the feature request. [Here ](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-with-azure-cli)are some docs you can reference for the same.

**Comment by gapra-msft** [comment]
Please do reopen the issue in case I have misunderstood/closed in error.

**Comment by aolszowka** [comment]
Just looping back here to indicate that this works and to provide an example:

Your DevOps Pipeline YAML:

```yml
- task: AzurePowerShell@5
  displayName: 'Copy Storage Account Data'
  inputs:
    azureSubscription: 'YOUR-SPN-HERE'
    TargetAzurePs: 'LatestVersion'
    ScriptType: 'FilePath'
    ScriptPath: 'AzCopyScript.ps1'
```

Note that I'm switching over to AzurePowerShell here because they've added support for taking the PowerShell Credentials and avoiding having to use AzureCli

AzCopyScript.ps1 (cutting out all the logic to grab AzCopy assumes $AzCopy points to the binary):

```powershell
# See: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-with-azure-powershell
$Env:AZCOPY_AUTO_LOGIN_TYPE="PSCRED"
```

Note that in this version of the script you need to drop any reference to `AzCopy login` INCLUDING `azcopy login status` which was used in the previous version. Failure to do so will result in this task failing.

This appears to work for us, thank you for the fix!
