### ISSUE TITLE
Slow performance - transferring 6M files at a total size of 6GB takes 32 hours to complete

### ISSUE THREAD

**Issue by AvivAvital2** [Azure/azure-storage-azcopy#2088]
### What command did you run?
```
export AZCOPY_CONCURRENCY_VALUE=AUTO;
export AZCOPY_BUFFER_GB=10;
export AZCOPY_CONCURRENT_FILES=100000;
azcopy copy "/path/to/local/dir" ""https://filesharename.file.core.windows.net/nameofshare/dirname?"" --overwrite=prompt --from-to=LocalBlob --blob-type Detect --follow-symlinks --check-length=false --follow-symlinks --disable-auto-decoding=false --recursive --log-level=INFO;
```
### What problem was encountered?
It took me **32 hours** uploading 6M files at a total size of roughly 6GB from local storage to a storage account.

Azcopy (10.17.0) output:
```
Elapsed Time (Minutes): 1961.4945
Number of File Transfers: 6274852
Number of Folder Property Transfers: 0
Total Number of Transfers: 6274852
Number of File Transfers Completed: 6239449
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 35403
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 6365454007
Final Job Status: CompletedWithSkipped
```

### How can we reproduce the problem in the simplest way?
Geneate a 20 row dataset using [Mockaroo](https://mockaroo.com/). Then make 6M copies of that file and upload to a storage account.

### Have you found a mitigation/solution?
No. I have tried using both azcopy and the Azure Storage Explorer with little luck.
Tried tweaking `AZCOPY_CONCURRENT_FILES`, `AZCOPY_BUFFER_GB` and `AZCOPY_CONCURRENCY_VALUE`, used different storage accounts on different regions, multiple machines, upgraded Azcopy to the latest version, removing/adding handles or changing values, nothing helped.
In addition, if the process would would be interrupted for some reason (e.g. I had a power outage once) skipping existing files the next time would take the same amount of time as uploading them in the first place.
In case we want to eliminate this is a connection issue, see speedtest results [here](https://www.speedtest.net/result/c/41956add-ae2e-4446-bc92-5991fd68439f)

Please assist, thanks :)

**Comment by nakulkar-msft** [comment]
Hi @AvivAvital2,
This is a limitation of AzCopy. We are making changes to improve this, however this would require changes on the Azure service as well.

WIth small files, the overhead of listing, creating and bookkeeping shadows the time taken for actual transfers, which is why you would see low throughput.

We do have recommendations here though. 
1. Use 8-16 core machine. Set AZCOPY_CONCURRENCY_VALUE to 512. and AZCOPY_CONCURRENT_FILES to 128. With small files, the throughput does not linearly scale, and higher values would be adverse.
2. With overwrite=prompt, we would have to make addtional call to know the existence of file on the destination. Check if you can skip this by setting overwrite=true. Likewise, blobtype as well. We try to make absolutely minimal n/w calls. When dealing with small files, these add up than actual data transfer
3. Finally set the log level to error.

We are making improvements continually to improve transfer speeds for this scenario. I would be closing this issue now. Please refer [here](https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-small-blobs) for more settings.
