### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by IsaakGroepT** [Azure/azure-storage-azcopy#214]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.0.7-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy cp [source] [destination?SAS] --recursive=true`

### What problem was encountered?
When transferring a large sum of files, azcopy absorbs as much as 6GB+ of RAM
![screenshot_20190215_221049](https://user-images.githubusercontent.com/14614620/52899149-ebcf9600-31e6-11e9-8f40-4592cd3a45bf.png)

### How can we reproduce the problem in the simplest way?
Start a cp transfer of +100GB of files, I'm not sure if it's required to upload at least this much data, but I noticed it happening during such a job.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @IsaakGroepT, thanks for reaching out!

AzCopy does consume quite a bit of memory to buffer file contents and upload them in parallel. But the memory usage is capped and shouldn't grow continuously. The maximum amount of memory we allow depends on how powerful your machine is. Do you mind sharing on what kind of machine are you running? How many physical cores?

**Comment by IsaakGroepT** [comment]
Now I noticed the RAM usage is quite static, the max was 7GB. My machine is a six core Ryzen 1600 with 16GB RAM

**Comment by JohnRusk** [comment]
Hi @IsaakGroepT 

We recently did a bug fix which will be released in the next release after 1.0.0.7.  It will almost halve the RAM usage.

The current behaviour, of being static at some capped figure, will remain. But the cap will be lower, at about 0.6 GB per core.  So in your case that would correspond to a static cap of about 3.5 Gbps (maybe closer to 4 due to a few overheads).  That's still a fair bit of RAM, but as Ze pointed out, the memory allocation is proportional to the number of cores.  So if you only had 2 cores, the new version would allocate only about 1.5 GB.

Finally, on very powerfull machines, e.g. with 32 cores, we never use over 8GB.

So there's no actual leak. Just a particular policy for how many buffers we allocate.

Does all of the above sound OK to you?  If so, I propose to close this issue.  Thanks heaps for reporting what you've observed.

**Comment by IsaakGroepT** [comment]
Okay awesome, thanks for the info. Glad this is only improving!
