### ISSUE TITLE
Preserve Source File Timestamps on Upload to Blobs from Windows 

### ISSUE THREAD

**Issue by michal-wieleba** [Azure/azure-storage-azcopy#2305]
##### Note: The version is visible when running AzCopy without any argument
10.19.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy
### What problem was encountered?
azcopy loses the original file metadata for Creation, LastWrite, and LastAccess.
### How can we reproduce the problem in the simplest way?
Just copy the file from windows to azure storage
### Have you found a mitigation/solution?
No
This issue stil persist, I don't know why https://github.com/Azure/azure-storage-azcopy/issues/1039 has been closed. Posix properties can be retained only for Linux/Blob storage, not for windows. There is no option for retaining timestamp metadata from source file system.

**Comment by vibhansa-msft** [comment]
- Backend supports only setting the last modified time and not creation/access time.
- Last modified time can be preserved on linux based system but it might not work when you upload through windows.

Can you validate LMT is preserved or not when you upload from linux system.

**Comment by michal-wieleba** [comment]
Yep, I know that it' not working on Windows. That's why I have reopened this issue.

**Comment by michal-wieleba** [comment]
.

**Comment by adreed-msft** [comment]
LMT persistence is a part of POSIX properties preservation, which gets stored in metadata. It is not actually setting the LMT on blobs. POSIX property preservation is not possible on Windows, because Windows does not support the concept of POSIX properties. Windows, insteads, supports SMB properties. SMB properties preservation is supported on Windows when targeting Azure Files.

That all aside, the Blob service doesn't support setting LMT for real; it's only updated when the blob itself is modified. If you'd like to see that supported service side, [the Azure Storage team would love to hear your feedback!](https://aka.ms/AzStorageFeedback)

**Comment by Nehmiabm** [comment]
Is there a way to preserve SMB properties on windows when uploading to Azure Blob Storage then if POSIX is not supported on Windows? This is a very important feature for Windows users and yet the issue is closed. SMH!
