### ISSUE TITLE
Scripting Azcopy(Cron Job or Scheduled Tasks) Local to ADLS Gen2 with SAS

### ISSUE THREAD

**Issue by emacdonald25** [Azure/azure-storage-azcopy#231]
### Which version of the AzCopy was used? 
AzCopy 10.0.7-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
C:\Users\em\Desktop>azcopy cp "C:\Users\em\Desktop\test" "https://adlsve.dfs.core.windows.net/staging?sas

### What problem was encountered?
failed to perform copy command due to error: OAuth token or shared key should be provided for Blob FS
### How can we reproduce the problem in the simplest way?
Try to upload data from local to Azure Data Lake Gen2 Storage account with SAS

*I understand that SAS is not supported, however, we need to set up some scripting with azcopy to do a nightly dump
### Have you found a mitigation/solution?

No, I was told azcopy has Hidden pararms that we might be able to use but I'm not able to find them. We are trying to set up some automation using azcopy like we have done before but this time we need to send it to this storage account ADLSv2

**Comment by Hong-Revo** [comment]
As the documentation says ADLSgen2 doesn't support SAS right now. This is a limitation in the ADLS2 API, and nothing to do with azcopy itself.

**Comment by emacdonald25** [comment]
any work around?

**Comment by zezha-msft** [comment]
Hi @emacdonald25, thanks for reaching out!

You could use Shared Key instead by specifying two environment variables ACCOUNT_NAME and ACCOUNT_KEY. These are indeed hidden from users, since we generally discourage using Shared Keys as they have too much privilege to be passed around on the command line. But as you already know we don't have SAS support for ADLSGen 2 yet. Please be very careful with respect to storing your credentials that don't expire.
