### ISSUE TITLE
Can‘t sync changed file from local to Azure

### ISSUE THREAD

**Issue by sysnick** [Azure/azure-storage-azcopy#240]
Dear.

I want to test azcopy sync function.

I createa txt file in a local folder and sync the folder to Azure Storage.The txt file sync to Azure Blob successed.

Then I modified the content of the txt file, run the sync again, But the txt file didn't sync to Azure Blob.

I have no idea how to use the AzCopy sync function.

**Comment by seguler** [comment]
Sorry for the trouble. Sync function had bunch of bugs, we have just rewritten it and are about to release the new version where all works pretty good.

In your scenario, sync version would simply update the file in the destination because the local file will have a last modified time that is newer in Blob storage. So what you are expecting will work in the next release.

**Comment by sysnick** [comment]
Got it. Thanks for reply. Very expect for the next release. One of my customer need this function very much.
