### ISSUE TITLE
Percentage does not takes into account skipped files?

### ISSUE THREAD

**Issue by aritztg** [Azure/azure-storage-azcopy#2415]
### Which version of the AzCopy was used? 
 10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
```
azcopy cp source destination --recursive --overwrite=ifSourceNewer --log-level=ERROR
```

### What problem was encountered?
I am copying over 76M files to an Azure fileshare, but:
```
8.3 %, 9389683 Done, 0 Failed, 20504029 Pending, 46507331 Skipped, 76401043 Total, 2-sec Throughput (Mb/s): 0.7594 (Service may be limiting speed)
```

This 8.3 % feels a bit wrong.

Right now, as the output states, only 20.5M out of those 76M are pending to be checked (or copied). This a continuation of an incomplete copy, so not all 76M requires a copy (because `--overwrite=ifSourceNewer`), and so far 46.5M were skipped due to that.
So 9389683+46507331= 55897014 were actually checked, which is 55897014/76401043, 73.16% seems more like a proper progress percentage.

### How can we reproduce the problem in the simplest way?
Sync a folder into a destination. Then add more content (if possible, some thousands of very small files, so the check will take more time and you can check it with more ease) and re-sync again.

### Have you found a mitigation/solution?
No. But it is not critical at all.

**Comment by nakulkar-msft** [comment]
Hi @aritztg, Percent complete takes into account skipped files as well. In your case a large file might be pending transfer while skipped/completed ones are very small. That would be cause for the skew in percent complete.

**Comment by michafaw** [comment]
> Percent complete takes into account skipped files as well. In your case a large file might be pending transfer while skipped/completed ones are very small. That would be cause for the skew in percent complete.

@nakulkar-msft  This doesn't appear to be true in 10.26.0-Win64. For example, using the following call:
`azcopy cp source destination --recursive=true --overwrite=ifSourceNewer --as-subdir=false`
If I make that call twice in a row (with no external file changes on either end), all files will be skipped in the second call. Unfortunately, the final **percent complete is reported as 0.0% instead of the expected 100.0%**.

From the end of the log file:
```
2024/09/20 19:20:53 0.0 %, 0 Done, 0 Failed, 0 Pending, 128 Skipped, 128 Total, 
2024/09/20 19:20:53 Closing Log
```
I see something similar if I instead cause the first call to fail halfway through (or alternately add additional files to the source just after the first call completes). **The second call will not reach 100%, and shows a percent representing only the files that were NOT skipped**. (e.g. 41.6%) This is the case in both the "live" progress and the EndOfJob progress.

Per a comment from 2020 that may be out of date ([link](https://github.com/Azure/azure-storage-azcopy/issues/981#issuecomment-620289552)), the percent is calculated using "bytes transferred divided by total (known) bytes", which matches the behavior I am seeing.
