### ISSUE TITLE
Update npm package to include latest bin versions in its optional dependencies

### ISSUE THREAD

**Issue by JorgeLievanoLeanIX** [Azure/azure-storage-azcopy#2501]
##### Note: The version is visible when running AzCopy without any argument
Latest npm package version `3.0.0`

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Install the npm package

### What problem was encountered?
The binary included in the npm package's optional dependencies is using an outdated version `10.19.0` which has several security vulnerabilities.

### How can we reproduce the problem in the simplest way?
Install the package in any OS, they all use the same version.

### Have you found a mitigation/solution?
Manually remove from `node_modules` the outdated version, download the latest version for my OS (https://aka.ms/downloadazcopy-v10-linux) and manually place it in the same location after package is installed.

Doing this manually is not a big issue but it has to be done constantly for a service that installs npm dependencies.
It would be great if this was updated to use the latest, more secure versions of the binaries.

**Comment by gapra-msft** [comment]
@MRayermannMSFT @JasonYeMSFT could you please take a look at this request

**Comment by MRayermannMSFT** [comment]
Hi @JorgeLievanoLeanIX , thanks for opening an issue!

Yes, we've definitely done a poor job of keeping the npm distributions of the executables up to date. We had everything ready to go for publishing 10.22.0 to npm, but unfortunately during testing with azcopy-node, a regression was discovered that makes 10.22.0 incompatible with azcopy-node.

And it is exactly for that reason why we don't have azcopy-node simply download the latest AzCopy. The way AzCopy is used via azcopy-node is a wee bit different than how you normally use AzCopy via a CLI, so there's extra testing and verification we do to make sure the latest version is compatible.

However, again, you are correct that it is important that the executables on npm are generall kept up to date due to security fixes that new releases contain. We're already in the process of re-evaluating how we prioritize publishing new versions to npm, and hopefully you can see a change in cadence going forward.

For today though, if you are concerned about deploying the older versions of AzCopy, please feel free to take advantage of the `exe` option on `AzCopyClient`:
 
![image](https://github.com/Azure/azure-storage-azcopy/assets/21112697/3b0814c0-f388-4e2d-9cc6-9c24fe9eb6ec)

This option allows you to specify a different AzCopy executable to be used, instead of the ones in the executable npm packages. This should allow you to download and manually make use of 10.22.0 yourself. Though, as I said earlier, there is an issue with 10.22.0 and AzCopy node. Specifically, if you make use of OAuth authentication, 10.22.0 has a regression in how it receives tokes shared in the way that azcopy-node shares them. But if you don't make use of that, then you should be fine to use 10.22.0.

Let us know if you have any further questions.

**Comment by JorgeLievanoLeanIX** [comment]
Thanks for your answer @MRayermannMSFT!

We do not use OAuth with `azcopy` so using version `10.22.0` should work just fine for us.
Hopefully it's not too long before the npm package starts including these updated binaries as well 🙏.

**Comment by vibhansa-msft** [comment]
Closing this as there is no action item open for AzCopy here. Feel free to post your comments in this regard here.
