### ISSUE TITLE
Outdated README and issues scripting install

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-storage-azcopy#253]
Firstly, thanks this is awesome and working great for speeding up my copies. One issue I have is around install. 

Current `readme` instructs to install as follows:

```
wget -O azcopyv10.tar https://aka.ms/downloadazcopy-v10-linux
tar -xf azcopyv10.tar
cd azcopy_linux_amd64_10.0.4
./azcopy
```

However this fails as the tar contains `azcopy_linux_amd64_10.0.8` not `azcopy_linux_amd64_10.0.8`. 

The larger frustration is that I'm attempting to script the running of AzCopy as part of a `cloud-init` machine setup and including the version number inside the `tar` without providing a way to pin my install to a version means scripts break. 

As a workaround I've taken the url of the redirect and used this `https://azcopyvnext.azureedge.net/release20190301/azcopy_linux_amd64_10.0.8.tar.gz` then extracting using `tar -xf azcopyv10.tar --strip-components=1`. Can this URI be relied on to remain available?

In terms of a fix, would you be happy for me to submit a PR to use [GoReleaser](https://goreleaser.com/) to build the necessary binaries and publish them to the `releases` page on the github repository? I can commit the `.goreleaser.yaml` file but would need to CI configured with a `githubtoken` etc for the publish to work. 

I've done something similar with [azbrowse](https://github.com/lawrencegripper/azbrowse/releases) it automatically generates release notes, docker, brew, scoop and snap installers too if you want to set them up.

**Comment by zezha-msft** [comment]
Hi @lawrencegripper, thanks for reaching out and providing feedbacks!

Yes, the download links will remain available. In general, I'd suggest to stick to a particular version for scripting purposes. 

I really appreciate your offer to add GoReleaser into this project, but I don't think it will be able to meet all of our requirements. To start, the Windows executable needs to be signed before releasing. Also, we want to switch to Azure DevOps for CI (since Travis is a bit slow and unreliable sometimes), so maybe we could do this work a bit later. Thanks a lot for the suggestion though, I'll keep it mind!

I've updated the [README](https://github.com/Azure/azure-storage-azcopy/commit/098e0fce81f5e71fe13d65bd0d785bd6dae320ec).

**Comment by lawrencegripper** [comment]
Sure would you like me to update the README with details on how to pin to a release and using the extract method I mentioned when scripting things?

FYI GoReleaser support [signing](https://goreleaser.com/customization/#Signing) and runs in any of the CI tooling as it's just an executable (I've used it in Azure Devops and Circle CI)

**Comment by zezha-msft** [comment]
Hi @lawrencegripper, that'd be nice! Thank you!

We'll definitely consider leveraging GoReleaser. We also use CGO so some further research needs to be done.
