### ISSUE TITLE
Does Azcopy support to copy from Alicoud OSS to Azure Storage blob?

### ISSUE THREAD

**Issue by shirleyley007** [Azure/azure-storage-azcopy#2536]
Hi Experts,

Our cx asked about whether he can use azcopy to copy from Alicloud OSS to Azure storage blob. 
Official documents did no mention such practice, but seems that Alicloud OSS has similar design as AWS, and we did support the latter.
So, does azcopy have an interface for Alicloud OSS?

Many thanks.

**Comment by gapra-msft** [comment]
Hi, we do not currently support non AWS S3 endpoints, and do not currently have this feature on the roadmap due to planning limitations. [Here ](https://github.com/Azure/azure-storage-azcopy/issues/832)is a related issue. It links a 3rd party PR that you could take a dependency on in the meanwhile, but we can provide no guarantees/support should it not work.

**Comment by gapra-msft** [comment]
For now I will close this in favor of the earlier issue since it is effectively tracking the same feature.
