### ISSUE TITLE
10.22.1 and 10.22.2 invalid_request when logging in using AZCOPY_AUTO_LOGIN_TYPE and AZCOPY_MSI_RESOURCE_STRING

### ISSUE THREAD

**Issue by farrare22** [Azure/azure-storage-azcopy#2538]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What problem was encountered? 
BalajiFailed to perform Auto-login: ManagedIdentityCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------
### How can we reproduce the problem in the simplest way?
Set AZCOPY_AUTO_LOGIN_TYPE and AZCOPY_MSI_RESOURCE_STRING
Using a system identity with [Storage Blob Data Contributor role

### Have you found a mitigation/solution?
yes, revert back to 10.21.0

**Comment by gapra-msft** [comment]
Hi @farrare22,

Due to our migration to the latest azure-sdk-for-go identity library, the behavior of managed identity has changed. 

If you unset AZCOPY_MSI_RESOURCE_STRING, I believe the SDK will use the [system assigned identity by default](https://github.com/Azure/azure-sdk-for-go/blob/4422a472f1943c35b2d36330ef5d529b6a067f42/sdk/azidentity/managed_identity_credential.go#L69). In versions 10.21.X and I believe 10.20.X, there was a bug with the implementation of managed identity with resource id, which is likely why you were seeing success in 10.21.0.

**Comment by farrare22** [comment]
Thanks for the quick response!  This fixed this issue. Thanks again!EdOn Jan 16, 2024, at 11:26 AM, Gauri Prasad ***@***.***> wrote:﻿
Hi @farrare22,
Due to our migration to the latest azure-sdk-for-go identity library, the behavior of managed identity has changed.
If you unset AZCOPY_MSI_RESOURCE_STRING, I believe the SDK will use the system assigned identity by default. In versions 10.21.X and I believe 10.20.X, there was a bug with the implementation of managed identity with resource id, which is likely why you were seeing success in 10.21.0.

**Comment by gapra-msft** [comment]
Thanks for the confirmation! Closing this issue as a result.
