### ISSUE TITLE
Default level of logging

### ISSUE THREAD

**Issue by arnobf** [Azure/azure-storage-azcopy#259]
### Which version of the AzCopy was used? 
10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy --recursive=true "https://...." "https://...."

### What problem was encountered?
The current default level of logging is "INFO" which produces **unexpectedly huge** amounts of logging information: we were copying ~5M files which in turn produced **25GB** of log files at which time our disk was full and azcopy aborted :(

### Have you found a mitigation/solution?
Mitigation: specify --log-level=ERROR on the command line myself

**Proposed solution**: default level of logging should be ERROR (not even WARNING). If someone is interested in the nitty gritty details of the copy process, they can specify --log-level themselves and know what awaits them. Producing GBs of log files is not a sensible default!

But even that may not suffice: e.g. after copying 4M files with --log-level=WARNING, I have a 4MB log file (ok), but a **620MB .azcopy/plans** directory. Why should I be interested in plans **at all**?

**Comment by zezha-msft** [comment]
Hi @arnobf, thanks for reaching out and providing us feedbacks!

The default level was set to "INFO" since the tool is still in preview, and the logs would be really useful if we need to investigate an issue for the customers. You could point the logs to another location through an environment variable setting, please refer to `./azcopy env`. We'll definitely change the default logging level once the tool enters GA.

As for the plan files, they maintain the state of the jobs so that you can resume a job if some transfers failed. They also allow the user to query the results of a job. We are planning on adding a command to clean these away if the user no longer wants to keep a record of them. We've also shrunk the size of the plan files.

We are using this issue (#221) to track the associated work items. Please don't hesitate if you have any suggestion! Thanks!

**Comment by arnobf** [comment]
@zezha-msft Thank you for your reply. Glad to hear that in GA the default will be different :)

**Comment by jtmoree-kahalamgmt-com** [comment]
Why was this closed without any status update?  Is the tool in GA?  Is the default still INFO?

**Comment by JohnRusk** [comment]
Ah, sorry that wasn't clear. Ze's final paragraph above says that this issue is closed, because everything is discussed in #221 (which remains open).  Effectively this issue here was closed as a duplicate/child of #221.  

In order to make sure we can provide detailed support, we have left the default at INFO even though the tool is now GA. 

We are actively working on slimming down the worst cause of "log bloat" in INFO mode, and on providing appropriate cleanup capability for log and plan files.  I'm not 100% sure on our long term plan for what the default level should be.  I think we'll re-evaluate after we've done those other work items, and after we've observed how many support cases actually need INFO level, in the first months after GA.
