### ISSUE TITLE
AzCopy high Number of ListBlob API requests

### ISSUE THREAD

**Issue by EurikasHP** [Azure/azure-storage-azcopy#2663]
### Which version of the AzCopy was used? 
10.24.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync $filePath $blobUri --delete-destination=$true --log-level INFO --from-to LocalBlob # flat namespace blob

### What problem was encountered?
AzCopy makes one ListBlob request per virtual directory.
This is an issue when having a high number of directories. List blob requests cost ($) at least 10 times more than read operations.
The version 10.4.3 does not display the same behavior - only makes very few ListBlob requests compared to latest version. 

### How can we reproduce the problem in the simplest way?
(1) Create a local directory with 100 folders each containing 1 file
(2) Run above command twice with version 10.24.0
(3) Check API request statistics in Azure Monitoring, which should show 101 list blob requests.

### Have you found a mitigation/solution?
No

**Comment by ashruti-msft** [comment]
By default AzCopy uses parallel hierarchical listing for the Blob endpoint in order to speed up the listing process.

To reduce the IOs/cost or optimize for a flat structure, you can choose to disable parallel hierarchical listing by setting the environment variable `AZCOPY_DISABLE_HIERARCHICAL_SCAN` to true. Also, while using 10.4.3 version can you please tell me what its value was as well.

You can refer [this](https://github.com/Azure/azure-storage-azcopy/wiki/Cost-of-data-transfers) for more information.

**Comment by EurikasHP** [comment]
Thanks. 
I confirm with AZCOPY_DISABLE_HIERARCHICAL_SCAN set to $true the number of list blob requests is reduced to the number we saw with version 10.4.3. 
In 10.4.3 we never set the environment variable AZCOPY_DISABLE_HIERARCHICAL_SCAN.

**Comment by ashruti-msft** [comment]
Yes, even when you don't set AZCOPY_DISABLE_HIERARCHICAL_SCAN you can disable parallel listing by enabling includeDeleted flag and either includeSnapshot or includeVersion flags. This might be why you saw less calls while using the previous version without changing the env variable.

**Comment by EurikasHP** [comment]
Closing issue
https://github.com/Azure/azure-storage-azcopy/issues/2663#issuecomment-2088274751
