### ISSUE TITLE
azcopy changing the metadata to lower case while copying from one region to another.

### ISSUE THREAD

**Issue by MritunjaySingh94** [Azure/azure-storage-azcopy#2842]
Hi Team,

We are in the process of moving approximately 250GB of data from one Azure region to another. However, we are encountering an issue where the metadata is being converted to lowercase during the copy process, which is causing problems for us.

Could you please advise on how we can retain the original case of metadata during the transfer? Alternatively, if there's another approach we should consider to resolve this issue, please let us know.

Thanks in advance for your help.

**Comment by PremSahooESL** [comment]
Few of the metadata keys are on Camel Case. During copy, we expect this keys to be as it is, without being converted to all lower case.

Any suggestion or guidance will be a great helpful for us.

**Comment by tanyasethi-msft** [comment]
Unfortunately, AzCopy does not currently support preserving the original case of metadata keys during the copy process. This issue arises because the Go HTTP client, which AzCopy relies on, treats HTTP headers as case-insensitive, leading to the automatic conversion of metadata keys to lowercase.

As a workaround, you can use the Azure CLI to update the metadata after the data has been copied. This can help you retain the correct case for your metadata keys. The command az storage blob metadata update can be used to manually adjust the metadata as needed​

**Comment by MritunjaySingh94** [comment]
Hi @tanyasethi-msft , thank you for your response.

We would like to update only the metadata keys to CamelCase. Specifically, we need to change the key from displaypage to displayPage in our storage account, while keeping the values the same. We have millions of images where this metadata needs to be updated. Could you guide us on how to achieve this efficiently?
Sharing screenshot for reference.
![Image](https://github.com/user-attachments/assets/4521f78a-c23c-42ee-8c22-f5a8a4fa5d5a)
