### ISSUE TITLE
Potential Deadlock Issue

### ISSUE THREAD

**Issue by nsmesh** [Azure/azure-storage-azcopy#293]
##### Note: The version is visible when running AzCopy without any argument
10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run? copy
[azcopy-uplink-test.txt](https://github.com/Azure/azure-storage-azcopy/files/3006588/azcopy-uplink-test.txt)

### What problem was encountered?
Potential deadlock - commands never terminate - no notable errors in logs

### How can we reproduce the problem in the simplest way?
Attached

### Have you found a mitigation/solution?
Yes - reduce concurrent commands to no more than 8 azcopy commands for 10GB uploads. For smaller uploads, concurrency up to 128 has worked fine.

**Comment by zezha-msft** [comment]
Hi @nsmesh, thanks for reaching out!

You have a very interesting/unusual use case. May I ask why are you instantiating 16 AzCopy processes simultaneously? Doing so is most likely causing memory thrashing resulting in lowered throughput (and thus timing out after 900 seconds). FYI AzCopy caps its memory usage to 0.5GB*# of logical cores, with an upper ceiling of 16GB.

AzCopy is designed to push as much throughput as possible, so it must take up the necessary system resources (CPU + RAM) to do so. Typically a single instance of AzCopy is transferring many files, which is why we have all these flags, arguments, and pattern matching to find the right files to transfer. A single instance can leverage the system resources as efficiently as possible. Otherwise, multiple AzCopy processes would just step on each other, competing for CPU, memory, and network bandwidth. And since you are reading the same 10GB file with 16 instances, the disk is probably a bottleneck. 

If the tool behaved great in this setup, it probably means that it wouldn’t be able to achieve the best possible performance when running alone, as it's not taking up enough system resources.

**Comment by zezha-msft** [comment]
@nsmesh, I'm closing this issue for now due to inactivity. Please let us know if we can assist you in any other way.
