### ISSUE TITLE
When using azcopy sync it is only deleting the files. Is there any way to delete the folder which are empty?

### ISSUE THREAD

**Issue by akhilpathania** [Azure/azure-storage-azcopy#369]
When using azcopy sync it is only deleting the files. Is there any way to delete the folder which are empty? Supose i have Folder named "Sync" having a file "Sync/sync.txt" in source as well as in destination. Later Sync folder is deleted in source after then i sync that and it has deleted the sync.txt file but Sync folder is not deleted. Is there any way to delete it?

**Comment by zezha-msft** [comment]
Hi @akhilpathania, thanks for reaching out!

It sounds like you are talking about blob -> local sync. This behavior is currently by design: sync only interacts with files and does not touch the directories, since empty local directories may or may not be useful for the user. In addition, local -> blob sync would skip the empty directories so the round trip is not impacted.

If you'd like to delete all empty directories on your local drive, please take a look at this [article](https://www.networkworld.com/article/2773290/unix-tip--recursively-removing-empty-directories.html).
