### ISSUE TITLE
Azcopy 10.1.0 - Disk may be limiting speed

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#380]
### Which version of the AzCopy was used? 
10.1.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Window
### What command did you run?
.\azcopy cp $SourceDirFile $Destination_Azure --recursive=true --overwrite=false 

### What problem was encountered?
24 Done, 0 Failed, 32 Pending, 0 Skipped, 56 Total, 2-sec Throughput (Mb/s): 770.4925 (Disk may be limiting speed)

### How can we reproduce the problem in the simplest way?
Not sure

### Have you found a mitigation/solution?
no

What is (Disk may be limiting speed)? How do I resolve this issue.

**Comment by adreed-msft** [comment]
Hi, srini99mkl. This is intended functionality to alert the user when there may be a performance bottleneck. Out of curiosity, how could we word this better to be clearer to our userbase?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by srini99mkl** [comment]
Thank you. How do I know that is performance bottleneck? How can i remove these kind of bottleneck?

I think if Microsoft add what are all the common bottlenecks and how to resolve them to Azcopy 10 webpage, that will be very helpful t to the customers.

**Comment by adreed-msft** [comment]
Hi, there are a number of bottlenecks (including azure itself) that can't really be removed. It's less an error, and more of just information on why things are going slower than they could be.
________________________________

**Comment by JohnRusk** [comment]
@srini99mkl We've posted documentation on bottlenecks here: https://github.com/Azure/azure-storage-azcopy/wiki/Disk-and-service-constraint-indicators-in-AzCopy 

Note that Azure itself will only be the bottleneck in very rare cases. The only cases I can think of are if you hit the account throughput limit - but most people won't because its typically 20 Gbps or more - and page blobs (which have defined performance limits that can be substantially lower than the account limit).

If you are seeing the "Disk may be limiting speed" message, that usually means that the speed you see AzCopy running at is the maximum read speed that your disk can support.  If you'd like to check your disk speed independently of AzCopy, you can use a tool like: https://aka.ms/diskspd .  If that shows much faster speeds that what you see with AzCopy, that suggests a bug in AzCopy's performance tuning.  In that case, please log that as a separate issue, and include some information about what type of disk drive you have and, if possible, email me a logfile from running AzCopy.

I propose to close this issue now. Please let us know if you feel that this comment and the documentation don't answer your question, and in that case we can re-open this issue.

**Comment by sql-deadwood** [comment]
@JohnRusk It looks like --cap-mbps can also cause this message to display. Additionally, when cap-mbps is in use the following is logged repeatedly in the log file: PERF: primary performance constraint is Unknown.

**Comment by JohnRusk** [comment]
Hi @sql-deadwood .  I moved on to a different project, so my recollections of how that part of AzCopy works are about a year old.  But I'm a bit surprised by this:
>It looks like --cap-mbps can also cause this message to display
I didn't think those two features would interact in this way.

Whereas this...
>when cap-mbps is in use the following is logged repeatedly in the log file: PERF: primary performance constraint is Unknown.

...is not a surprise, because IIRC, I did not take cap-mbps into account when computing those performance constraints (sorry). The benchmark mode, with its more detailed analysis of constraints does take cap-mbps into account.

BTW, if AzCopy thinks disk is the constraint, then it will say so in the log.  I don't think it's possible for it to say that disk is the constraint on screen and that "unknown" is the constraint in the log - at least, not at the same moment in time.

Hopefully current team members will be able to commment further if necessary.
