### ISSUE TITLE
Copy local to Azure Blob Storage with Write-only SAS

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-storage-azcopy#394]
This used to work with AzCopy 7.x with "force" flag.

Windows 10 x64, AzCopy 10.1.2

Scenario: I created a _**write only**_ SAS and gave it to a client. He runs AzCopy with that SAS token for a blob container to copy a huge file. But Azure fails to authenticate the request. Is there any parameter to "force" AzCopy?

**Comment by adreed-msft** [comment]
Hi, alvipeo, we appreciate the feedback, but could you provide this issue in the proper format? Thanks!

**Comment by adreed-msft** [comment]
Hi, alvipeo, could you please edit your issue to provide the commands you executed in order to reproduce this? Thanks!

**Comment by alvipeo** [comment]
```
"G:\azcopy_windows_amd64_10.1.2\azcopy.exe" .\huge-file.mp4 https://account.blob.core.windows.net/video?st=2019-05-16T23%3A17%3A00Z&se=2019-05-19T23%3A17%3A00Z&sp=w&sv=2018-03-28&sr=c&sig=BSCXcyQJJV8A0e51BxH7WkYJGAHa1TH1nfO25hlJ8eo%3D  --overwrite=false --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob
```

**Comment by JohnRusk** [comment]
Alex, I think I see the problem. If you remove `--overwrite=false` I think it will work.  

V10 defaults for overwrite=true, which is similar to v7's force.  With v7's force, or v10's default of overwrite=true, write access should be fine because it doesn't need to read to see if the file is already there.

But with overwrite=false, it has to read to see if the blob is already there.  Hope that makes sense.

**Comment by stewartadam** [comment]
Note on recent versions of azcopy `--check-length=false` is also required to avoid an upload failure on write-only SAS tokens.
