### ISSUE TITLE
AzCopy run inside a cronned script outputs 0-byte blobs when piped

### ISSUE THREAD

**Issue by shybbko** [Azure/azure-storage-azcopy#413]
### Which version of the AzCopy was used? 
azcopy version 10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 18.04.2

### The problem

- When a bash script containing azcopy is run via cron and azcopy is set to copy something from Blob Storage and the result is piped (to gzip / tar / dd / etc.), the Blob is not read properly (0 bytes are returned). Additionally, if SAS token includes Write permission, the remote Blob in Storage Account gets overwritten and becomes a 0-byte-long one.

- When a bash script containing azcopy is run via cron and azcopy is set to copy something from Blob Storage and the result is not piped, the problem does not occur.

- When a bash script containing azcopy is run manually, the problem does not occur in either case (pipe or no pipe).

### Details
There is a following script:
```
#!/bin/sh
azcopy cp "path/blob?sas_token" /target/dir
azcopy cp "path/blob?sas_token" | dd of=/target/dir
```

- Running it manually via `./script.sh` results in both files being written properly.

- Running it via cron `0 0 * * * root /usr/local/sbin/script.sh >> /var/log/output.log 2>&1` results in first file being written properly, the second one is written with a length of 0 bytes. If SAS token includes Write permission, the remote Blob in Storage Account gets overwritten and becomes a 0-byte-long one.

### Have you found a mitigation/solution?
Unfortunately not.

**Comment by JohnRusk** [comment]
Thanks for reporting this.

**Comment by schybbkoh** [comment]
I guess it's worth noting that in a very similar environment (although not identical - see below), copying data to Storage Account (not from) in a "piped cron" works perfectly: `azcopy version 10.1.1` + `Ubuntu 16.04.6`

``` 
0 0 * * * root /usr/local/sbin/script.sh >> /var/log/output.log 2>&1 
```

```
#!/bin/sh
tar cf - directory --absolute-names | pigz | azcopy cp path/blob?sas_token
```

**Comment by zezha-msft** [comment]
Thanks @schybbkoh for the detailed description!

It looks like the tool was somehow tricked into thinking there's data coming in from the `stdin`([here](https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/copy.go#L1094)). We'll investigate and update this thread accordingly.

**Comment by ampedandwired** [comment]
Experiencing the same thing with a script that copies data from Azure to stdout which is piped to another command, then the whole script invoked from a Java app. I created a simple Python/shell script (running on Ubuntu 18.04) that does something similar:

testazcopy.sh
```bash
#!/usr/bin/env bash
azcopy copy 'https://mystorageaccount.blob.core.windows.net/container/foo.txt?sas_token' | cat > foo.txt
```

testazcopy.py
```python
from subprocess import Popen, PIPE
Popen("./testazcopy.sh", stdin=PIPE, shell=True)
```

Running the Python script will not only emit a zero byte "foo.txt", but it will also truncate the file in the storage account to zero bytes as well. I think this is because azcopy sees stdin as a pipe and thinks it should do a PUT rather than a GET.

Not sure if this explains the problem within the context of cron though.

**Comment by zezha-msft** [comment]
Hi @ampedandwired, thanks for your feedback! I've logged this item for further investigation.

**Comment by zezha-msft** [comment]
Thanks @rsheptolut thanks for the insights! 

Is it possible that one of the jobs got cancelled mid-way? There's a known issue (which we are solving) that cancellation is not cleaning up the in-flight transfers correctly.

**Comment by JohnRusk** [comment]
(Tagged with needs-retest not because it exactly needs retesting by the project team, but really just to mean, "needs active investigation".)  First step is to hear back from @rsheptolut re Ze's question above.

**Comment by rsheptolut** [comment]
@zezha-msft Yes. This is a script that I run manually after changing a couple of files, it syncs changes in my local folder to Azure Storage. Then on another PC I run the opposite to sync Azure Stotage to a local dir, which then automatically syncs with SharePoint with OneDrive sync. We have a lot of "security"-induced workflows like this - have to use an intermediate PC though RDP because of the corporate firewall. And I might have ran those scripts a couple times in different combinations to make sure everything is synced. At some point I definitely remember getting tired of waiting and closing the cmd window, to resume later. The expectation there was that I can cancel it at any time and it will leave the files in a consistent state - just not fully synced yet, but I can always rerun the script (the script simply runs azcopy sync for several containers) to finish the sync. Closed the script because for some reason it started doing hunderds of file transfers, even though I only changed a couple of files. Dates may have changed, but not contents or md5, oh well. And I'm temporarily on a 4mbit connection now and needed to take my internet back urgently for something: it's impossible to do anything on a poor connection when you have azcopy running, it somehow exhausts the entire connection. That's the entire story and the reasoning. Sorry that I don't remember the exact proper repro steps, and thank you for looking into it!

**Comment by zezha-msft** [comment]
Hi @rsheptolut, thanks for the detailed explanation!

Ah yes, if the tool is killed while running, the inflight transfers would not complete, and the destination files could be left in a corrupt state. 

That's a great insight though. We'll think about how we can make the experience better. Perhaps we could keep the incomplete files with a suffix ".partial", and rename them to the real name once download completes.

**Comment by rsheptolut** [comment]
@zezha-msft Something like that would be neat!

**Comment by adreed-msft** [comment]
Actually though, it would make sense if stdin for cron was a pipe. Perhaps we should use a flag for pipe up/download so we don't get confused by this. Thoughts, @zezha-msft?

**Comment by zezha-msft** [comment]
Closing due to age of issue. Please let us know if you are still experiencing difficulties, we can reopen if needed.

**Comment by shybbko** [comment]
Personally I'm not experiencing difficulties anymore since I've moved to a more reliable cloud provider ;) Whether the issue occurs anymore or got fixed in one of the commits since the issue got reported that I do not know. If anyone reading this struggles with this please do comment.

**Comment by zezha-msft** [comment]
@shybbko sorry to hear that 😢
