### ISSUE TITLE
Azcopy slow performance 

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/azure-storage-azcopy#414]
### Which version of the AzCopy was used? 
10.0.10

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Copy

### What problem was encountered?
Run copy command to download 1 file, it took minimum 0.03 minutes to run, 1.8 seconds
Run copy command to upload 1 file, it also took minimum 0.03 minutes to run
Regardless performance tier of azure blob, its the same... tested with premium blob too.

### How can we reproduce the problem in the simplest way?
Just download 1 file?

### Have you found a mitigation/solution?
I stop using azcopy.

**Comment by JohnRusk** [comment]
How big is the file and roughly how long did you expect it to take?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JohnRusk** [comment]
BTW, I suspect that within that 1.8 seconds you are experiencing various small delays due to application startup and wind-down.  On longer jobs - with one larger files or a larger number of small files all in the one job - startup and wind-down become insignificant compared to the job duration as a whole.

**Comment by andrew-vdb** [comment]
100 KB file, should be in milliseconds, people just need to be aware that you have startup performance problem in the case you won't fix this issue.

**Comment by zezha-msft** [comment]
Hi @andrew-vdb, thanks for your feedback! 

To clarify, a single 100KB file might be too small to benchmark the tool fairly. If a GPU is being tested, long-running rendering tasks would be used rather than a single image. 

AzCopy V10 is designed to transfer large amounts of data (XX TBs) over an extended period of time, it could even be weeks sometimes. As a result, it needs to have the right scalability for the job. Start-up/tear-down times become insignificant since the transfer job itself generally lasts way longer.

**Comment by zezha-msft** [comment]
If your use case is to upload really small files, please consider using the piping functionality:

```
Upload a single file with a SAS using piping (block blobs only):
  - cat "/path/to/file.txt" | azcopy cp "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"
```
