### ISSUE TITLE
Setting AZCOPY_CONCURRENCY_VALUE has no effect

### ISSUE THREAD

**Issue by webben-de** [Azure/azure-storage-azcopy#429]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
export AZCOPY_CONCURRENCY_VALUE=1
azcopy sync ...
### What problem was encountered?
The azcopy command doest respect the environment variable `AZCOPY_CONCURRENCY_VALUE `to limit to system resources 
### How can we reproduce the problem in the simplest way?
Setting the environment variable AZCOPY_CONCURRENCY_VALUE to 1
### Have you found a mitigation/solution?
No

So we notice that setting the environment `AZCOPY_CONCURRENCY_VALUE`  variable has no effect of limiting the outgoing request.
In the log file of the transfer it's shown by the line 
`Max concurrent transfer initiation routines: 64`
This seems to be the default value for our machine with 2 core (core count * 32) as of the docs.
With the environment variable set, this should be only 1 right?

**Comment by JohnRusk** [comment]
'Max concurrent transfer initiation routines' is a different thing, and is currently not controllable through an environment variable.  It controls how may files are read from disk in parallel.

AZCOPY_CONCURRENCY_VALUE controls how may concurrent HTTP operations are used. It does work.  If you set it to 1, then search the log file for PERF to find the performance stats lines, you'll see that the two HTTP-related states (H and B) never have more than 1 operation in total. (I.e. H + B <= 1).  Note that H only appears for downloads. For uploads just look at B.

Also, on most networks there's a visible difference in throughput when AZCOPY_CONCURRENCY_VALUE = 1 (It's pretty slow).

**Comment by mkohns** [comment]
Hi! Very interesting topic! 
When we use "azcopy copy" on large files (>1GB) we can see in htop that serveral transfer threads (go routines) are started to ship data to azure blob storage. The load on the linux node (also azure vm) rises up to 10 and above. We tried to minimize the load impact with "nice" and "ionice" + AZCOPY_CONCURRENCY_VALUE=1. We still see that serveral transfer threads are running in parallel. We actually want azcopy to behave more production friendly and let most io and cpu for the main application. 

Any ideas on that requirement?

**Comment by JohnRusk** [comment]
As far as I understnad, "nice" won't affect the number of threads.  And, if you have nothing else running at the time, it wont even affect the total CPU usage of the process. What it will do, is make sure that the nice process gives up lots of CPU when something else needs it.  So, if you didn't have other CPU load at the time, I'd suggest you re-run your nice test with other CPU load. I would expect that nice would work fine.

BTW in future releases we are planning to add direct control of the bandwidth used, and maybe also the ability to control "max concurrent transfer initiation routines" (which is currently hard-coded at 64).

Finally, the other option I would suggest, if nice doesn't work, is to try setting CPU affinity to control its CPU usage. On Windows I've tested this with "start /affinity 3".  The mask of 3 has two bits set, so that command restricts it to just 2 CPU cores.  That approach works if you have several cores and you can meet your goals by restricting AzCopy to use just some of them.  On Linux you can do it like this: https://serverfault.com/questions/32322/is-it-possible-to-limit-a-linux-process-so-that-it-can-only-run-on-a-particular 

But, if you already have a very small number of cores, that approach might not work I'm sorry.  In that case, maybe look at the cpulimit command. But note that we've never tested it with AzCopy.

**Comment by JohnRusk** [comment]
In 10.2.1 we just released the --cap-mbps parameter when lets you control network usage directly (and indirectly control CPU usage - since less network throughput means less CPU usage).

On that basis, I'm going to close this issue, since --cap-mbps provides better control than changing AZCOPY_CONCURRENCY_VALUE. Please let us know if we need to re-open the issue.
