### ISSUE TITLE
Add --check-md5 NoCheck to [S2S] Copy 

### ISSUE THREAD

**Issue by xyh1** [Azure/azure-storage-azcopy#450]
### Which version of the AzCopy was used? 
10

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp ...

### What problem was encountered?
Invalid Md5

It seems that AzCopy v10 does a Md5 valiadtion due to the new copy behavior with PutBlockfromURL. AzCopy v8 does not do this validation and is able to copy the md5 regardless of it not being 128 bit base 64 encoded.

Can you add a --check-md5 optional parameter to the cp behavior? 

Thanks,
Xin

**Comment by zezha-msft** [comment]
Hi @xyh1, could you please clarify the question?

I assume you are doing a blob to blob copy right? And there's invalid stored MD5 on the source blob?

**Comment by xyh1** [comment]
Yes, a customer uploaded a bunch of blobs with azcopy / storage explorer and then some of the MD5s were modified such that they no longer adhered to our storage MD5 128 bit base64 encoded string. 

They were able to make a copy of some of those "invalid" md5 blobs from 1 storage account to another using storage explorer because storage explorer uses the CopyBlob API instead of PutBlockfromURL. There is no md5 validation done on a CopyBlob operation , everything is copied over to destination from source blob.

azcopy v10 introduced the new copy behavior that is different from azcopy v8 and storage explorer because as it uses PutBlockfromURL instead of CopyBlob. This makes copies faster but there is no simple way to make a direct copy with all of the same properties. 

This probably necessitates a change to the [PutBlockfromURL REST API ](https://docs.microsoft.com/rest/api/storageservices/put-block-from-url)as there doesn't seem to be a way to disable the Md5 check. 

We can discuss more in person when I'm back in the office if you want.

Thanks,
Xin

**Comment by JohnRusk** [comment]
I doubt that the issue is in PutBlockFromURL. I suspect it occurs at the end, when we call PutBlockList. We would need to figure out what the desired behavior is and what the flag should be called.  'check' is not the right concept, because nothing is actually complaining that file content doesn't match the MD5. It's complaining that the MD5 is not in the accepted format.

**Comment by xyh1** [comment]
@JohnRusk 

Yes you're right, it is should PutBlockList when committing the blocks.
I think a way to handle could be similar to:

>       --s2s-handle-invalid-metadata string   specifies how invalid metadata keys are handled. AvailabeOptions: ExcludeIfInvalid, FailIfInvalid, RenameIfInvalid. (default "ExcludeIfInvalid")

There can probably be a option to handle invalid system properties.

**Comment by JohnRusk** [comment]
@xyh1 This is on our backlog, but not scheduled for work in the next 4 months.  Pls email me if you want to discuss further.

**Comment by JohnRusk** [comment]
To be clear, to anyone reading this, the feature already exists for downloads. `--check-md5 NoCheck` works just fine for downloads. This feature request is just for service-to-service copies (e.g. container to container or account to account)

**Comment by andrew-allen-work** [comment]
Any ideas how to acheive this now ? 
I have uploaded 5TB of data via the databox disk service and that data has been loaded into a storage account with a number of containers... 
However, I now need to copy from one storage account to another which has been created with terraform Iac with all our required private endpoints. The problem I seem to be facing is how I can verify the copy file hashes using md5 checksums? 

Is there anyway of verifying all copies between 2 different storage accounts because without this capabilty in AZCOPY V10 I need some other method or tool to do it. This is a Prod env. and I have a complete blocker if I cannot prove that the on prem data has been copied uploaded into azure and then moved to the final secured storage accounts by using checksums?
Any pointers would be great. The reason I am adding this comment is that I expected the md5 S2S capability to be in place.I cannot download and upload 5TB of data to double check checksums.. that would be rediculous given I have had to copy direct to disk and ship them back to AZURE for loading....

**Comment by JohnRusk** [comment]
@andrew-allen-work Do MD5 checksums exist on the data that you want to check? I.e. do they exist on the blobs in the final storage account?  If so, I think there's an answer as described here: https://github.com/Azure/azure-storage-azcopy/wiki/Data-integrity-and-validation .  See the section named "checking lots of blobs".

Basically, you just get a big-ish Azure VM (e.g. 16) cores in the same region as a blobs you want to check. Then you run AzCopy on that VM ... telling to to check the hashes but _NOT_ save the files to disk.  It just races through all the blobs, downloads each one, checks the hash, but never saves anything to disk.   If your blobs are really small it will take a while, but if your blobs are medium-sized or big it will be pretty quick and should take less than 2 hours.

BTW, I'm a bit rusty on the details, because I've been working in a different area for the last few years. But hopefully that's enough to solve your problem.   

Are there any other solutions?  I don't know. Maybe new solutions have come along in the years since I left AzCopy. I'll leave it to current team members to fill you in on those if they exist.

**Comment by andrew-allen-work** [comment]
@JohnRusk yes that link helps ;-)  I was already thinking of creating a VM for the purpose but if it doesn't download I can try an on prem VM first to see how it works, thanks for the advice and pointers to the wiki
Cheers.

**Comment by vibhansa-msft** [comment]
MD5 checksum validation is an optional process in later versions of AzCopy. Feel free to reopen if issue persists even with latest versions of Azcopy
