### ISSUE TITLE
Will there be some simple documentation examples that work?

### ISSUE THREAD

**Issue by brunis** [Azure/azure-storage-azcopy#487]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 8.1.0-netcore

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy Source:F:\Export\ Dest:"SASurl"
or
azcopy Source:F:\Export\ DestSAS:"SASurl"
doesn't really matter, it can't parse the source

### What problem was encountered?
The syntax of the command is incorrect. Error parsing the argument "Source:F:\Export\": parameter name is required.

### How can we reproduce the problem in the simplest way?
Do an azcopy from local filesystem to a DestSAS url. I was doing Exchange migration.

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Run AzCopy with no command line params to double check which version you have. If it is indeed 8.1, the docs are here : https://docs.microsoft.com/en-nz/previous-versions/azure/storage/storage-use-azcopy

I think your problem is that you need a forward slash to start each parameter name in v8.1

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by JohnRusk** [comment]
Sounds like that was the answer. So closing now.
