### ISSUE TITLE
Copying directory between two Storage Accounts in the same Resource Group fails on random file.

### ISSUE THREAD

**Issue by rbespalovnc** [Azure/azure-storage-azcopy#504]
### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy cp "https://rbespalovprimarystorage.blob.core.windows.net/sys-master-images/h3c?<SAS1>" "https://rbespalovbackupstorage.blob.core.windows.net/sys-master-images/?<SAS2>" --recursive=true`

(copy directory `h3c` in the container `sys-master-images` from one storage to another)

### What problem was encountered?
```
INFO: Scanning...
INFO: source is not validated as a single file: BlobNotFound
INFO: trying to copy the source as container/directory/list of files

Job 0e10edbb-b688-3b40-4548-537e6e2993c2 has started
Log file is located at: /home/rbespalov/.azcopy/0e10edbb-b688-3b40-4548-537e6e2993c2.log

0 Done, 0 Failed, 13 Pending, 0 Skipped, 13 Total, 
Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
RequestId:de695573-001e-0115-57c8-3ba5c5000000
Time:2019-07-16T11:22:11.9697628Z, Details: 
   Code: CannotVerifyCopySource
   PUT https://rbespalovbackupstorage.blob.core.windows.net/sys-master-images/h3c/h99/8796234973214?blockid=mjk5mgjknjitztu3mc02mzriltvmzjatnmy4yjq1zdrlmtrj&comp=block&se=2019-07-16t18%3A44%3A21z&sig=-REDACTED-&sip=-REDACTED-&sp=rwdlac&spr=https&srt=sco&ss=b&st=2019-07-16t10%3A44%3A21z&sv=2018-03-28&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.2.1 Azure-Storage/0.7 (go1.12; linux)]
   X-Ms-Client-Request-Id: [2045dbfe-1d68-4a17-6d50-db456debffc3]
   X-Ms-Copy-Source: [https://rbespalovprimarystorage.blob.core.windows.net/sys-master-images/h3c/h99/8796234973214?se=2019-07-16t18%3A48%3A30z&sig=-REDACTED-&sip=-REDACTED-&sp=rwdlac&spr=https&srt=sco&ss=b&st=2019-07-16t10%3A48%3A30z&sv=2018-03-28]
   X-Ms-Source-Range: [bytes=0-8954]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [248]
   Content-Type: [application/xml]
   Date: [Tue, 16 Jul 2019 11:22:11 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [de695573-001e-0115-57c8-3ba5c5000000]
   X-Ms-Version: [2018-11-09]
```

Copy fails at a **random** file from those 13 that are in this directory. When checking on Azure directly I see that no files are copied.

### How can we reproduce the problem in the simplest way?
Use azcopy to copy the directory from one BlobStorage account to the second BlobStorage account in the same resource group

### Have you found a mitigation/solution?

Run azcopy to download directory to the local PC and then upload to the second storage.
`azcopy cp "https://rbespalovprimarystorage.blob.core.windows.net/sys-master-images/h3c?<SAS1>" sys-master-images/ --recursive=true`

`azcopy cp sys-master-images/h3c "https://rbespalovbackupstorage.blob.core.windows.net/sys-master-images/?<SAS2>" --recursive=true`

### Additional info
* Same error happens if I try it with any single file instead of directory.

Azure Storage properties (may be related, may be not)
* I have a Contributor role on the Resource group that contains both Storages.
* Performance/Access tier: Standard/Hot
* Replication: Read-access geo-redundant storage (RA-GRS)
* Account Kind: BlobStorage

This issue is very similar to these two:
* https://github.com/Azure/azure-storage-azcopy/issues/446
* https://github.com/Azure/azure-storage-azcopy/issues/404

**Comment by JohnRusk** [comment]
I think I know what the issue is: your source SAS has an IP restriction on it. I.e. it only works when used from certain IP addresses.  I can see that from the sip= element in your error message. 

The way account to account copy works in AzCopy v10 is that it calls the PutBlockFromUrl API method, on the target account. It passes in the full SAS URL of the source, and the data is actually copied by the Storage service.  So the request to get the data comes from the Storage Service's IP address, not from AzCopy.

Your easiest fix is if you can construct a source SAS without the IP restriction.  If you don't want (or aren't allowed) to do that, then you'll need to create one that allows traffic from the range of IP addresses used by Blob Storage.  I don't know the details of that, but I think the IP ranges are documented online.

Finally, in a future release, we plan to support user delegation keys, which lets you authenticate entirely with AAD (no SAS in your command line) and (if I understand correctly) we generate the necessary SASs for the blob-to-blob copy. That work can be found here: #493. We don't have any public release date for it yet.

**Comment by rbespalovnc** [comment]
@JohnRusk 
thank you, you got the issue perfectly right.

For someone who needs a solution - I found a list of Azure Dataceter ip addresses [here](https://www.microsoft.com/en-us/download/confirmation.aspx?id=41653) but it's in the deprecating status. So for the test I just set an IP range 0.0.0.0-255.255.255.255 for the SAS and it worked.

I don't have any more questions for this issue, so it's fine to close it.
