### ISSUE TITLE
Azcopy10 - Is it possilbe to copy files within a ADLS gen2 storage account from one folder to another folder

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#507]
### Which version of the AzCopy was used? 
Azcopy 10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Azcopy cp Storage_account_A Storage_account_A --recursive true
### What problem was encountered?
failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

**Comment by JohnRusk** [comment]
AzCopy can't figure out the type of the source or destination, based on the URLs that you've used for the source and destination. There's a known bug where that happens with HTTP.  You can add this to the command line to tell it exactly what you mean:

--from-to BlobBlob

Also try putting double quotes around the two URLs, to make sure they parse correctly. 

BTW, you said storage_account_a for both source and dest. Is that right?

**Comment by srini99mkl** [comment]
Hello, I am trying to copy files with Azure Data Lake Storage Gen2

Here is how the command would looks like from PS command promopt

PS C:\Program Files (x86)\AzCopy>>> .\azcopy cp "" "https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt “https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt/.replacedfiles/"


I am getting the following error…. Please help ASAP!

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired



Thanks,
Srini Arumilli

**Comment by srini99mkl** [comment]
Just updating the command to make it more clear

PS C:\Program Files (x86)\AzCopy>>> .\azcopy cp "https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt" “https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt/.replacedfiles/"

I am getting the following error…. Please help ASAP!

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired



Thanks,
Srini Arumilli
Markel - IT
Data Services
4501 Highwoods Parkway, Glen Allen, VA 23060
Direct: (804) 525-7041
www.markelcorp.com<http://www.markelcorp.com/>

From: Arumilli, Srinivas
Sent: Thursday, July 18, 2019 8:58 AM
To: 'Azure/azure-storage-azcopy' <reply@reply.github.com>; Azure/azure-storage-azcopy <azure-storage-azcopy@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Azure/azure-storage-azcopy] Azcopy10 - Is it possilbe to copy files within a ADLS gen2 storage account from one folder to another folder (#507)

Hello, I am trying to copy files with Azure Data Lake Storage Gen2

Here is how the command would looks like from PS command promopt

PS C:\Program Files (x86)\AzCopy>>> .\azcopy cp "" "https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt “https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt/.replacedfiles/<https://mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt%20“https:/mkdssdedldev212.dfs.core.windows.net/msdsd-dssds-fssdsdys-edfffl-dev-001/refidfdfned/Asdsds/dbo/DisdsdsdResdsdsursdsde_Adff.txt/.replacedfiles/>"


I am getting the following error…. Please help ASAP!

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired



Thanks,
Srini Arumilli

**Comment by JohnRusk** [comment]
Ah, I see. Sorry, I did not realise you were copying between dfs endpoints. Unfortunately, that is not currently supported. For account to account copies, we only support blob endpoints (non-hierarchical).

The reason for the limited support is that interoperability, between blob and dfs, is coming in the Storaeg Service, so that you'll be able to use the existing blob to blob copy feature even on hierarchical accounts.  That's why we have not written dfs-to-dfs copy (since soon it won't be needed).  In fact, interop just went into preview in some regions a few days ago. Here is the link: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access 

To copy account to account right now (without interop) you'll need to either download the data to disk then upload it to the target (only works for small-to-moderate data volumes, due to disk space requirements) or use something like Azure Data Factory (I think it as Gen2-to-Gen2 copy).  Sorry about the limited support right now, and doubly sorry that I didn't previously see "gen2" right there in the subject line of this issue!!!!  Yesterday I just followed the link in from the notification email, and didn't read the title!

**Comment by tdebroc** [comment]
Hello there !
2 days ago, interop general availability has been announced:
https://azure.microsoft.com/fr-fr/blog/multi-protocol-access-on-data-lake-storage-now-generally-available/
However I tried an azcopy between two gen2 storage account but it failed woith same error:
"the inferred source/destination combination is not currently supported."
Do you know when it will be fix ?

**Comment by JohnRusk** [comment]
Did you use blob endpoint urls for source and destination?

**Comment by tdebroc** [comment]
Hey John ! Thanks for your answer. Indeed I was only using the DFS ones ! Thanks for pointing that ! 

With blob, it goes further:

```
~/azcopy_windows_amd64_10.3.2
$ export AZCOPY_SPA_CLIENT_SECRET=XXXXXX
$ ./azcopy.exe login --service-principal --application-id XXXXXXX --tenant-id= XXXXXXX
INFO: SPN Auth via secret succeeded.
$ ./azcopy.exe copy 'https://mystorageaccount.blob.dfs.core.windows.net/fs1/test ' 'https://otherstorageaccount.blob.dfs.core.windows.net/fs2/test' --recursive
INFO: Scanning...
INFO: Using OAuth token for authentication.
failed to perform copy command due to error: a SAS token (or S3 access key) is required as a part of the source in S2S transfers, unless the source is a public resource
```

Unfortunately, my company doesn't allow public resources for security reasons.
I will have to figure out how to generate a SAS Token for 2 storages Account. I know how to do it for one, it's easy on the portal. But for 2 storage Account, I need to find... Or maybe you know John ? 
Best regards

**Comment by JohnRusk** [comment]
OAuth is fine for the destination. You only need a sas for the source account. The easiest place to generate them is in Storage Explorer. Hopefully it will let you generate a blob style one for your adls gen 2 container. If that doesn't work, Powershell might. Remember you need a blob sas url, not an adls gen 2 sas url. 

Let us know if your can't get it working

Btw a future version of AzCopy will remove the need for a sas on the source. (by using OAuth for both source and dest)  Choose "watch" on our releases page to be notified when it comes out.

**Comment by kyrmca** [comment]
i am trying to Run Azcopy  in ADF V2 custom activity command ,but it's not working .
 **ADF Command : Azcopy.exe copy  @pipeline().parameters.Source  @pipeline().parameters.Dest**
May i know how to pass dynamic source and destination path though the ADF pipeline parameters or Varaibles in AZcopy?

**Comment by srini99mkl** [comment]
Thank you, coping files from one folder to another folder with ADLS gen2 storage account.

I have couple of more questions:

1)      Is it possible to move the files from one folder to another folder thru AzCopy?  my requirement is not keep the files in source folder once they have been moved from source folder to destination.

**Comment by JohnRusk** [comment]
We don't currently support "move" (i.e. we don't have support for deleting the source).  That's an open feature request here: See https://github.com/Azure/azure-storage-azcopy/issues/45

**Comment by tdebroc** [comment]
Hey John,
I retried operations today, but faced others problems :-). Here is a summary, hoping you would have some tips:

# Which Version of Azcopy ?

10.3.2

 

# Which platform do you use?

Windows 10

 

# What do I want to do ?

 

I want to copy data from a AdlsGen2 storage account to another AdlsGen2 storage account.

 

At first I will try to copy data from 1 Adlsgen2 storage account to the SAME Adlsgen2 storage account.

 

# What problems were encountered ?

 

## 1st Problem: RESPONSE Status: 502 badgateway

Here is what I did:

 

export HTTPS_PROXY=http://127.0.0.1:3128

export HTTP_PROXY=http://127.0.0.1:3128

$ ./azcopy.exe login --service-principal --application-id XXXXX --tenant-id=XXXXX

INFO: SPN Auth via secret succeeded.

 

$ ./azcopy.exe copy 'https://mystorageaccount1.blob.dfs.core.windows.net/filesystem1/folder1/subFolder1/myFile&ss=XXX&srt=sco&sp=rwdlacup&se=2 019-12-02T20:20:05Z&st=2019-12-02T12:20:05Z&sip=0.0.0.0-255.255.255.255&spr=https&sig=XXXXXXXXXXXXXXXXXX' 'https://mystorageaccount1.blob.dfs.core.windows.net/filesystem1/folder1'

INFO: Scanning...

INFO: Using OAuth token for authentication.

INFO: Failed to create one or more destination container(s). Your transfers may still succeed if the container already exists.

 

failed to perform copy command due to error: cannot start job due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42

 

As you can see it works for Login, but then fail on copy ...

I can do curl to Adlsgen2 API easily with this proxy

If proxy is badly set, why would it work for login but not for copy ?

 

 

## 2nd Problem: Extremely Long authentification via Oauth Token :

 

To bypass 1st problem with my proxy, I have created a VM on Azure Cloud.

 

$ ./azcopy.exe login --service-principal --application-id XXXXX --tenant-id=XXXXX

INFO: SPN Auth via secret succeeded.

 

$ ./azcopy.exe copy 'https://mystorageaccount1.blob.dfs.core.windows.net/filesystem1/folder1/subFolder1/myFile&ss=XXX&srt=sco&sp=rwdlacup&se=2 019-12-02T20:20:05Z&st=2019-12-02T12:20:05Z&sip=0.0.0.0-255.255.255.255&spr=https&sig=XXXXXXXXXXXXXXXXXX' 'https://mystorageaccount1.blob.dfs.core.windows.net/filesystem1/folder1'

INFO: Scanning...

INFO: Using OAuth token for authentication.

 

This stay Like this for an infinite time

....

 

To debug this, I try:

 

If I run :

$ azcopy jobs list

Existing Jobs

JobId: 7ce25733-2a1d-7e45-630b-XXXX

Start Time: Monday, 02-Dec-19 14:11:18 GMT

Status: Cancelled

Command: bench https://storageaccount1.blob.dfs.core.windows.net/yars-test/

 

For "bench" it looks, it has created a job, but for "copy", I don't see any jobs...

 

I have tried

> ./azcopy --log-level DEBUG

Error: unknown flag: --log-level

 

I have added  --log-level DEBUG at the end of my command, but I don't more than before, only:

"

INFO: Scanning...

INFO: Using OAuth token for authentication.

"

 

How Can I debug more the calls ?

I would to know exactly why it hangs, which calls it is making...

**Comment by JohnRusk** [comment]
I think both problems are caused by the same thing.  The URLs you're using, as you posted above, contain: "accountname.blob.dfs.core.windows.net".  They should have blob OR dfs. Remove the dfs section of the URL, and I think both your test scenarios will work.

**Comment by tdebroc** [comment]
Ohh ! Thank you so much John :-) ! 

I just had a last struggle by understanding a 403 Error.
In fact, it was the IP Range. I had put 0.0.0.0-255.255.255.255 and it didn't worked, I had 403. I then left the field "IP Range" empty and generated the SAS Token and now it work like a charm !

I successfully copied 1 file from 1 Adlsgen2 storage Account to another Adlsgen2 storage Account ! Perfect !

That's awesome :-) Thanks much again John !

Note: To understand 403, there is several things to check (Blob Data Owner Role, Time of SAS Token, IP Range ...), so if there were explanation on the 403, it would be perfect.

**Comment by srini99mkl** [comment]
Hello John, Do we still need to use Blob SAS key to move files from one folder to another folder within Gen2 Storage account?  Or AzCopy latest version does not require that?

**Comment by JohnRusk** [comment]
It will be version 10.4 that gives the feature you're asking for. You can track the pull request here: https://github.com/Azure/azure-storage-azcopy/pull/689   Note that 10.4 includes three big features, of which this is the smallest (and this SAS issue has been held up behind the other two features a little, but the plan is for all three to be in 10.4).

**Comment by srini99mkl** [comment]
Thank you. Do you know when 10.4  will be released?

**Comment by JohnRusk** [comment]
We don't pre-announce dates, sorry.

**Comment by tdebroc** [comment]
Thanks for the news, what are the 2 others bigs features for azcopy 10.4 please ?

**Comment by JohnRusk** [comment]
Preserving properties (including ACLS) when transferring to and from Azure Files; and preserving folder properties (including ACLS) and existence (including empty folders) when transferring between folder-aware sources. (File systems and Azure Files are folder-aware. Blob storage is not because folders there are just virtual).   
ACL preservation is highly-demanded, and folder preservation is necessary to make ACL preservation logically consistent.

**Comment by srini99mkl** [comment]
Thank you. Do you know when 10.4  will be released?


From: Arumilli, Srinivas
Sent: Tuesday, January 21, 2020 4:23 PM
To: 'Azure/azure-storage-azcopy' <reply@reply.github.com>
Subject: RE: [Azure/azure-storage-azcopy] Azcopy10 - Is it possilbe to copy files within a ADLS gen2 storage account from one folder to another folder (#507)

Thank you. Do you know when 10.4  will be released?

**Comment by JohnRusk** [comment]
We don't announce release dates in advance, sorry.  There's still quite a lot of work to do on 10.4.

**Comment by srini99mkl** [comment]
Hello John, I am using 10.4  version, but the flowing function is still not working…  Copying files from between Gen2 storage accounts, it is still asking for SAS key. Can you please help?


failed to perform copy command due to error: a SAS token (or S3 access key) is required as a part of the source in S2S transfers, unless the source is a public resource


From: Arumilli, Srinivas
Sent: Thursday, January 23, 2020 11:44 AM
To: 'Azure/azure-storage-azcopy' <reply@reply.github.com>
Subject: RE: [Azure/azure-storage-azcopy] Azcopy10 - Is it possilbe to copy files within a ADLS gen2 storage account from one folder to another folder (#507)

Thank you. Do you know when 10.4  will be released?


From: Arumilli, Srinivas
Sent: Tuesday, January 21, 2020 4:23 PM
To: 'Azure/azure-storage-azcopy' <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [Azure/azure-storage-azcopy] Azcopy10 - Is it possilbe to copy files within a ADLS gen2 storage account from one folder to another folder (#507)

Thank you. Do you know when 10.4  will be released?

**Comment by blueRegen** [comment]
Hi

I want to copy a bunch of ORC files (about 700 of them)  from ADLS Gen 2 to Azure Blob.  
Is it not possible?  Is it too complex?  

thanks.

**Comment by JohnRusk** [comment]
@blueRegen This looks like a new question. I'd suggest you post it as a new issue.

**Comment by mattiasmoser8451** [comment]
@JohnRusk - like other users in this thread we are trying to do s2s copy (from ADLS Gen2 to ADLS Gen2) and can only do so with a SAS token on the source. Allowing users to create SAS tokens forces us to give these users access permissions (far?) beyond "read", which is a concern for our security folks. What is the best practice to do what we need to do? What are the minimal additional access permissions so that users can get SAS tokens? How are your other customers working with what looks to us like a pretty serious limitation?

You also refer to a solution to the issue in version 10.4 - did that solution end up not making it into the release? Has the referenced PR (https://github.com/Azure/azure-storage-azcopy/pull/689) been abandoned?

**Comment by JohnRusk** [comment]
@mattiasmoser8451 I'm on a different project now, and no longer involved in AzCopy.  (I only saw this because GitHub notified me when you @-mentioned me.)

@zezha-msft or @amishra-dev should be able to answer your question.

**Comment by mattiasmoser8451** [comment]
@zezha-msft or @amishra-dev - would you be able to help with the questions above?

**Comment by zezha-msft** [comment]
Hi @mattiasmoser8451, it seems that there are some confusions here. In general, your customers should not be in the business of creating SAS tokens, as only the account owner (the one with the storage account key) should do it. If you have users who need a SAS token, you should perhaps have your service hand them the tokens ready.

Please create a new issue if you have any further questions. Thanks!

**Comment by mattiasmoser8451** [comment]
@zezha-msft: before I create a new issue, please help me with 2 questions:

(1) What is PR https://github.com/Azure/azure-storage-azcopy/pull/689 about? I thought it would support seamless copy based on OAuth authentication only. Am I mistaken?
(2) Are you suggesting that we build a service that provides users with SAS tokens whenever they need one?

**Comment by zezha-msft** [comment]
1) Yes, the PR needs to be reworked but basically the user can authentication with OAuth, and we'd generate an identity SAS for them. They have to have the right permissions on the account.
2) I'm not aware of your application so I cannot say. I made the comment because typically your users shouldn't be the ones generating SAS using account keys. In some applications, the service hands a token to an end user (ex: a mobile app user) who can use it upload/download blobs. You can also use [RBAC with Storage](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal).
