### ISSUE TITLE
High memory usage when uploading big files

### ISSUE THREAD

**Issue by marcioos** [Azure/azure-storage-azcopy#530]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy cp /local/file/path <https://destinationBlobUrl> --log-level WARNING

### What problem was encountered?
While uploading big blobs (~13 GB), `azcopy` memory allocation spikes to around 6 GB. That's too much for our setup, where we can potentially upload several big blobs concurrently across multiple processes running in the same VM, which has 32 GB of RAM.

I guess most of the memory is being allocated by upload buffers. Is there a way we can limit the maximum memory allocated by `azcopy` during upload (and download) operations?

**Comment by zezha-msft** [comment]
Hi @marcioos, thanks for reaching out!

It seems that you have a pretty powerful machine, and that is why AzCopy is allowing itself to allocate a lot of memory. How many cores does the machine have btw?

Is there a way of grouping your upload tasks together? For example, instead of submitting a job for each individual file, could you do:
```
azcopy cp "/usr/bla/*filename.txt" https://destinationBlobUrl 
```

In our next release, there will be a configuration allowing the user to override the default algorithm that calculates how much memory to use.

**Comment by JohnRusk** [comment]
The setting, coming in the next release, will be an environment variable called AZCOPY_BUFFER_GB.  When the next version is release, run `AzCopy env` for help information on the environment variable.

BTW, as Ze says, AzCopy is designed with the expectation that upload tasks will be grouped together (one instance of AzCopy, uploading multiple files) instead of one instance per file.  However, the new environment variable should allow it to be run in in the way you desire, if grouping the tasks together is not practical.)

We will leave this issue open until the new release comes out, then we'll close it.

**Comment by marcioos** [comment]
Hi, thanks for the replies. Good to know that an option for controlling the buffer size is on the way.

Unfortunately in our setup we can't group AzCopy tasks like that. We have up to 15 distinct Docker containers running per VM (Azure F16s_v2 instance), each uploading potentially big blobs periodically with AzCopy, in isolation.

Until the new release comes out, is there a way we can indirectly influence buffer size? Like playing with the concurrency level, for example?

Just for planning purposes in our team, do you have an idea of when the next version will be published? I'm thinking that we might have to go back to using the Java SDK depending on that.

**Comment by JohnRusk** [comment]
Hi. For uploads, there's really only one way to indirectly influence buffer size, and that is to trick AzCopy into thinking that's its running on a smaller VM. That works because the current version sets a max buffer size that is 0.5 GB per CPU. So if you can, for instance, persuade it that there's only one CPU, then each instance will allocate 0.5 GB for buffers. With a bit of overhead for the rest of the app's memory usage, that should be less than 1GB per AzCopy instance. If I understand correctly, you're currently seeing 6GB per instance so this should be a good improvement. 

On Linux you can launch AzCopy using the taskset command to set CPU affinity. I'm not entirely sure how that translates to use in Docker, but if you investigate a bit you might find a solution. 

I hope that helps. 

The next version is about a month away, maybe a little longer. (We haven't published an exact date)

**Comment by JohnRusk** [comment]
Version 10.3 is now released with the AZCOPY_BUFFER_GB environment variable. It accepts decimals. E.g. to limit (each AzCopy instance) to 0.75 GB, set it to 0.75.
