### ISSUE TITLE
Provide source last modified time newer then destination last modified time.

### ISSUE THREAD

**Issue by klaaslanghout** [Azure/azure-storage-azcopy#55]
I'm assuming that  --overwrite:false will not overwrite matching blobs in the destination but, the /XO option of the previous azcopy was better (in the case for instance where you are doing multiple copies through time with the same source and destination path).

**Comment by zezha-msft** [comment]
Hi @klaaslanghout, thanks for reaching out!

To clarify, are you saying that instead of simply checking whether the destination blob exists, we should look at the lmts of the source and the destination? If that is the case, then the `sync` command should do exactly that. If you don't mind, please give it a try and let us know if its behavior corresponds to your expectations.
