### ISSUE TITLE
s3 to blob storage error.

### ISSUE THREAD

**Issue by psatyaa** [Azure/azure-storage-azcopy#558]
### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy cp "https://s3.amazonaws.com/zoetis-prod-ugc/uploads" "https://qapetcaredbstor.blob.core.windows.net/?sv[sastokendata]" --recursive=true

S3 Bucket - zoetis-prod-ugc
Directory Name: uploads

### What problem was encountered?
Error :
"failed to perform copy command due to error: cannot start job due to error: cannot list objects, The request signature we calculated does not match the signature you provided. Check your key and signing method."

Also attaching error screenshot for reference.

<img width="751" alt="AzCopy_Error" src="https://user-images.githubusercontent.com/22309002/63310073-44cbd400-c2c7-11e9-9b40-d63dbd4d1730.PNG">

### How can we reproduce the problem in the simplest way?
Create a directory in the S3 bucket with some files.  Give S3- IAM Full access rights on specific directory inside the bucket.    

### Have you found a mitigation/solution?
Not yet.

**Comment by JohnRusk** [comment]
I'm no expert on AWS auth, but is it possible that the key you used in your environment vars does not match the one that has full rights to the directory.

I also wonder if it might be something about the fact that your permissions are granted only at directory level. Maybe AzCopy is enumerating the bucket contents at a higher level (e.g. enumerating from the parent of that directory and then filtering).  It's long time since I've read that code, so I'm not sure.

@adreed-msft Would you have time to test this?  I.e. rights granted only at directory level in AWS. If you don't have time this week, pls say so.

**Comment by psatyaa** [comment]
This is a practical scenario where the business has shared keys on S3 Bucket's directory which is needed to be copied. 
So do you think you must need container level access to copy content?

**Comment by JohnRusk** [comment]
I'm not sure. Let's see if Adele has time to test it tomorrow.

**Comment by psatyaa** [comment]
@JohnRusk,  I am able to replicate the issue with AWS S3. The problem is not related to azcopy but with the group policy applied on S3 container. generated new user with updated policy on S3 and able to copy data.
Closing the Issue.

Thanks,
Satya
