### ISSUE TITLE
/xo capability is not available in v10.2.1

### ISSUE THREAD

**Issue by jiteshkumargouthamchand** [Azure/azure-storage-azcopy#559]
sync feature which is available is not doing similar behavior as that of /xo.
In our case we have recursive folders and the performance with sync is really bad. Refer to Issue 496 for performance details.

**Comment by zezha-msft** [comment]
Thanks @jiteshkumargouthamchand for reaching out!

We'll discuss and schedule this feature request accordingly.

**Comment by jiteshkumargouthamchand** [comment]
Any updates on /xo and performance improvement with newer AzCopy version ?

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft  As you know with recent MS Windows security patches we are having issues with AzCopy v6 and hence it is very important for us to have good performance with v10 and /xo feature. Due to Windows patch constraint we would want this issue to be prioritized.

**Comment by JohnRusk** [comment]
@rpohane This is probably the most-requested thing that v8 can do but v10 doesn't yet support.

**Comment by jiteshkumargouthamchand** [comment]
Problem is v8 also has known issues due to which we cannot update further than v6. This was already reported and know issue with MS which is when they recommended to work on updating straight from v6 to v10. We had issues with both v7/8 AzCopy.

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand could you please elaborate slightly on what issues were encountered with v7/8?

**Comment by jiteshkumargouthamchand** [comment]
Issues with v7 was Performance which was big hit for our structure . With  AZCOPY 8.1 failure is the .net core proxy authentication. This was a known issue which was fixed in  10.x

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft  @Salomon.Henriquez@microsoft.com : Any updates on when the /xo feature will be available in v10.

**Comment by JohnRusk** [comment]
No update on that, sorry.

BTW, in regard to your earlier email, proxy _discovery_ is fixed in current releases of V10. But proxy _authentication_ is not.

**Comment by AriVillaca** [comment]
AzCopy v10 does not work for us due to proxy authentication not being available as of now. Are you going to add this feature to AzCopy? If you are, do you know when this feature will be available in AzCopy?

Below is the stack trace of a failedazcopy call:
2019/12/18 22:41:21 ==> REQUEST/RESPONSE (Try=1/217.009ms, OpTime=441.0249ms) -- REQUEST ERROR
   PUT https://myblobacct.blob.core.windows.net/mycontainer/myfile.csv?<...>&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [25fcb796-2bd2-4206-49ca-7a46260e5f10]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Put https://myblobacct.blob.core.windows.net/mycontainer/myfile.csv?<...>&timeout=901: **authenticationrequired**

goroutine 299 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc0002248a0, 0xc0103c1200, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x10, 0x1, 0x0, 0xc0113f6160)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:146 +0x7ac
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007b4e10, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0xc0113f6200, 0xc001a04fc8, 0xa, 0x2030004)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x64028f0, 0xc001a05050, 0x40c7c0, 0xc0010c2500)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:75 +0x1b8
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00009f760, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x10, 0x10, 0xaffee0, 0x30)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xcdfd40, 0xc00009f760, 0xc00020a960, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x0, 0x11af520, 0xc001a050b0, 0x4310d8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc000207bc0, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x0, 0x0, 0x0, 0xc001a051d0)
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000207bd0, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0xc0010802a0, 0xc00cb3a250, 0x1, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x10, 0xab2660, 0x64492d747301, 0xc010bca420)
	/home/vsts/work/1/s/ste/xferRetrypolicy.go:382 +0x70f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007b4e60, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc010bca4f0, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x10, 0xab2660, 0x1be, 0xcca256)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00009f7a0, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc010bca4d8, 0x34, 0xc00001e400, 0xc001a05598)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x1, 0x0, 0x1, 0xc000212368)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc001058d50, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc001058d50, 0xc001a05668, 0x4143e3, 0xc00020a968)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000024980, 0xcee020, 0xc000024c80, 0xcdfe00, 0xc00020a960, 0xc010bc8000, 0x25, 0xc0010e662d, 0x4f, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlock(0xc0010e6600, 0x5, 0x0, 0x0, 0x0, 0xc0010e6608, 0x25, 0xc0010e662d, 0x4f, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zz_generated_block_blob.go:260 +0x4c0
github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlock(0xc0010e6600, 0x5, 0x0, 0x0, 0x0, 0xc0010e6608, 0x25, 0xc0010e662d, 0x4f, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/url_block_blob.go:79 +0x17b
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobUploader).generatePutBlock.func1()
	/home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:77 +0x37e
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x7f)
	/home/vsts/work/1/s/ste/sender.go:165 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc00006c000, 0x7f)
	/home/vsts/work/1/s/ste/JobsAdmin.go:427 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
	/home/vsts/work/1/s/ste/JobsAdmin.go:356 +0x682

**Comment by JohnRusk** [comment]
Yes, this should be a new issue.  We don't pre-accounce dates for features, sorry.

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, I'm working on a [PR](https://github.com/Azure/azure-storage-azcopy/pull/836) to resolve this issue.

Question: if source and destination last-modified times are equal, should the file be transferred? Do you have a preference?

**Comment by jiteshkumargouthamchand** [comment]
No it does not copy with /xo . Like wise we do not need to copy. Again filestamp on server might be iN CT whereas upload time in Blob will be in UTC so I am sure you will consider handling it like the way it is handled in /xo.

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand thanks, and yes time zone is taken into account.

**Comment by JohnRusk** [comment]
This feature is now released in version 10.3.4 https://github.com/Azure/azure-storage-azcopy/releases/tag/10.3.4
