### ISSUE TITLE
azcopy can't copy file or folder named as 'con' or 'con1'

### ISSUE THREAD

**Issue by jackchenquest** [Azure/azure-storage-azcopy#580]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Centos 7.5

### What command did you run?
azcopy copy con "https://saname.file.core.windows.net/sharename/foldername/?$SAS"

### What problem was encountered?
INFO: Scanning...

Job 57091685-9399-9e44-7585-36b05e258936 has started
Log file is located at: /home/atlas/.azcopy/57091685-9399-9e44-7585-36b05e258936.log

0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,

Job 57091685-9399-9e44-7585-36b05e258936 summary
Elapsed Time (Minutes): 0.0334
Total Number Of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

### How can we reproduce the problem in the simplest way?
create a text file, name it as 'con', then copy it to a Azure Files with "azcopy copy"

### Have you found a mitigation/solution?
rename the file as con2 .

**Comment by JohnRusk** [comment]
Hi @jackchenquest.  It looks like this is not a limitation of AzCopy, but a limitation of the Azure Files service.  This page here documents a number of filenames that are not allowed: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata

I'm a little puzzled about why it didn't let you use CON1, since only CON (not CON1) is on the list of banned file names. Are you sure that CON1 failed?

BTW, you can reproduce the issue with "CON", and the other banned filenames, outside of AzCopy. E.g. try to rename an Azure Files file to "CON" in Storage Explorer.

**Comment by jackchenquest** [comment]
Yes I retested and CON1/con1 is fine, probably something else caused it in previous test.
