### ISSUE TITLE
Feature request: azcopy jobs kill

### ISSUE THREAD

**Issue by wahalulu** [Azure/azure-storage-azcopy#609]
I have been trying to copy a set of files from a public Azure blob to local filesystem using azcopy. I've hit ctrl-c but it seems that the azcopy jobs still exist, a few being in progress. I would like to see a way to kill a job in progress.

##### Note: The version is visible when running AzCopy without any argument
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

**Comment by zezha-msft** [comment]
Hi @wahalulu, we've added the "jobs rm" command and will ship it soon.

**Comment by JohnRusk** [comment]
In the meantime, if you've killed the process by CTRL-C, the job will not be running.  It's definition just still exists on disk, marked as InProgress since that was the last saved status before you killed the process.  Job definitions on disk like that can be resumed with the existing resume command, or (in the upcoming 10.3 release) you can remove their definition (aka plan) files from disk using the command that Ze mentions.

**Comment by JohnRusk** [comment]
Version 10.3 is now released, with the jobs rm command as listed above.  To use, terminate the running job with CTRL-C, then use "jobs rm" if you want to clean up the plan (job definition) files that it left behind.
