### ISSUE TITLE
azcopy 10.2.1

### ISSUE THREAD

**Issue by nareshynn** [Azure/azure-storage-azcopy#611]
### Which version of the AzCopy was used? 
10.2.1
### Have you found a mitigation/solution?

i am trying to copy files from local file system to ADLS 2 and when every i am using azcopy cp it's copying all the files from that location. we need to copy only latest files from source to destination. while i am giving --preserve-last-modified-time syntax it showing destination location must be file system.

**Comment by JohnRusk** [comment]
Hi @nareshynn, I have bad news, I'm sorry. The behavior you are looking for is represented by the "sync" command in AzCopy, not by the "cp" (copy command)…. but unfortunately sync is not implemented for ADLS gen 2. 

Question: what type of changes happen in your source file system: just addition of brand new files, or  are existing files updated sometimes?

**Comment by nareshynn** [comment]
Brand new Files. may be every hour new files will be generated in source location. i have to move to ADLS2. if powershell script is available please let me know.

**Comment by JohnRusk** [comment]
If its only brand new files, and if there are NO changes to existing files, then the following approach is safe:

use a command like this:
azcopy cp <source> <destination> --overwrite=false

That will look at all the files in the source, but it will only copy those that don't already exist at the destination. It only checks file existence, not modification dates, which is why its only safe if there are no changes to your existing (already transferred) files.

Will that do?  It will probably perform better than any other options (e.g. something in PowerShell)

**Comment by nareshynn** [comment]
is it possible to provide sample power shell script using last modified date please.

azcopy cp --overwrite=false-- this works fine as of now.

**Comment by JohnRusk** [comment]
Glad hear overwrite=false is working for you.  As for a powershell script using last modified date, that's probably outside the scope of the support that we can provide here, I'm sorry.  The reason is that AzCopy v10's copy command doesn't currently have any support for using last modified date like that... so any powershell script would have to use some other technology (that's not AzCopy).  I don't know what that would be.

BTW, in the long term, [interop ](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access) between ADLGS Gen 2 and Blob Storage will go GA. At that point, it should work to simply use AzCopy's existing blob sync to sync to your _ADLS Gen 2_ account through its _blob_ endpoint.  I.e. once interop is GA, the existing azcopy sync function will become useable on ADLS Gen 2, and I believe it will meet your needs.  BTW This is why we have not written sync support specifically for ADLS Gen 2. 

Until interop goes GA, copy with overwrite=false seems like the best option in your particular case.
