### ISSUE TITLE
Linux AZCOPY_LOG_LOCATION Variable Not Working

### ISSUE THREAD

**Issue by ek1977** [Azure/azure-storage-azcopy#662]
### Which version of the AzCopy was used? 
RHEL Linux 7.x, AzCopy 10.2.1
### What command did you run?
 export AZCOPY_LOG_LOCATION=/vol01/data/stage-backup/azcopy-logs

### What problem was encountered?
When I update the environmental variable it shows the updated path when I run "azcopy env" but when I do a "sudo azcopy cp ..." command the log file always goes to the root home folder. 
(e.g. /root/.azcopy/ea0c2353-e692-ff4e-5120XXXXXXXXX.log).  I have not been able to get azcopy to use the values set in the AZCOPY_LOG_LOCATION environmental variable.  

### How can we reproduce the problem in the simplest way?
Set the environmental variable on Linux and then note the location of the log after executing an azcopy cp command.

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
Hmm, we'll have to see if we can reproduce that here on the project team. I've tagged it to remind us to do that.

**Comment by adreed-msft** [comment]
This seems to work on 10.3.0 in my case (WSL2, Arch Linux). Could you retest on 10.3.0?

**Comment by thisiscmt** [comment]
Not sure if it's related but I have a similar problem setting the log and plan location env variables. I have v10.3.0 on Windows 10. I can open a command prompt and run the following:

set AZCOPY_LOG_LOCATION=C:\some-path-no-spaces\logs && set AZCOPY_JOB_PLAN_LOCATION=C:\some-path-no-spaces\logs\plans

That succeeds and running azcopy env shows those are the paths it will use. It also creates those directories. When I try to run azcopy to copy something, I get this:

azcopy copy "C:\some-path-no-spaces\extracted-packages\1ae27318-9f64-4cac-852e-c3baae948d3e\*" "http://127.0.0.1:10000/devstoreaccount1/extracted/1ae27318-9f64-4cac-852e-c3baae948d3e?sv=2019-02-02&st=2019-10-18T17%3A13%3A22Z&se=2019-10-18T18%3A13%3A22Z&sr=c&sp=rw&sig=xxxxxx" --recursive --from-to=LocalBlob --follow-symlinks --log-level ERROR --output-type=json
{"TimeStamp":"2019-10-18T11:39:09.1686505-07:00","MessageType":"Info","MessageContent":"INFO: Scanning...","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
{"TimeStamp":"2019-10-18T11:39:09.1696494-07:00","MessageType":"Info","MessageContent":"INFO: NOTE: HTTP is in use for one or more location(s). The use of HTTP is not recommended due to security concerns.","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
panic: open C:\some-path-no-spaces\logs /7dd04084-e7af-7b4c-41f9-45791c4048c9.log: The system cannot find the path specified.

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
        /home/vsts/work/1/s/common/lifecyleMgr.go:420
github.com/Azure/azure-storage-azcopy/common.(*jobLogger).OpenLog(0xc0007c60c0)
        /home/vsts/work/1/s/common/logger.go:138 +0x4cd
github.com/Azure/azure-storage-azcopy/ste.(*jobMgr).reset(0xc000c0b180, 0xcd3d60, 0xc0000f2180, 0xc0007ce000, 0x171, 0x2b, 0x0)
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:108 +0x3f
github.com/Azure/azure-storage-azcopy/ste.newJobMgr(0x80, 0xc0000f3fb0, 0xc000200000, 0x80, 0x7ffffe46, 0xc000200030, 0x5ac2880, 0xc000066400, 0x7b4ce7af7dd04084, 0xc948401c7945f941, ...)
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:98 +0x43a
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).JobMgrEnsureExists.func1(0xac0ae0, 0xc0000846c0)
        /home/vsts/work/1/s/ste/JobsAdmin.go:565 +0x185
github.com/Azure/azure-storage-azcopy/ste.(*jobIDToJobMgr).EnsureExists(0xc0000b4200, 0x7b4ce7af7dd04084, 0xc948401c7945f941, 0xc0008efcf0, 0x7b4ce7af7dd04084, 0xc948401c7945f941)
        /home/vsts/work/1/s/ste/JobsAdmin.go:790 +0xd7
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).JobMgrEnsureExists(0xc0000b41a0, 0x7b4ce7af7dd04084, 0xc948401c7945f941, 0x7945f9417b4ce703, 0xc0007ce000, 0x171, 0x0, 0x0)
        /home/vsts/work/1/s/ste/JobsAdmin.go:562 +0xb2
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0x7dd0408400000000, 0x7945f9417b4ce7af, 0xc948401c, 0x10300000001, 0x0, 0x0, 0x0, 0xc0007c25b0, 0x61, 0xc00005a7e0, ...)
        /home/vsts/work/1/s/ste/init.go:143 +0xfc
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xb994b3, 0x10, 0xa83800, 0xc00009af00, 0xa83840, 0xc000b56a40, 0x1, 0xc000b56a40)
        /home/vsts/work/1/s/cmd/rpc.go:44 +0x908
github.com/Azure/azure-storage-azcopy/cmd.glob..func4(0xb994b3, 0x10, 0xa83800, 0xc00009af00, 0xa83840, 0xc000b56a40)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x64
github.com/Azure/azure-storage-azcopy/cmd.dispatchFinalPart(0xc00009af00, 0xc0003e8380, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorHelper.go:63 +0xd1
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).initEnumerator.func6(0xc0007b41e0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorInit.go:251 +0x3a
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc0007e4140, 0x7dd0408400000000, 0x7945f9417b4ce7af)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:508 +0x9f
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc0003e8380, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:946 +0x6f6
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc0003e8380, 0x171, 0xb)
        /home/vsts/work/1/s/cmd/copy.go:733 +0x91
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001d7680, 0xc0000a4580, 0x2, 0x8)
        /home/vsts/work/1/s/cmd/copy.go:1312 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc0001d7680, 0xc0000a4480, 0x8, 0x8, 0xc0001d7680, 0xc0000a4480)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0x11fe1e0, 0xc0000f63f0, 0xc00014be00, 0x40c8ef)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c7
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc00006ef80, 0x16, 0xc000096330, 0x2b, 0xc000082880, 0x30, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:92 +0xd7
main.main()
        /home/vsts/work/1/s/main.go:82 +0x3c5

It blows up trying to create 7dd04084-e7af-7b4c-41f9-45791c4048c9.log. It's not clear from the error which path it's trying to use. Does the code that tries to create the log file attempt a mkdir first? If so, is that code OS-aware enough?

**Comment by zezha-msft** [comment]
@thisiscmt It looks like there's an extra space that got inserted from the error message:

panic: open C:\some-path-no-spaces\logs /7dd04084-e7af-7b4c-41f9-45791c4048c9.log: The system cannot find the path specified.

The statement to set the environment variable seems to be the problem:
```
set AZCOPY_LOG_LOCATION=C:\some-path-no-spaces\logs && set AZCOPY_JOB_PLAN_LOCATION=C:\some-path-no-spaces\logs\plans
```

If I remove the &&, and put the statements on separate lines, it works fine.

**Comment by zezha-msft** [comment]
@ek1977 is there a reason why `sudo` was used to invoke azcopy? IIRC the environment variables of the user is not shared with sudo.
