### ISSUE TITLE
Improve cleanup of log files

### ISSUE THREAD

**Issue by JohnRusk** [Azure/azure-storage-azcopy#693]
Consider ways to automatically clean up log (and plan) files, without compromising supportability. (And bearing in mind that sometimes support is required for jobs in which AzCopy itself thinks it succeeded, and so would automatically delete the logs in a simple delete-on-success approach.  The prime example is performance-related support issues).

This issue is branched from #221

**Comment by jtmoree-kahalamgmt-com** [comment]
Since this is a new thread I'm going to summarize the situation.   

- AzCopy writes two types of files in order to do its work: log files and plan files
- The parameter --log-level NONE may be used to prevent logs from being written but plan files must always be written
- The location of the plan files may be moved by using AZCOPY_JOB_PLAN_LOCATION
- The location of the log files may be moved by using AZCOPY_LOG_LOCATION
- All log and plan files may be cleaned up by running azcopy a second time with the jobs clean parameter
- There is no azcopy feature that will clean up individual job files in the same process that writes them
- If the caller to azcopy wants to run jobs concurrently and needs the files to be cleaned up individually, she must parse output from each job and clean the files up with a separate process

**Comment by jtmoree-kahalamgmt-com** [comment]
> (And bearing in mind that sometimes support is required for jobs in which AzCopy itself thinks it succeeded, and so would automatically delete the logs in a simple delete-on-success approach. The prime example is performance-related support issues).

In performance related support issues the user would be running multiple times and could turn on the switch to keep files.  The rest of us can use the switch to clean up.  I don't care if azcopy defaults to keeping everything under the sun.   It should be a good citizen and clean up after itself--even if that has to be activated by the caller using a switch or environment variable or magic incantation.

There is no situation where the performance is bad just one time that would result in needing the logs.  If the performance is bad on one run but all subsequent runs are fine it is an outlier.  If the user has sporadic performance problems then they need to keep all logs until they figure it out by using appropriate switches (or the default).  The rest of us would really appreciate a clean up parameter so that we don't have to do extra work to pick up after azcopy.

**Comment by JohnRusk** [comment]
>If the caller to azcopy wants to run jobs concurrently and needs the files to be cleaned up individually, she must parse output from each job and clean the files up with a separate process

For completeness, if she wanted to get a bit fancy, should you set up separate environments for each instance, with different AZCOPY_JOB_PLAN_LOCATION and AZCOPY_LOG_LOCATION, which would in theory allow the use of azcopy jobs clean.  I'm not sure I'd necessarily advise that, because if you mess it up you'll end up deleting (or at least trying to delete) files belonging to another instance.  But it is theoretically possible.

Thanks for your summary here @jtmoree-kahalamgmt-com .  This issue is on our list to consider in prioritization of future work.  I can't guarantee any particular decision regarding timing.

**Comment by Jehoel** [comment]
Is there a reason `azcopy` creates a new file for each invocation instead of appending to an existing log-file? I wouldn't be complaining about clean-up if azcopy simply appended to a small number of files.

On a related subject, can you enable date-time prefixes in the generated files? That way I can use a glob to clean-up older files without having to inspect each log file's last-write-time value.

**Comment by JohnRusk** [comment]
Good question re one file or many. I worked on a previous tool that used a one-file approach, and it did have some downsides. (E.g. if customer wanted to send log to us for support, it was hard for us and them to find the right part).

We'll have to think about the prefix question. Thanks for asking it.

BTW, if really want date-based naming or similar, and you don't mind writing a little script, you can have a script that sets the environment variables AZCOPY_LOG_LOCATION and AZCOPY_JOB_PLAN_LOCATION to something date based (or unique in some other way) before each run of AzCopy.

**Comment by aersamkull** [comment]
I just had a server where AzCopy already create 30GB of logs in three months time... Seems to not be a very reasonable default. Keeping n Files per Default would be a lot more user friendly.

**Comment by marc-hb** [comment]
> Thanks for your summary here @jtmoree-kahalamgmt-com

Seconded! Thank you.


> I don't care if azcopy defaults to keeping everything under the sun. It should be a good citizen and clean up after itself

This.

A lot of other software has temporary files too. BUT they are left behind _only_ when something goes wrong; as soon as everything is completed fine then temporary files are automatically cleaned. Why doesn't `azcopy` let us have very simple, nice things that every other software provides?

This is especially true for binary "plans" that only `azcopy` itself can understand and re-use. Logs are more complicated because most users want to keep them for some about of time or some amount of disk space using `logrotate` or a similar approach, see earlier discussions in #221.

On the other hand, if the transfer went well  then why would any user want to preserve a "plan" and the ability to resume a transfer that was completed fine? That does not make any sense to me, what am I missing? Listing previous, successful jobs with `azcopy jobs list` should not require as much disk as if they all failed.


> The rest of us would really appreciate a clean up parameter so that we don't have to do extra work to pick up after azcopy. [...]
> even if that has to be activated by the caller using a switch or environment variable or magic incantation.

Exactly: changing default behavior is disruptive, we get it. But at the very least `azcopy` should have some `--behave-like-every-other-tools` options.

> Is there a reason azcopy creates a new file for each invocation instead of appending to an existing log-file?

Separate files is convenient for interactive use where multiple copies can be running at the same time. On the other hand it's mostly useless and painful for regular "cron" jobs, see earlier discussions in #221


> For completeness, if she wanted to get a bit fancy, she could set up separate environments [...] and you don't mind writing a little script, [...]

“Simple things should be simple, complex things should be possible.” Why require _every_ user to duplicate the same efforts to "setup environments" or "write little scripts" which is time-consuming and error prone for basic features that are usually built-in in other, similar software? Logging must be either `logrotate`-friendly or provide `logrotate` features built-in. It's really that simple. How come `azcopy` developers never experience this lack of log rotation themselves, are they never automating `azcopy` for anything? Do they use some other, Windows-specific log rotation tool that `azcopy` is more compatible with?

>  This issue is on our list to consider in prioritization of future work. I can't guarantee any particular decision regarding timing.

This was in October 2019. So this issue is not officially but practically in the "closed as wontfix" state?

**Comment by marc-hb** [comment]
So the main purpose of "plan" files seems to support resuming partially failed transfer with `azcopy jobs resume` https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure "Find errors and resume jobs by using log and plan files in AzCopy"

This looks like a great feature but if transfer "plans" are leveraging disk space one wonders why `azcopy sync` memory usage seems to grow really fast and _linearly_ with the number of files. In fact `azcopy sync` is simply running out of memory for large file sets (and hogging the entire system memory for smaller ones):
- #1215

Is there already an issue filed about this memory (ab)use and lack of scalability? #693 seems more focused on one particular detail.

**Comment by JohnRusk** [comment]
@marc-hb Sync does some in-memory processing which copy does not do, and that uses RAM. So in some cases, it's better to simply configure "copy" to have behaviour that is similar (but not identical) to "sync".  See https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#optimize-file-synchronization

BTW, I moved to a different team a couple of years ago, so I'm not actively involved in AzCopy now, but am responding here because I see that this is a thread which I started :-)

**Comment by igorpupkinable** [comment]
For anyone unfamiliar with the tool, but looking for a way to clean leftovers:
```
azcopy jobs list
azcopy jobs clean
```

**Comment by peter-bertok** [comment]
I've just wasted an hour of my life chasing this through issue ticked after issue ticket, and my general impression that "version 10" of azcopy is not suitable for production usage. Several of its developers made comments that the requirements of the users is much less important than the convenience of azcopy developers being able to track down bugs via collecting always-on log files.

Filling up customer system disks with files nobody asked for is not how production-ready software is written.

On Windows the *standard* is to write to the Event Log, which is a fixed-sized circular buffer and won't fill the disk.

On Linux the *standard* is for CLI utilities to output *nothing on success*, and have no side effects other than what is explicitly configured.

For PowerShell and similar advanced CLIs, the *standard* is to enable background/resumable jobs ONLY if explicitly prompted by users. E.g.: how can "azcopy" *securely* store the configuration parameters for resumable jobs!? Either it throws the SAS token away which makes the job not really resumable, or it is leaving **secrets** on disks where the end-user is not expecting this!

It has been 4+ years of many users patiently explaining to the azcopy team that they're not writing a toy utility for their own personal use.

Please just do what has been asked: Logging should be off by default, leave an *option* to enable it, and don't waste time with silly half-measures like "--log-level NONE" not actually disablings logs!

**Comment by vibhansa-msft** [comment]
There are commands to cleanup and wipe out older job files. These files are kept by default (untill cleared by user manually) so that at any moment user can go back and check the status of a given job to identify if any of the job failed and what all files were not copied successfully. User can resume the job as well to continue with whatever failed last time. If you think job is done and there is no need to keep the status now then using job cleanup command you can delete these files.

**Comment by daiplusplus** [comment]
@vibhansa-msft this issue should not have been closed as "completed" (if so, where's the PR?) - whereas a more _honest_ action would be "closed as wontfix".

...but _a better_ response would be to re-open this issue with an admission that _unchecked logfile build-up without even the option for automatic cleanup_ is not a hallmark of good-quality software that meets its users' needs.

...at the very least, shouldn't a first-party Microsoft title be [a good citizen on its own platform by integrating with Windows' Disk Cleanup utility](https://learn.microsoft.com/en-us/windows/win32/lwef/disk-cleanup)?
