### ISSUE TITLE
Override Pending Copy Operation?

### ISSUE THREAD

**Issue by HELAdramalech** [Azure/azure-storage-azcopy#697]
Using AzCopy v10, I'm receiving:

409 : 409 There is currently a pending copy operation.. When Uploading blob. X-Ms-Request-Id:

After a system client crash, I'm nolonger able to migrate some important files, they are associated with database hooks in a very large container.  Is there a way of releasing the blockage?

**Comment by adreed-msft** [comment]
https://docs.microsoft.com/en-us/rest/api/storageservices/abort-copy-blob

You'll need to manually call this on the blobs that have pending copy operations. AzCopy currently doesn't try to do anything about blobs in this disposition.

**Comment by adreed-msft** [comment]
If you _don't_ have the copy ID, you may have to upload to a different blob name or location.

**Comment by HELAdramalech** [comment]
Thanks for the feedback.  I've managed to grab the copy operation using wget -S --spider and of course az storage blob show. 

Haven't had much luck cancelling the operation yet.

**Comment by JohnRusk** [comment]
To do the cancel ,I would imagine that you could use an approach similar to what I suggested above with wget.  But in this case, the method would be PUT, the URL would be constructed as descibed in the page that @adreed-msft shared above, and you need to set a number of headers - namely the mandatory headers documented in that page.

End your URL with a SAS token since that's the easiest way to authenticate. (And I _think_ you can omit the Authorizationheader if you do that).  So you'll only need the Date and x-ms-copy-action: abort headers.

 This page shows how to set headers in powershell: https://stackoverflow.com/questions/12936150/is-it-possible-to-send-additional-http-headers-to-web-services-via-new-webservic

**Comment by JohnRusk** [comment]
Closing since there's no change needed to AzCopy itself.
