### ISSUE TITLE
AZCopy Resume Related question

### ISSUE THREAD

**Issue by veeraps** [Azure/azure-storage-azcopy#720]
### Which version of the AzCopy was used? 
Azcopy v10.3.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy login --tenant-id <>
azcopy cp source-file-name dest-file-name 
azcopy jobs resume <jobid>

### What problem was encountered?
I am trying to upload a 650GB file from my laptop to azure storage account. Using my home internet (200mbps connection). When I ran the copy command, it failed after 3.5 hours. Again I resumed, ran for 2 hours. I kept resuming for 8 times for about 2.5 days. While this was running, we were not able to use other devices. It was all too slow. After second day, I changed the number of cores to be used by AZCopy to 6 in env variables. Then home internet was usable for other purposes. After 2.5 days, resume started running without any failures for another 2.5 days. While I was trying something in Azure for some other configuration, I had to change my password for AD login. It stopped Azcopy after 71.5%. Again, I resumed, it is now still running since morning showing 12.5%. Can I assume that file copy is 84% complete? Is this normal behavior?

**Comment by zezha-msft** [comment]
Hi @veeraps, sorry for the inconvenience, AzCopy does not perform any chunk level retries, so every time you resume, the file is re-uploaded from the beginning.

The network bandwidth is definitely a bit small for the file size, at uninterrupted full speed, it takes:
![image](https://user-images.githubusercontent.com/26559128/67993066-7385f500-fbfc-11e9-807b-0d5788df0c24.png)

But in reality, network providers tend to throttle its users.

I'd suggest to let the current run continue, if it fails again, maybe try from a faster network.

**Comment by JohnRusk** [comment]
And, just for completeness, you did the right thing in reducing AZCOPY_CONCURRENCY_VALUE.  For convenience, it can also be set to "AUTO"  - which tells AzCopy to start at 4 connections and seek the optimal number.  In our testing, that avoids the problem you had of it overloading the network with too many connections.

**Comment by veeraps** [comment]
Oh no, I have to wait for another 3-4 days for this to complete. 

Can I switch to Azure Data Box Gateway (online)? Will it be faster?

**Comment by JohnRusk** [comment]
Very sorry about the inconvenience.  

As far as I know, Data Box Gateway wouldn't help here, since the constraint is the time taken to move the data over the 200 Mbps network.  If, for instance, the laptop is a work laptop and you have access to an office network that runs at, say 1 Gbps, then maybe physically relocating the laptop onto that network would help.  Or, if your home internet provider allows opt-in dynamic reconfiguring of speed (as mine does) I guess you could temporarily buy faster speed from them (and you _probably_ wouldn't have to stop and restart the existing job).  Those are the best ideas I can think of at the moment, sorry.

**Comment by veeraps** [comment]
Thanks for your idea. I could finish copying the 650GB file in 31 hours (upload speed is about 40 mbps).
