### ISSUE TITLE
Feature request: use azcopy as go library

### ISSUE THREAD

**Issue by howie** [Azure/azure-storage-azcopy#722]
Can you provider some tutorial about how to import azcopy as go library?
I want to leverage azcopy's implementation to let my go application can copy file more efficiently.

**Comment by JohnRusk** [comment]
Hi Howie.  Importing as a Go library is actually not a scenario that we've targeted, I'm sorry. We've been focused on a different integration scenario instead, which is to invoke the Go executable.  If you pass `--output-type json`  it sends you back JSON-formatted output on its stdout, which is easier to deal with programatically.  We've focussed on this scenario because it's cross-language.  For instance, Storage Explorer uses this approach.

Would it be _possible_ to invoke it as a library? Maybe, but there are some important unknowns, and so I wouldn't recommend it at this stage.

I'll make this issue as a feature request.  Sorry we don't have a supported solution right now.
