### ISSUE TITLE
How to pass input parameters to Azcopy .exe command in ADF V2 custom activity 

### ISSUE THREAD

**Issue by kyrmca** [Azure/azure-storage-azcopy#764]

**Comment by kyrmca** [comment]
i am trying to Run Azcopy in ADF V2 custom activity command ,but it's not working .
ADF Command : Azcopy.exe copy @pipeline().parameters.Source @pipeline().parameters.Dest
May i know how to pass dynamic source and destination path though the ADF pipeline parameters or Varaibles using Azcopy?

**Comment by JohnRusk** [comment]
Running AzCopy in Azure Data Factory is not a scenario that we've looked at.  Generally we expect data movement customers to use AzCopy OR ADF, but not both.  (However, we'd be interested to hear your reasons for combining the two tools).

I don't know the answer to your actual question I'm sorry.  It sounds like a question for ADF support, not AzCopy support.  There should be no difficulty from the AzCopy side, since its just a command line executable.  The question seems to be about how to pass the parameters from the ADF side. So if I'd suggest you raise it though whichever channel you normally use to get ADF support (if you want to continue to combine the two tools).

**Comment by kyrmca** [comment]
i have done this requirement using Append variable activity and building azcopy command dynamically and this variable i am using in ADF v2 custom activity command.

**Comment by JohnRusk** [comment]
Thanks for the info @kyrmca.  Unfortunately, we on the AzCopy team don't know enough about ADF to help you any more on this.   I think your best option is to go ahead and raise the issue as an ADF support issue. (Or else get ADF to move the data without using AzCopy at all.  As I mentioned above, combining the two tools is not something that we plan for or test).

**Comment by kyrmca** [comment]
Thank you @JohnRusk .
