### ISSUE TITLE
Bypass the system default proxy on Windows

### ISSUE THREAD

**Issue by andym102** [Azure/azure-storage-azcopy#766]
### Which version of the AzCopy was used? 
10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp D:\LocalFolder\* https://<storageaccount>.blob.core.windows.net/blobcontainer/<SAS> --recursive=true --overwrite=false

### What problem was encountered?
Unable to bypass the system default browser proxy when running azcopy in a script.  

The source machine is an Azure VM and the destination is a storage account in the same region but the VM has the browser proxy forced to use an on-prem server which is ok for browser traffic but we don't want the azcopy traffic going via the on-prem proxy.  

We would like a command line option to make azcopy ignore the system HTTP proxy server and attempt direct communication with the blob storage.  

### How can we reproduce the problem in the simplest way?
Setup a local squid (or other) proxy server on the local VM and set it as the system default proxy server where 'Automatically detect settings' is disabled and 'Manual Proxy Setup' is configured to use the local proxy server.  Any Azcopy command will then use the proxy by default and there is no way to bypass it at a script/command level.  

### Have you found a mitigation/solution?
No.  The on-prem proxy server cannot handle the large amount of data being transferred by azcopy and so many transfer failures are being caused by the proxy dropping the connection before the blobs can be transferred.

**Comment by JohnRusk** [comment]
I think you can trick AzCopy into using no proxy as follows.  Set these environment variables, in the environment where AzCopy will run:

HTTP_PROXY="http://proxy.invalid"
NO_PROXY="*"

The PowerShell syntax to set these looks like this:
```
$env:HTTP_PROXY="http://proxy.invalid"
$env:NO_PROXY="*"
```

The key is the NO_PROXY setting, which says to use no proxy for _everything_.
The actual value of HTTP_PROXY doesn't matter, but because of the way AzCopy currently works, it has to be _present_, just to make it look at the NO_PROXY setting.  (I just used a .invalid URL here because that TLD is guaranteed to never resolve to anything in DNS - but it probably doesn't matter what you put in there as long is it can be _parsed_ as a URL)

I'll add something to our backlog to one day make it be enough to just set NO_PROXY.

Please let us know how this goes for you.

**Comment by andym102** [comment]
Thanks very much for the quick response John!  Setting the NO_PROXY env value fixes it for me.  I had tried setting HTTP_PROXY to various values but in conjunction with NO_PROXY it works.  
Btw I found that the above Powershell syntax for setting the env values in the script work fine but to set the values as system environment variables for use by command prompt or in a .cmd script I had to remove the quotes around the values (on Windows 2016)

A NO_PROXY command line option in future would be much easier if it could avoid these platform/environment differences, in the meantime perhaps add mention of the the NO_PROXY option to the user docs?
Thanks again

**Comment by JohnRusk** [comment]
Thanks for confirming it worked.  
BTW, I'm leaning toward updating the public docs only after we remove the need to put a dummy value into HTTP_PROXY.  That way, we can just document a clean and simple solution.  We have that work on our backlog, but it's probably at least a few months away. 
cc @normesta
