### ISSUE TITLE
Linux azcopy 7.3.0-netcore hangs on azure hosted agent for Azure DevOps pipeline

### ISSUE THREAD

**Issue by TamasSzerb** [Azure/azure-storage-azcopy#769]
Hello,

In Azure DevOps a scrip hangs when calling azcopy 7.3.0-netcore (this is shipped with ubuntu-latest vmImage).

1) Please update to newer azcopy
2) Please fix the issue in DevOps

Thanks,

Tamas

**Comment by JohnRusk** [comment]
Thanks for noting this issue.  This is not the right place to log a DevOps issue, I'm sorry.  Before I can help you find the right place, can I check please, is your version of AzCopy shipping with DevOps or with Ubuntu?

**Comment by JohnRusk** [comment]
If it's a DevOps issue, it looks like the best place is "report a bug" here: https://azure.microsoft.com/en-au/support/devops/ 

I propose to close this now, because its not an AzCopy v10 bug.  But please do comment below if you have any further questions, or comments, or clarification on whether its a DevOps problem or an Ubuntu image problem.

Finally, AzCopy V10 is just a single executable (no DLLs). That makes it easy to deploy so I guess (I don't know) that there might be a way to get it going yourself in devOps, without waiting for any official upgrade.  I don't know enough about DevOps to know what would be involved in running your own custom exe like that.
