### ISSUE TITLE
if the file exist download from source otherwise skip using Azcopy V10.3.2

### ISSUE THREAD

**Issue by kyrmca** [Azure/azure-storage-azcopy#770]
### Which version of the AzCopy was used? 
AzCopy 10.3.2
### Which platform are you using? (ex: Windows, Mac, Linux) 
 Windows

### What command did you run?

azcopy copy ''C:\myDirectory\test\myTextFile.txt'' ''https://mystorageaccount.file.core.windows.net/mydir/myTextFile.txt?sv=2018-03-28&ss=bjqt&srs=sco&sp=rjklhjup&se=2019-05-10T04:37:48Z&st=2019-05-09T20:37:48Z&spr=https&sig=REDACTED'' 
### What problem was encountered?
Error: failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\C:\myDirectory\test\myTextFile.txt, please verify that it is a valid.

**Comment by JohnRusk** [comment]
In this case, the file does not exist. Right?  And you'd like AzCopy to just skip it without an error?

AzCopy will do that if the source is a directory - i.e. it will transfer all files in the directory, and not worry about any files that are not there.  But, if you give it the path to one specific file on the command line, as you have done here, then it will show the error if the file does not exist.  It does that because you asked it to do something, and it can't do what you asked. We will not be changing that behavior in AzCopy.  But you can wrap your usage of AzCopy in a script, e.g. PowerShell, to test to see if the source file exists, and only call AzCopy if it does exist.

**Comment by kyrmca** [comment]
Thank you @JohnRusk . i have basic knowledge on PowerShell and Azcopy. 
if you have any sample code for combining PowerShell and Azcopy script, could you please share to me.

**Comment by JohnRusk** [comment]
Sorry kyrmca. I don't have any relevant examples, sorry.

**Comment by kyrmca** [comment]
its's okay np @JohnRusk,  Thank you so much .
