### ISSUE TITLE
Copying from file share is much slower than from blob container

### ISSUE THREAD

**Issue by HughKu** [Azure/azure-storage-azcopy#779]
Hi all, is there any reason as to why copying to local storage from `file share` is much slower than from `blob container`? Thanks.
### Which version of the AzCopy was used? 
v10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
The sample data contains around 1000 images of total size 1GB.
```sh
# copy from blob container
azcopy copy "https://{storage_account}.blob.core.windows.net/sample?{sas_token}" "{path_to_local_storage}" --recursive

# copy from file share
azcopy copy "https://{storage_account}.file.core.windows.net/sample?{sas_token}" "{path_to_local_storage}" --recursive
```
### What problem was encountered?
Downloading from `file share` is much slower than from `blob container`.

```sh
# logs from `copy from blob container`
INFO: Scanning...

Job 47ad5f16-5726-ec41-7ba1-ee58cd80eaa7 has started
Log file is located at: /home/linker/.azcopy/47ad5f16-5726-ec41-7ba1-ee58cd80eaa7.log

99.9 %, 1057 Done, 0 Failed, 1 Pending, 0 Skipped, 1058 Total, 2-sec Throughput (Mb/s): 4550.4094


Job 47ad5f16-5726-ec41-7ba1-ee58cd80eaa7 summary
Elapsed Time (Minutes): 0.0667
Total Number Of Transfers: 1058
Number of Transfers Completed: 1058
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 1138849930
Final Job Status: Completed

# logs from `copy from file share`
INFO: Scanning...

Job 5aaf62a9-4532-2b41-778a-775e14be347d has started
Log file is located at: /home/xxxx/.azcopy/5aaf62a9-4532-2b41-778a-775e14be347d.log

99.2 %, 1050 Done, 0 Failed, 8 Pending, 0 Skipped, 1058 Total, 2-sec Throughput (Mb/s): 173.0721  

Job 5aaf62a9-4532-2b41-778a-775e14be347d summary
Elapsed Time (Minutes): 0.1
Total Number Of Transfers: 1058
Number of Transfers Completed: 1058
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 1138849930
Final Job Status: Completed
```

### How can we reproduce the problem in the simplest way?
1. Make a copy of the sampled data into both blob container and file share
2. Execute the corresponding copy command using azCopy

### Have you found a mitigation/solution?
None

**Comment by JohnRusk** [comment]
The difference is normal and to be expected. 

For block blobs, the target max throughput is the account egress limit.  For Azure files, the max throughput per share is much less than the account egress limit.  See here for details: https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets

Note that in your case, your jobs of of relatively short duration. The short duration limits the throughput, because the very start and very end of a transfer job are naturally less efficient that the middle. At the start, there are requests being made but no responses yet; and at the end there are the last slowest responses coming in, but nothing else happening.  So in your case throughput is being partially limited just by the short job duration, but additionally limited (I think) by the lower max throughput of Azure Files, compared to Blob Storage.

If you need faster Azure Files, you can look at Premium Azure Files, which is faster... but not the same price.
