### ISSUE TITLE
AzCopy failing in on premise virtual machine but working  on local system

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#784]
##### Note: The version is visible when running AzCopy without any argument
Azcopy 10.2.1 i also tried 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "U:\directorycontents.csv" "https://usldevstorage.blob.core.windows.net/bpglobe?[sastoken]"

### What problem was encountered?
The same command is working from local system but not from a  on premise server.
I have even tried setting the below in environment variable as suggested by @JohnRusk, but didnt worked.
HTTP_PROXY="http://proxy.invalid"
NO_PROXY="*"

I also wanted to know what if i am tranfering 1000k of files and 100k fails how to resend the failed files again?
Transfer failed. Please find the error message from the log file.
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Put https://usldevstorage.blob.core.windows.net/bpglobe/directorycontents.csv?blockid=ZTVhN2JmN2EtYTk4Mi1l....
.....
.....
....
.
2019/12/10 12:58:35 ==> REQUEST/RESPONSE (Try=2/21.0012107s[SLOW >3s], OpTime=43.1634929s) -- REQUEST ERROR
   PUT https://usldevstorage.blob.core.windows.net/bpglobe/directorycontents.csv?blockid=nwq1ntyzytytndjhos0wytrjlty1n2ytnjjhnwe5ogi1zgrh&comp=block&se=2019-12-20t23%3A00%3A00z&sig=-REDACTED-&sp=racwdl&sr=c&st=2019-12-05t01%3A00%3A00z&sv=2019-02-02&timeout=901

### How can we reproduce the problem in the simplest way?
run the below command:
azcopy copy "U:\directorycontents.csv" "https://usldevstorage.blob.core.windows.net/bpglobe?[sastoken]"
### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
@qudiransari there should be a bit more info in the log, immediately after the REQUEST ERROR that you included. There should be an actual error message.  We will need that in order to offer any help on this issue.

 But at a guess, I would say that either
(a) You have a proxy server that requires authentication (proxy authentication with Kerberos and NTLM is not yet supported in AzCopy v10) or
(b)  You have some other network routing issue that prevents you reaching Storage from on premises.

**Comment by JohnRusk** [comment]
BTW, when you say it works on a local system, do you mean something that's on-premise, but not a VM?  In that case, my guess would be that your VM can't see the internet.

Finally, to answer your question about how to transfer only the failed files if something goes wrong, see https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-resume

**Comment by qudiransari** [comment]
> @qudiransari there should be a bit more info in the log, immediately after the REQUEST ERROR that you included. There should be an actual error message. We will need that in order to offer any help on this issue.
> 
> But at a guess, I would say that either
> (a) You have a proxy server that requires authentication (proxy authentication with Kerberos and NTLM is not yet supported in AzCopy v10) or
> (b) You have some other network routing issue that prevents you reaching Storage from on premises.

**Comment by qudiransari** [comment]
> @qudiransari there should be a bit more info in the log, immediately after the REQUEST ERROR that you included. There should be an actual error message. We will need that in order to offer any help on this issue.
> **Please find the logs after that:**
PUT https://usldevstorage.blob.core.windows.net/bpglobe/directorycontents.csv?blockid=nzq4nzjhndgtnwyyms05ndq5ltrlnmityzvmnwy3njhmnjc1&comp=block&se=2019-12-20t23%3A00%3A00z&sig=-REDACTED-&sp=racwdl&sr=c&st=2019-12-05t01%3A00%3A00z&sv=2019-02-02&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [e3dd698a-db51-4cf3-6751-7845e7a98541]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Put https://usldevstorage.blob.core.windows.net/bpglobe/directorycontents.csv?blockid=xxxxxxxxxxxxxxxxxxxxxx&comp=block&se=2019-12-20T23%3A00%3A00Z&sig=-REDACTED-&xxxxxxxxxxxxxxxxxx&timeout=901: dial tcp 52.239.248.228:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

goroutine 16 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc00007a900, 0xc000206800, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xcee0a0, 0xc00020a420, 0xc00010d100, 0x10, 0x1, 0x0, 0xc000126420)
	.................
...........
...........
...........

> But at a guess, I would say that either
> (a) You have a proxy server that requires authentication (proxy authentication with Kerberos and NTLM is not yet supported in AzCopy v10) or
Yes i am trying to access through on premise server which is proxy enabled but using that proxy i am able to open azure portal and access the storage in the same on premise server and also i have installed Azure storage explorer and i am able to access the storage with that also within the same on premise server.

> (b) You have some other network routing issue that prevents you reaching Storage from on premises.
From the error log its is confirm that there is some network issue which is preventing connecting the
**"connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."**

**Comment by qudiransari** [comment]
> BTW, when you say it works on a local system, do you mean something that's on-premise, but not a VM? In that case, my guess would be that your VM can't see the internet.
> **When i am saying local then i mean able to copy file from my desktop/laptop. But my requirement is to copy form a within a on premise server where lies the problem which i  have discussed in the above comments**
> Finally, to answer your question about how to transfer only the failed files if something goes wrong, see https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-resume

**Comment by JohnRusk** [comment]
Thanks for the answer to the question and the error message.  From the information you've supplied I can confirm that it appears to be that AzCopy cannot establish a network connection to Storage from the VM.  I suggest you run the following PowerShell command to test basic internet connectivity from the VM. (Note that you can use any public URL in this test, here I'm using the one that AzCopy pings to check whether its up to date)

```   [System.Net.WebRequest]::Create("http://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt").GetResponse().StatusCode
```
 
If you run that in PowerShell on the VM, one of the following two things should happen:
 
a.	It prints OK. This is the expected result if you run it on your desktop machine.  If it also prints OK on the VM, that suggest that we might have an AzCopy issue here. 
b.	It fails with an error, that includes the text “(407) Proxy Authentication Required”.  Note that this text will be buried inside a larger error message.  If this happens, it shows that the traffic is being directed through a proxy that requires authentication. The current version of AzCopy v10 doesn't work with those proxies.
c. It fails with some other error.  That probably suggests that the VM cannot reach the internet.  In this case, this is not an AzCopy issue but is a VM configuration issue (or possibly a configuration of the virtualized network adapters on the machine that hosts the VM). 

Please let us know what happens when you run the above on your local machine and on the VM.

**Comment by qudiransari** [comment]
Hi @JohnRusk,
Thanks for quick reply. I removed the below variables form the system variable list and it started working.
HTTP_PROXY="http://proxy.invalid"
NO_PROXY="*"

I would like to give a big thanks to you and your team who are constantly checking the post and issues and replying so quickly.
Hats off to you guys.

**Comment by JohnRusk** [comment]
Thanks :-)

**Comment by stellajoe** [comment]
Hi @JohnRusk,
I am having the same issue, ran the PowerShell command to test basic internet connectivity from the VM and got the following response : 

PS C:\Users\xxx> [System.Net.WebRequest]::Create("http://azcopyvnextrelease.blob.core.windows.net/releasemetadata/lates
t_version.txt").GetResponse().StatusCode

_Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
At line:1 char:130
+ [System.Net.WebRequest]::Create("http://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt")
.GetResponse <<<< ().StatusCode
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException_


Can you please advise?

Thanks,
Stella

**Comment by JohnRusk** [comment]
@stellajoe I've moved on to a different project, and so am no longer involved in AzCopy.  At first glance it looks like your VM is indeed unable to reach the internet.  If it is running in an environment that is managed by your IT department, you'll need to speak to them.  If that doesn't help, I'd suggest making a new AzCopy issue, instead of relying on folks to read this closed one.

**Comment by Vishva1995** [comment]
When I am performing copy operation using azcopy with sas key getting below error,
Please someone help me.

Error:
failed to perform copy command due to error: cannot start job due to error: could not list files. Failed with error -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed
