### ISSUE TITLE
Custom Headers for API Gateway

### ISSUE THREAD

**Issue by mikaelweave** [Azure/azure-storage-azcopy#785]
Hello!

I'm trying to use azcopy 10.3.2 with Apigee as an API gateway. Apigee requires a custom header of `x-my-api-key` to be populated to ensure the correct application is calling Azure Storage which needs to be protected due to PHI/PII concerns. 

What would be the best appraoch for adding a user defined header field to an azcopy command?

Thank you!
Mikael

**Comment by JohnRusk** [comment]
Does it need the header on all requests?

Also, does it need the header to be capitalized exactly as you show, or could it be something like `X-My-Api-Key`?  (AzCopy v10 is written in Go, and Go has some opinionated rules on capitalization of headers. Technically, according to the HTTP specs, Go is correct. But in practice some systems expect different behaviour).

**Comment by mikaelweave** [comment]
Yes, the header needs to be on all requests to the blob endpoint. The header is required for traffic to be forwarded. 

Capitalization isn't important to us. `X-My-Api-Key` would suffice as it's changable. Allowing any case could be more useful to other users who don't have this ability, but not necessary for my use case.

Thanks!

**Comment by JohnRusk** [comment]
Thanks for the info.  There's nothing in AzCopy right now that would do that.  Can you tell us a bit more about how urgently you need this, and whether you have any workarounds? That will help us with prioritization of the feature request. (BTW, you can email me directly if you'd prefer email to commenting here. My email address is in my profile page).

Finally, one question which it would be helpful to have answered here, in this issue thread: is the value of the key fixed?  And is it considered "secret" like a password? (Asking the latter question because we typically prefer not to have secrets on the command line).

**Comment by mikaelweave** [comment]
I'll email you more details about the priority of this specific use case, thank you! 👍 

In our use case, the value of the key is a secret. Ideally it would be best not to expose it over the command line. Great catch!

**Comment by mikaelweave** [comment]
@JohnRusk - any ideas if this feature will be making it into a future release?

**Comment by JohnRusk** [comment]
Following up offline.

**Comment by mikaelweave** [comment]
No longer needed
