### ISSUE TITLE
The file size exceeds the limit allowed and cannot be saved  error for SPO

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#816]
##### Note: The version is visible when running AzCopy without any argument
10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "l:\*" "xxxxxxxxxxxxxxxxxstorage+sastokenxxxxxxxxxxxxxxx" --r

### What problem was encountered?
I am trying to copy few files from a SharePoint Online doc lib to Azure Storage Account but few files are geting failed after multiple teries due to below size limit.I have seen files above 50 MB are causing issue / geting failed. But how come 50 MB size limit is an issue?
2020-01-02 15:03:26.465 +00:00 [Warning] (LJ0SD, Upload) Currently unable to read file xxxxxxxxxxxxxxx.pptx, retrying later. This line is NOT an error. Reason file can't be read right now is IOException The file size exceeds the limit allowed and cannot be saved.
@JohnRusk  Please help

### How can we reproduce the problem in the simplest way?
Executing the above command
### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
@qudiransari That error message doesn't look like an AzCopy error message. It is a Fast Data Transfer error message.  Can you please check what's going on at your end, then log a new issue here if you are now using AzCopy, or else contact me using the Fast Data Transfer Help email address if you are actually using Fast Data Transfer.   For now, I will close this issue, because this is the AzCopy issues list and that's not an AzCopy error message.
