### ISSUE TITLE
retain file/folder attribute using azcopy

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#838]
### Which version of the AzCopy was used? 
azcopy 10.3.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?
Can i retain file or folder attributes using azcopy?
### Have you found a mitigation/solution?
Not yet

**Comment by JohnRusk** [comment]
This feature is currently in development and scheduled for release in 10.4. The 10.4 work targets transfers to and from Azure Files.

To help us make sure that we cover all the cases we should, could you tell us a little more about what you're doing.  Is the source a local file system, or Azure Files?  What about the destination, what's that?

Also, what are the attributes that you want to preserve?

**Comment by jethrogalolo** [comment]
Source is a local file and destination is azure premium file share. We want to preserver the date and time of folder and files

**Comment by JohnRusk** [comment]
Thanks.  At this stage, preservation of _file_  creation and modification times is included in our plans for release 10.4, when the source is Windows local files and the destination is Azure Files (and also in the reverse direction). So that mostly covers what you are looking for.  Just one thing, for _folders_ , we plan to preserve only the creation date, and not the modification date.  That's because folder modification dates are not universally updated (e.g. Azure Files doesn't update them; Windows does, but not recursively upwards in the folder tree. Apparently it only does one level).

**Comment by lonevvolf** [comment]
Is there any chance to get the create/modification dates to also propagate to Blob Storage?

**Comment by JohnRusk** [comment]
Last time I checked, the blob API didn't support them directly.  But as you say, doing them as a metadata field would, in theory, work.  Any additional thoughts on how that ought to work?

**Comment by adreed-msft** [comment]
Hi there! 10.4 now supports the persistence of these attributes to azure files using --preserve-smb-info. Enjoy!
