### ISSUE TITLE
Simple copy not working - the inferred source/destination combination is currently not supported

### ISSUE THREAD

**Issue by epmck** [Azure/azure-storage-azcopy#839]
##### Note: The version is visible when running AzCopy without any argument
10.3.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy "C:\localdir\PDF_Images\" "https://storageaccount.blob.core.windows.net/image-container/" --recursive=true 
### What problem was encountered?
failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired
### How can we reproduce the problem in the simplest way?
I don't know ? It happens every time I try to copy a directory into a container.

### Have you found a mitigation/solution?
No

I can't figure this out. It looks so simple. I am trying to copy a directory with multiple directories inside with images in each one into a blob container. I login and that part goes fine, but then when I try to copy these files into a Blob container, it gives me the above error. What am I doing wrong? Is it a problem with having multiple directories inside it? Do I need to go create all of those directories in Azure Storage Explorer first? I assumed it would be able to create those for me at the time of copying. What else can I do?

**Comment by JohnRusk** [comment]
That should work.

Try it from Powershell if you're currently using CMD as your command prompt. (Powershell has fewer surprises with special characters etc).  And make sure you're using straight quotes " not slanted smart quotes like these “test”

If those doesn't help, try putting this on the command line: --from-to localBlob

And if that doesn't help, please comment again here.

**Comment by epmck** [comment]
Thanks for your help. Interestingly, it got closer to working in PowerShell, but then I got some authorization error, which is a bit confusing to me as well. Any ideas on what would cause this? 

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====

**Comment by JohnRusk** [comment]
You've previously used azcopy login, right?

It sounds like the account you logged in as doesn't have the necessary rights to the container you are accessing.  Have you given that account Blob Storage Data Contributor role on that container (or Blob Storage Data Owner, also works, I think).  Just the ordinary "Owner" does not work, because its an "admin" owner, not a "data/content" owner.

And wait up to 5 mins for that to take effect, when you grant that role in Portal, before it will be usable by AzCopy.

**Comment by epmck** [comment]
Thank you. No, I have not used AzCopy before, this is my first time. I'll have to look into my rights. Thanks for getting me this far!

**Comment by JohnRusk** [comment]
Good luck.  Check this section of the doc, if you haven't already: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#choose-how-youll-provide-authorization-credentials

I'll close this issue now, since the initial problem is resolved, and the rights issue should be resolvable as per the docs.  Please let us know if you have any problems or need any more help.
