### ISSUE TITLE
AzCopy changes block sizes and block ids on copy

### ISSUE THREAD

**Issue by klesta490** [Azure/azure-storage-azcopy#863]
### Which version of the AzCopy was used? 
10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy "https://storage1.blob.core.windows.net:443/container?CENSORED_SAS_TOKEN" "https://storage2.blob.core.windows.net:443/container?CENSORED_SAS_TOKEN" --recursive=true

### What problem was encountered?
We habe block blobs inside container. For these block blobs azcopy changes block sizes and block ids. This later results in 
`Microsoft.WindowsAzure.Storage.StorageException: The specified blob or block content is invalid.` (inside our app) because our app did not expect block ids and block sizes to change.

### How can we reproduce the problem in the simplest way?
copying block blob that was created with custom block size (we use 32kB and 4MB) and custom block id (we have short e.g. `MDAwMDA=`). 

### Have you found a mitigation/solution?
use old version such 7.2.0-netcore

**Comment by JohnRusk** [comment]
Hi,

When you say it "changes" them, did you mean that the format used by AzCopy changed between version 8 and version 10?  

Yes, it did change at that time. The block size is controllable with a command line parameter, but I'm sorry the block ID format is not.

**Comment by klesta490** [comment]
By "change" I mean completelly different. 
Block size - `32kB`    -> `8MB`
BlockId -> `"MDAwMDA="` -> `"YmM2ZjUxOWMtNTViMi1jYTRjLTY4NDYtMDAxZDhjZDQ4NTBj"`

I see there is 
`--block-size-mb`

propably specifying `0.03125`  would work (`32kB`) 
but it is not very handy, because I want to copy whole container and I have two "types" of block blobs in that container (that differs by block sizes).  Therefore I cannot specify block size on command line.

**Comment by JohnRusk** [comment]
Thanks for the detail.

I presume that your custom code works with the same blobs.  I'm guessing it must be adding blocks to the ones that AzCopy uploads, and you end up with a mix of AzCopy's block IDs and your own block ids, all in the same list sent to CommitBlockList.   

We don't have a good answer to that, I'm sorry.  

AzCopy v10 has been in release for almost a year now, so we cannot change its block ID format - if we did, we'd create similar problems for _other_ customers.

I realise this really leaves you only two options: stay with an old version of AzCopy (which we don't encourage) or change your code to support the new block sizes and id formats.  I'm sorry we don't have any better options to offer.

I'm going to close this issue now, since there's nothing that can be done about this on the AzCopy side.

**Comment by klesta490** [comment]
Ok, Thanks
