### ISSUE TITLE
azcopy upload to adlsgen2 hierarchical namespace taking a long time

### ISSUE THREAD

**Issue by mronnlun** [Azure/azure-storage-azcopy#889]
### Which version of the AzCopy was used? 
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy "https://exampleadlsgen2.blob.core.windows.net/example-container/csv?sv=2019-02-02&ss=bfqt&srt=sco&sp=rwdlacup&se=2020-03-06T22:36:49Z&st=2020-03-06T14:36:49Z&spr=https&sig=xxx" "." --recursive

### What problem was encountered?
The command is showing _INFO: Scanning..._ indefinitely

The folder structure is three levels deep, contains about 75 leaf folders and each leaf folder contains 3 files, 200-500kB in size.

When trying to download a folder with Azure Storage Explorer this error is produced:
cannot start job due to error: could not list files. Failed with error -> github.com/Azure/azure-storage-azcopy/azbfs.newStorageError, /home/vsts/work/1/s/azbfs/zc_storage_error.go:41\\n===== RESPONSE ERROR (ServiceCode=OperationTimedOut) =====\\nDescription=500 Operation could not be completed within the specified time

azcopy bench to the container is showing the same throughput as out internet connection max.

It seems to be enumerating the folders that is taking time, because if I point the command at a leaf folder, then it is finishing quite fast.

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
I don't know what could cause that, sorry.

A few ideas for things you could try:
1. Try changing "blob" to "dfs" in your URL for your copy source. That will use the ADLS Gen2 endpoint instead of the blob one. (Both _should_ work, but in your case it seems sensible to try them individually).
2. If that doesn't work, please look in the Windows Event log for a recent failure message from one of your test runs, and email me the x-ms-request-id if any is there, or else the the x-ms-client-request-id plus the approx date and time of the failure and the name of the storage account. 

My email address is on my profile page.
