### ISSUE TITLE
Slowness issue while coping files between two storage accounts

### ISSUE THREAD

**Issue by vijayraje23** [Azure/azure-storage-azcopy#890]
### Which version of the AzCopy was used?  
> 10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
>Windows server 2012 R2
### What command did you run?
>set AZCOPY_LOG_LOCATION="D:\Azcopy\logs"
>set AZCOPY_JOB_PLAN_LOCATION="D:\Azcopy\logs"

>azcopy cp "https://[Sourceaccount].blob.core.windows.net/[container]/[folder]?<SAS>" "https://[Destaccount].blob.core.windows.net/[container]/[folder]?<SAS>" --recursive=true --log-level=ERROR

### What problem was encountered?
> Copy was running slow, took 7 hours to copy 3200000 files size 800GB
### Have you found a mitigation/solution?
No, 
I have also below queries
1. Do we have any option to check benchmark between two storage account
2. while running copy from windows server, does data copy directly from source to destination storage account or it use windows server for copy.
3. does windows server need high config

**Comment by JohnRusk** [comment]
Hi,  Thanks for reporting this issue. Small files are difficult, because the overhead per file is higher when the files are small, but we normally see better performance than what you are seeing.  In answer to your question:

1. Right now, the only way to benchmark is to run AzCopy copys as you are already doing. BTW, at larger file sizes AzCopy will reach the throughput limit of the account, which is 5, 10, 15 or 25 Gbps depending on region and account type.  But AzCopy can't always reach the account limits when files are small.
2. The data does not go through the server.  But, when files are small, the server has a lot of work to do orchestrating everything (i.e. telling the Service what to copy).
3. Yes, it does help to have at least 8 cores, or more, on the machine running the copy.  If you look at your existing machine when its running an AzCopy copy, you may see that its running low on RAM or that its CPU is maxed out.  If so, one easy solution is to use an Azure VM to run AzCopy.  You can get an VM with 8 or 16 cores, use it to run your copy, then deallallocate it.

Note that by default AzCopy does an extra check at the end of each file:  it queries the destination to see what length the destination thinks the file is, and it compares that to the known length from the source.  AzCopy would report an error if those lengths were ever different.  If you don't want the extra certainty that comes with that check, you can turn it off with `--check-length=false`. That can increase performance a bit when working with small files.

**Comment by vijayraje23** [comment]
Thank you JohnRusk. If we set --check-length=false then can we get information about failed blobs in azcopy logs file.

**--check-length   --> Check the length of a file on the destination after the transfer. If there is a mismatch between source and destination, the transfer is marked as failed. (default true)**

**Comment by JohnRusk** [comment]
If it is true (the default) then AzCopy checks the lengths and records any failures in the log file and in the on-screen summary at the end of the job. (As far as I know, there has never been any length check failure, ever, in any account-to-account copies in the entire life of AzCopy v10.  But it _would_  record a failure if there was one).

If its set to false, it does not do the check, and so there will never be any information about the check in the log file.

Blobs may fail for other reasons (e.g. trying to overwrite a page blob with a block blob of the same name), and those failures will be reported in the log.

Does that answer your question?

**Comment by vijayraje23** [comment]
There is one Azure copy tool available i.e. Fast Data Teansfer(FDT), Can we use that tool to copy data between two storage accounts ?

It is much faster than azopy.

**Comment by JohnRusk** [comment]
I worked on the FDT team before joining the AzCopy team.  Did you test FDT and notice that it was faster, or are you just going from the documentation?    If you have comparative test results, I'd be very interested to hear them.

We are trying to encourage FDT users to switch to AzCopy, for all transfers to Blob Storage.  If you're seeing much better results with FDT, please let us know.

**Comment by vijayraje23** [comment]
Yes John, as per my experience FDT is much faster than azcopy v8 n v10.

**Comment by vijayraje23** [comment]
Also while using Azcopy V10, it showing percentage in first column, Is this
showing percentage based on total files. ?
if Yes then please see below screen shot it showing incorrect value.

[image: image.png]

**Comment by JohnRusk** [comment]
Interesting thanks.  I'd love to better understand cases where FDT is outperforming AzCopy. In the cases where its much faster than AzCopy version 10, how many FDT servers are you using?

As for the percentage question, I can't see your screenshot. (It doesn't seem to have come through). Note: for security, if you re-send it, please make sure that it does NOT include any SAS tokens. E.g. crop the image so that the command line is NOT included.

**Comment by JohnRusk** [comment]
Oh, I realise I never answered your earlier question
> Can we use Fast Data Transfer to copy data between two storage accounts ?

I actively discourage that, because we are investing all our efforts in AzCopy, for both support and feature development.  And because AzCopy has more robust mechanisms to cope with failures.  Also, for copying between accounts, in all cases except very small files, AzCopy v10 is actually much faster.

However... it is possible.  There are instructions in the FAQ part of the Fast Data Transfer documentation (there's a lot of FAQ's so you'll have to skim read the headings to find the one you want).

**Comment by JohnRusk** [comment]
We are making some improvements soon that might help in some cases.  I'd suggest testing with version 10.5 when it comes out.

**Comment by zezha-msft** [comment]
AzCopy V10.5 (which has the improvement for scanning blobs faster) is out. It should help in speeding up small blob jobs.
