### ISSUE TITLE
Copying a folder from a public container

### ISSUE THREAD

**Issue by agentmorris** [Azure/azure-storage-azcopy#896]
### Which version of the AzCopy was used? 

10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows and Linux

### What command did you run?

azcopy cp "http://container.blob.core.windows.net/container/folder/folder" "c:\local_folder" --recursive

...where the container is public for read and list access (i.e., public at the container level).

### What problem was encountered?

We get the following error message:

failed to obtain credential info: no SAS token or OAuth token is present and the resource is not public

The following works fine for the same container, which indicates that the container definitely has the right public access level:

azcopy cp "http://container.blob.core.windows.net/container" "c:\local_folder" --recursive

azcopy cp supports copying at the folder level when a SAS token is present, and I couldn't find any documentation to suggest that this *isn't* supported for public containers.  At the very least, this error message is incorrect, because the resource is in fact public.

We get the same result using the list-of-files option, which I think shouldn't require enumeration at all, i.e. shouldn't even require the container to be public (only for the blobs to be public).  This is in fact our more immediate need; we actually have a list of files that we want to copy, but we got the same error, which led to the simpler test of just recursively copying a folder.

### How can we reproduce the problem in the simplest way?

I believe the above to be reproducible.

### Have you found a mitigation/solution?

Not yet.

Thanks!

**Comment by adreed-msft** [comment]
So, in order to check access to a container, we try to ping the blob specifically (or the container, if it's a container URL). It may be worthwhile for us to drop to the container level and try a list call, I think.

This is a usability issue. Thanks for reporting it.

If you need a workaround in the meantime, target the container, and use a --include-path filter.

**Comment by agentmorris** [comment]
include_path is a good tip, thanks... I verified that this works for the folder-level problem listed above (though it results in a different output folder structure, so it's not a 1:1 replacement, but it basically addresses the issue).

Our real scenario is that we have a list of many files that we want to download from a public container, trying to assess whether there's any way of doing that with azcopy.  --include-path doesn't really help here, because for any real list we'll hit OS/shell limits on command line length.  --list-of-files is what I really want to use, but it's unclear how --list-of-files interacts with --include-path; is there any way to get around this issue for --list-of-files?

Thanks.

**Comment by JohnRusk** [comment]
--list-of-files IS --include-path.  I.e. the both have the same implementation, one just reads from a file instead of the command line.

Note that there is a known performance issue when you have a large number of files listed in list-of-files and your source is remote (i.e. not local disk). The issues is that we probe/query each one to see whether its a folder or a file, and that has a performance cost.  We're aware of this issue, and its on our list to be fixed one day.  It is the reason we are not yet "unhiding" the list-of-files parameter to make it appear in the in-app help.

**Comment by agentmorris** [comment]
This is super-helpful, that clears everything up.  I can't have my cake and eat it too (yet) (i.e., I can't retrieve a list of files from a public blob URL), so I think I will solve our particular situation by using a SAS key where I didn't originally want to use a SAS key.  This is not the end of the world for our scenario.  Closing this issue.  Thanks!
