### ISSUE TITLE
`azcopy make [URL]` fails on MacOS 10.15.3 when run in a bash script

### ISSUE THREAD

**Issue by ausfestivus** [Azure/azure-storage-azcopy#897]
### Which version of the AzCopy was used? 

```
😀 abest@BARMIX2:~ $ ./bin/azcopy 
AzCopy 10.3.4
...
```

### Which platform are you using? (ex: Windows, Mac, Linux)

MacOS 10.15.3

### What command did you run?
`azcopy make 'https://acctname.blob.core.windows.net/containername'`

### What problem was encountered?

When the above command is run as part of a bash script (which contains a preceding `az login` command) it fails with:

```
INFO: Use anonymous credential by default for location '1'

operation not supported, cannot create resource $%7BDST_URL%7D type at the moment
./scripts/SCRIPTNAME.sh: line 103: 1: command not found
```

### How can we reproduce the problem in the simplest way?

Some pseudo code:
* create new bash script
* `az login --service-principle yada yada`
* `azcopy make 'URL'`

### Have you found a mitigation/solution?

No.

**Comment by JohnRusk** [comment]
Is most probably an issue with the keychain (which is where login stores the creds). 

I see the source code says this
"// For SSH environment, user needs to unlock login keychain once, to enable AzCopy to Add/Update/Retrieve/Delete key.
// For Mac UI or terminal environment, unlock is not mandatory.
// For more details about Apple keychain support: https://developer.apple.com/documentation/security/keychain_services?language=objc
"
If that doesn't help, I'd suggest somehow investigating the mac equivalent of [this workaround](https://github.com/Azure/azure-storage-azcopy/issues/452#issuecomment-503812803) (if such an equivalent exists)

**Comment by ausfestivus** [comment]
Yea, sorry no idea about a Mac equivalent. Did some googling around it but nothing obvious popped up.

**Comment by JohnRusk** [comment]
It works when run interactively? (Outside the bash script?)

**Comment by ausfestivus** [comment]
The `azcopy make [URL]` command does work outside the bash script. Output is:

```
INFO: Make is using OAuth token for authentication.

Successfully created the resource.
```

**Comment by JohnRusk** [comment]
You might be able to do this... (this is basically the same process that I followed to come up with that workaround for Linux)

1. login to AzCopy (outside of bash)
2. Use this command, [security](https://ss64.com/osx/security.html), to dump contents of the keychain(s). I presume AzCopy is using the "login key chain".  Try to find the AzCopy entry in the chain.   We use a service name of "AzCopyV10" and an account name of "AzCopyOAuthTokenCache".
3. Now write a bash script that runs the same security commands.  Run the script. I suspect it will _not_ show the same things that you found in step 2.  At that point, you've proved that the issue is what we think it is.  I don't have enough knowlegde of the keychain and security app to say what to do next, but something along the lines of unlocking it, or setting a different default keychain for the bash session, or something like that, might help.
