### ISSUE TITLE
azcopy list: unable to specify folder depth to list

### ISSUE THREAD

**Issue by ezra-at-lumedic** [Azure/azure-storage-azcopy#914]
##### Note: The version is visible when running AzCopy without any argument

10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy ls URL-goes-here

### What problem was encountered?

It lists the contents of every folder under that URL.  Not what I want at all.  

### How can we reproduce the problem in the simplest way?

Trivial.  This is a feature need/request.  The current tools is very limited and doesn't give what's desired.

### Have you found a mitigation/solution?

Nope.

**Comment by adreed-msft** [comment]
Interesting request. Could you think of a case where this would be useful?

**Comment by ezra-at-lumedic** [comment]
Let's say I've mapped hundreds of large database takes to blob storage. Let's say I want to do processing on them in Databricks, so I break them into ~100MB parquet files. Each folder represents a table and each table has potentially hundreds of files within it.

I now want to know, which tables are mapped to blob storage and the tool doesn't give me a simple way to do that. The tool doesn't even give what the API gives, so rather then being a tool it is an obstacle or at least a distraction.

So the best is to throw it out.

If I use it in its current form I have to pipe the output throw sed or similar (and hope I'm not forced to use a Windows box where such tools aren't built in).

That's one of signs of use cases.

I'm sure you can use your imagination to see others that occur regularly.



Sent from my mobile, please expect typos.
________________________________

**Comment by maumoura** [comment]
I +1 this one.
We have an storage that has perhaps 10 top folders. But those have perhaps thousands or millions of files underneath them... _azcopy list_ on the top level takes forever because it tries to list every single file in the storage, even if I just want to check the names of 10 folders or so.

**Comment by vibhansa-msft** [comment]
Even if directory depth is an option on the cli, how does it help resolve the issue you face. If you have 10 folders at top level and then possibly millions of files/directories inside it, with potential depth specified it will stop iterating after a certain level. But at the end you wish to copy those files as well in which case you will have to start another azcopy job for that path. If that's what you are going to do then why not start a azcopy job for each of the folder idependently so that azcopy does not have to iterate all of them in one go rather each instance iterate it independently.
